### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by imranhashmi** [playgameservices/play-games-plugin-for-unity#116]
Hi guys,

I am trying to integrate play games plugin into unity and getting Authentication failed everytime I login with test user. Our game is published but our game service is not published yet. 

I have followed the guide and setup the game service , linked the app , setup the client id for the app in Google Developer Console. As far as I know all my values are correct.  and match but still I get this .

In the LogCat there is this line in red only two times i.e. before the error happens and after the error happens. 
```
E/NavigationBar(22192): meta-data ==> set Navi Bg (package:com.dubaipolice.uaedrifting, portResource ID:0, landResource ID:0, alpha:0)
```
What is this?

This is the full log I get when I try to authenticate. 
```
05-08 14:15:56.831: W/PopupManager(22192): You have not specified a View to use as content view for popups. Falling back to the Activity content view which may not work properly in future versions of the API. Use setViewForPopups() to set your content view.
05-08 14:15:57.051: V/Activity(22192): [DSDR][Activity.java]isExternal() : extUsage == 0
05-08 14:15:57.461: V/AudioTrack(22192): stop 0x6211a9c0
05-08 14:15:57.471: V/AudioTrack(22192): stop 0x6211a9c0
05-08 14:15:57.471: V/AudioTrack(22192): stop 0x6211a9c0
05-08 14:15:57.471: V/AudioTrack(22192): stop 0x6211a9c0
05-08 14:15:57.491: W/GameHelper(22192): GameHelper.enableDebugLog(boolean,String) is deprecated. Use GameHelper.enableDebugLog(boolean)
05-08 14:15:57.501: W/PopupManager(22192): You have not specified a View to use as content view for popups. Falling back to the Activity content view which may not work properly in future versions of the API. Use setViewForPopups() to set your content view.
05-08 14:15:57.541: E/NavigationBar(22192): meta-data ==> set Navi Bg (package:com.dubaipolice.uaedrifting, portResource ID:0, landResource ID:0, alpha:0)
05-08 14:15:57.631: D/View(22192): View.setSystemUiVisibility .. packageName : com.dubaipolice.uaedrifting
05-08 14:15:57.631: D/View(22192): View.setSystemUiVisibility ..  : mParent.recomputeViewAttributes called
05-08 14:15:57.691: V/Activity(22192): [DSDR][Activity.java]isExternal() : extUsage == 0
05-08 14:15:58.631: D/View(22192): View.setSystemUiVisibility .. packageName : com.dubaipolice.uaedrifting
05-08 14:15:58.631: D/View(22192): View.setSystemUiVisibility ..  : mParent.recomputeViewAttributes called
05-08 14:16:02.381: W/GameHelper(22192): disconnect() called when client was already disconnected.
05-08 14:16:02.381: W/GameHelper(22192): ****
05-08 14:16:02.381: W/GameHelper(22192): ****
05-08 14:16:02.381: W/GameHelper(22192): **** APP NOT CORRECTLY CONFIGURED TO USE GOOGLE PLAY GAME SERVICES
05-08 14:16:02.381: W/GameHelper(22192): **** This is usually caused by one of these reasons:
05-08 14:16:02.381: W/GameHelper(22192): **** (1) Your package name and certificate fingerprint do not match
05-08 14:16:02.381: W/GameHelper(22192): ****     the client ID you registered in Developer Console.
05-08 14:16:02.381: W/GameHelper(22192): **** (2) Your App ID was incorrectly entered.
05-08 14:16:02.381: W/GameHelper(22192): **** (3) Your game settings have not been published and you are 
05-08 14:16:02.381: W/GameHelper(22192): ****     trying to log in with an account that is not listed as
05-08 14:16:02.381: W/GameHelper(22192): ****     a test account.
05-08 14:16:02.381: W/GameHelper(22192): ****
05-08 14:16:02.381: W/GameHelper(22192): **** To help you debug, here is the information about this app
05-08 14:16:02.381: W/GameHelper(22192): **** Package name         : com.dubaipolice.uaedrifting (this is also same in android manifest)
05-08 14:16:02.381: W/GameHelper(22192): **** Cert SHA1 fingerprint: XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX (I have hide this but its same in google dev console and my keystore is signed with the same)
05-08 14:16:02.381: W/ResourceType(22192): No package identifier when getting value for resource number 0x00000000
05-08 14:16:02.381: W/System.err(22192): android.content.res.Resources$NotFoundException: String resource ID #0x0
05-08 14:16:02.381: W/System.err(22192): 	at android.content.res.Resources.getText(Resources.java:231)
05-08 14:16:02.381: W/System.err(22192): 	at android.content.res.Resources.getString(Resources.java:315)
05-08 14:16:02.381: W/System.err(22192): 	at com.google.example.games.basegameutils.GameHelperUtils.getAppIdFromResource(GameHelperUtils.java:125)
05-08 14:16:02.381: W/System.err(22192): 	at com.google.example.games.basegameutils.GameHelperUtils.printMisconfiguredDebugInfo(GameHelperUtils.java:109)
05-08 14:16:02.381: W/System.err(22192): 	at com.google.example.games.basegameutils.GameHelper.giveUp(GameHelper.java:791)
05-08 14:16:02.391: W/System.err(22192): 	at com.google.example.games.basegameutils.GameHelper.onActivityResult(GameHelper.java:533)
05-08 14:16:02.391: W/System.err(22192): 	at com.google.example.games.pluginsupport.HelperActivity.onActivityResult(HelperActivity.java:41)
05-08 14:16:02.391: W/System.err(22192): 	at android.app.Activity.dispatchActivityResult(Activity.java:5421)
05-08 14:16:02.391: W/System.err(22192): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3350)
05-08 14:16:02.391: W/System.err(22192): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3397)
05-08 14:16:02.391: W/System.err(22192): 	at android.app.ActivityThread.access$1100(ActivityThread.java:146)
05-08 14:16:02.391: W/System.err(22192): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1288)
05-08 14:16:02.391: W/System.err(22192): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-08 14:16:02.391: W/System.err(22192): 	at android.os.Looper.loop(Looper.java:137)
05-08 14:16:02.391: W/System.err(22192): 	at android.app.ActivityThread.main(ActivityThread.java:5171)
05-08 14:16:02.391: W/System.err(22192): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-08 14:16:02.391: W/System.err(22192): 	at java.lang.reflect.Method.invoke(Method.java:511)
05-08 14:16:02.391: W/System.err(22192): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
05-08 14:16:02.391: W/System.err(22192): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
05-08 14:16:02.391: W/System.err(22192): 	at dalvik.system.NativeStart.main(Native Method)
05-08 14:16:02.391: W/GameHelper(22192): **** App ID from          : ??? (failed to retrieve APP ID)
05-08 14:16:02.391: W/GameHelper(22192): ****
05-08 14:16:02.391: W/GameHelper(22192): **** Check that the above information matches your setup in 
05-08 14:16:02.391: W/GameHelper(22192): **** Developer Console. Also, check that you're logging in with the
05-08 14:16:02.391: W/GameHelper(22192): **** right account (it should be listed in the Testers section if
05-08 14:16:02.391: W/GameHelper(22192): **** your project is not yet published).
05-08 14:16:02.391: W/GameHelper(22192): ****
05-08 14:16:02.391: W/GameHelper(22192): **** For more information, refer to the troubleshooting guide:
05-08 14:16:02.391: W/GameHelper(22192): ****   http://developers.google.com/games/services/android/troubleshooting
05-08 14:16:02.631: E/NavigationBar(22192): meta-data ==> set Navi Bg (package:com.dubaipolice.uaedrifting, portResource ID:0, landResource ID:0, alpha:0)
```

**Comment by claywilkinson** [comment]
closing since it is old and the plug in has been re-architected so this log is obsolete.
