### ISSUE TITLE
ERROR: Exception launching bridge intent: java.lang.ClassNotFoundException: com.google.games.bridge.NativeBridgeActivity

### ISSUE THREAD

**Issue by claudiojundi** [playgameservices/play-games-plugin-for-unity#1167]
Hi im trying to show the leaderboard ui or achievement ui unsuccessfully

Im using 
GooglePlayGamesPlugin-0.9.33
Unity 5.3.5.f1 Personal

first it is logging correctly 

`SocialController Autheticate success = True`

but when i click on button to show leaderboard ui i receive this log

```

  [Play Games Plugin DLL] 05/21/16 1:52:10 -03:00 DEBUG: ShowLeaderboardUI with default ID
05-21 01:52:10.445 11244-11260/? I/Unity:  
05-21 01:52:10.445 11244-11260/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-21 01:52:10.447 11244-11260/? I/Unity:  [Play Games Plugin DLL] 05/21/16 1:52:10 -03:00 DEBUG: ShowLeaderboardUI, lbId= callback is 
05-21 01:52:10.447 11244-11260/? I/Unity:  
05-21 01:52:10.447 11244-11260/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-21 01:52:10.456 11244-11325/? I/Unity:  [Play Games Plugin DLL] 05/21/16 1:52:10 -03:00 DEBUG: Entering internal callback for AndroidPlatformConfiguration#InternalIntentHandler
05-21 01:52:10.456 11244-11325/? I/Unity:  
05-21 01:52:10.456 11244-11325/? I/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-21 01:52:10.472 11244-11260/? W/Unity: *** [Play Games Plugin DLL] 05/21/16 1:52:10 -03:00 ERROR: Exception launching bridge intent: java.lang.ClassNotFoundException: com.google.games.bridge.NativeBridgeActivity
05-21 01:52:10.472 11244-11260/? W/Unity:  
05-21 01:52:10.472 11244-11260/? W/Unity: (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-21 01:52:10.486 11244-11260/? W/Unity: *** [Play Games Plugin DLL] 05/21/16 1:52:10 -03:00 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.NativeBridgeActivity
05-21 01:52:10.486 11244-11260/? W/Unity: java.lang.ClassNotFoundException: com.google.games.bridge.NativeBridgeActivity
05-21 01:52:10.486 11244-11260/? W/Unity:     at java.lang.Class.classForName(Native Method)
05-21 01:52:10.486 11244-11260/? W/Unity:     at java.lang.Class.forName(Class.java:324)
05-21 01:52:10.486 11244-11260/? W/Unity:     at java.lang.Class.forName(Class.java:285)
05-21 01:52:10.486 11244-11260/? W/Unity:     at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
05-21 01:52:10.486 11244-11260/? W/Unity:     at com.unity3d.player.UnityPlayer.a(Unknown Source)
05-21 01:52:10.486 11244-11260/? W/Unity:     at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
05-21 01:52:10.486 11244-11260/? W/Unity:  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.games.bridge.NativeBridgeActivity" on path: DexPathList[[zip file "/data/app/com.jsassaki.superpath-1/base.apk"],nativeLibraryDirectories=[/data/app/com.jsassaki.superpath-1/lib/arm, /data/app/com.jsassaki.superpath-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
05-21 01:52:10.486 11244-11260/? W/Unity:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-21 01:52:10.486 11244-11260/? W/Unity: 	at java.lang.ClassLoader.loadClass(Class
```

**Comment by claywilkinson** [comment]
Glad you got it working!

**Comment by Chiejina** [comment]
Can you be specific in what you mean you wrote

"compile files('libs/play-games-plugin-support.jar')"

My files are in the same place but my Android manifest doesn't seem to merge all the manifests correctly.

**Comment by AbrarTaurus** [comment]
Thank you man for your hint.@claudiojundi
I solved my issue with just copying the file "play-games-plugin-support.jar" at this location "Assets\Plugins\Android\MainLibProj\libs" from another project. I missed this file while manually adding .jar file.
