### ISSUE TITLE
Authorization Error when signing in

### ISSUE THREAD

**Issue by shite** [playgameservices/play-games-plugin-for-unity#1238]
Hey guys! I set a test game for Android and was trying out signing in. When I do it, my name appears for like a second then the name just disappears right away and the authorization fails. My email is set as a tester in the Developer Console. This is the log:

`I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:32 -04:00 DEBUG: Star
ting Auth Transition. Op: SIGN_IN status: VALID
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
W/GamesServiceBroker( 3558): Client connected with SDK 8487000, Services 9082036
, and Games 37230036
D/ActivityManager( 2461): caller:android.app.ApplicationThreadProxy@43e99458, r.
packageName :com.google.android.gms
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:32 -04:00 DEBUG: Ente
ring internal callback for PlayerManager#InternalFetchSelfCallback
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:32 -04:00 DEBUG: Popu
lating User
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:32 -04:00 DEBUG: Foun
d User: [Player: 'shlte' (id g06981514943057957822)]
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:32 -04:00 DEBUG: Mayb
e finish for User
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:32 -04:00 DEBUG: Auth
 not finished. User=[Player: 'shlte' (id g06981514943057957822)] achievements=
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
V/GamesNativeSDK(19715): Encountered GmsCore error with status code: 4
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:33 -04:00 DEBUG: Ente
ring internal callback for AchievementManager#InternalFetchAllCallback
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:33 -04:00 DEBUG: Popu
lating Achievements, status = ERROR_INTERNAL
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
W/Unity   (19715): *** [Play Games Plugin DLL] 06/16/16 21:26:33 -04:00 ERROR: E
rror retrieving achievements - check the log for more information. Failing signi
n.
W/Unity   (19715):
W/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
W/Unity   (19715):
I/GamesNativeSDK(19715): Auth operation started: SIGN OUT
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:33 -04:00 DEBUG: Invo
king user callback on game thread
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:33 -04:00 DEBUG: Star
ting Auth Transition. Op: SIGN_OUT status: ERROR_NOT_AUTHORIZED
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
D/ActivityManager( 2461): caller:android.app.ApplicationThreadProxy@436ce178, r.
packageName :com.google.android.gms
W/GamesServiceBroker( 3558): Client connected with SDK 8487000, Services 9082036
, and Games 37230036
`

**Comment by claywilkinson** [comment]
Does it consistently fail, or is it intermettent? Can you post an unfiltered log when you get the ERROR_INTERNAL response?

**Comment by shite** [comment]
It consistantly fails. It doesn't crash, it just fails to sign in. Ill give the unfiltered log after I get home.

**Comment by shite** [comment]
Here is the log without filters:

your content view.
I/GamesNativeSDK(19715): Successfully connected to Google Play.
D/dalvikvm( 2461): GC_CONCURRENT freed 861K, 27% free 34482K/47060K, paused 8ms+
30ms, total 423ms
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:32 -04:00 DEBUG: Star
ting Auth Transition. Op: SIGN_IN status: VALID
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
W/GamesServiceBroker( 3558): Client connected with SDK 8487000, Services 9082036
, and Games 37230036
D/ActivityManager( 2461): caller:android.app.ApplicationThreadProxy@43e99458, r.
packageName :com.google.android.gms
W/System.err( 2461): java.io.FileNotFoundException: /data/system/users/0/res_com
.google.android.gms.xml: open failed: ENOENT (No such file or directory)
W/System.err( 2461):    at libcore.io.IoBridge.open(IoBridge.java:409)
W/System.err( 2461):    at java.io.RandomAccessFile.<init>(RandomAccessFile.java
:118)
W/System.err( 2461):    at android.util.XmlMoreAtomicFile.isDamaged(XmlMoreAtomi
cFile.java:53)
W/System.err( 2461):    at android.util.MoreAtomicFile.openRead(MoreAtomicFile.j
ava:114)
D/MoreAtomicFile( 2461): /data/system/users/0/res_com.google.android.gms.xml dur
ing check if it is damaged, rename it to /data/system/users/0/res_com.google.and
roid.gms.xml.crt
W/System.err( 2461):    at com.android.server.pm.UserManagerService.readApplicat
ionRestrictionsLocked(UserManagerService.java:1584)
W/System.err( 2461):    at com.android.server.pm.UserManagerService.getApplicati
onRestrictionsForUser(UserManagerService.java:1374)
W/System.err( 2461):    at com.android.server.pm.UserManagerService.getApplicati
onRestrictions(UserManagerService.java:1357)
W/System.err( 2461):    at android.os.IUserManager$Stub.onTransact(IUserManager.
java:254)
W/System.err( 2461):    at android.os.Binder.execTransact(Binder.java:404)
W/System.err( 2461):    at dalvik.system.NativeStart.run(Native Method)
W/System.err( 2461): Caused by: libcore.io.ErrnoException: open failed: ENOENT (
No such file or directory)
W/System.err( 2461):    at libcore.io.Posix.open(Native Method)
W/System.err( 2461):    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
W/System.err( 2461):    at libcore.io.IoBridge.open(IoBridge.java:393)
W/System.err( 2461):    ... 9 more
D/ActivityManager( 2461): caller:android.app.ApplicationThreadProxy@43dba740, r.
packageName :com.google.android.gms
D/ActivityManager( 2461): caller:android.app.ApplicationThreadProxy@43cd1fa0, r.
packageName :com.google.android.gms
D/ActivityManager( 2461): caller:android.app.ApplicationThreadProxy@43ca44f8, r.
packageName :com.google.android.gms
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:32 -04:00 DEBUG: Ente
ring internal callback for PlayerManager#InternalFetchSelfCallback
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:32 -04:00 DEBUG: Popu
lating User
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:32 -04:00 DEBUG: Foun
d User: [Player: 'shlte' (id g06981514943057957822)]
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:32 -04:00 DEBUG: Mayb
e finish for User
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:32 -04:00 DEBUG: Auth
 not finished. User=[Player: 'shlte' (id g06981514943057957822)] achievements=
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
D/KeyguardUpdateMonitor( 2716): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2716): handleKeyguardVisibilityChanged(1)
I/SurfaceFlinger( 1971): id=482 Removed TignInActiv (10/11)
I/SurfaceFlinger( 1971): id=482 Removed TignInActiv (-2/11)
D/KeyguardUpdateMonitor( 2716): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2716): handleKeyguardVisibilityChanged(1)
I/SurfaceFlinger( 1971): id=485 createSurf (1x1),1 flag=4,
D/KeyguardUpdateMonitor( 2716): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2716): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 2716): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2716): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 2716): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2716): handleKeyguardVisibilityChanged(1)
D/BarController.StatusBar( 2461): mState: WINDOW_STATE_HIDDEN
D/PhoneStatusBar( 2716): Status bar WINDOW_STATE_HIDDEN
D/ActivityManager( 2461): bindService callerProcessName:com.google.android.gms,
calleePkgName: com.google.android.gms, action: null
D/ActivityManager( 2461): bindService callerProcessName:com.google.android.gms,
calleePkgName: com.google.android.gms, action: null
D/KeyguardUpdateMonitor( 2716): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2716): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 2716): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2716): handleKeyguardVisibilityChanged(1)
D/AudioPlayer(20938): [LatencyCheck] releasing media player
V/MediaPlayer-JNI(20938): release
V/MediaPlayer(20938): setListener
V/MediaPlayer(20938): disconnect
V/MediaPlayer(20938): destructor
V/MediaPlayer(20938): disconnect
E/Volley  ( 3558): [146] BasicNetwork.performRequest: Unexpected response code 4
04 for https://www.googleapis.com/games/v1/applications/played
W/GameAgent( 3558): Volley error when reporting played
W/GameAgent( 3558): com.android.volley.ServerError
W/GameAgent( 3558):     at com.android.volley.toolbox.BasicNetwork.performReques
t(SourceFile:163)
W/GameAgent( 3558):     at iyi.performRequest(SourceFile:64)
W/GameAgent( 3558):     at com.android.volley.NetworkDispatcher.run(SourceFile:1
13)
D/dalvikvm( 3558): GC_CONCURRENT freed 2314K, 27% free 16018K/21932K, paused 7ms
+9ms, total 98ms
E/DataBuffer( 3558): Internal data leak within a DataBuffer object detected!  Be
 sure to explicitly call release() on all DataBuffer extending objects when you
are done with them. (internal object: com.google.android.gms.common.data.DataHol
der@4280fca8)
E/Volley  ( 3558): [145] BasicNetwork.performRequest: Unexpected response code 4
04 for https://www.googleapis.com/games/v1/achievements?language=en_US
W/AchievementAgent( 3558): {"code":404,"errors":[{"message":"The requested appli
cation with ID 571707973781 was not found.","domain":"global","reason":"notFound
"}]}
E/Volley  ( 3558): [143] BasicNetwork.performRequest: Unexpected response code 4
04 for https://www.googleapis.com/games/v1/events?language=en_US
D/ActivityManager( 2461): bindService callerProcessName:com.google.android.gms,
calleePkgName: com.google.android.gms, action: null
W/EventAgent( 3558): {"code":404,"errors":[{"message":"The requested application
 with ID 571707973781 was not found.","domain":"global","reason":"notFound"}]}
W/AppOps  ( 2461): Bad call: specified package com.google.android.play.games und
er uid 10322 but it is really 10134
W/AppOps  ( 2461): Bad call: specified package com.google.android.play.games und
er uid 10322 but it is really 10134
V/GamesNativeSDK(19715): Encountered GmsCore error with status code: 4
W/GamesNativeSDK(19715): Could not automatically seed event cache.
E/Volley  ( 3558): [144] BasicNetwork.performRequest: Unexpected response code 4
04 for https://www.googleapis.com/games/v1/players/g06981514943057957822/achieve
ments?language=en_US&state=ALL
W/AchievementAgent( 3558): {"code":404,"errors":[{"message":"The requested appli
cation with ID 571707973781 was not found.","domain":"global","reason":"notFound
"}]}
W/AppOps  ( 2461): Bad call: specified package com.google.android.play.games und
er uid 10322 but it is really 10134
W/AppOps  ( 2461): Bad call: specified package com.google.android.play.games und
er uid 10322 but it is really 10134
V/GamesNativeSDK(19715): Encountered GmsCore error with status code: 4
W/GamesNativeSDK(19715): Could not automatically seed achievement cache.
D/ActivityManager( 2461): bindService callerProcessName:com.google.android.gms,
calleePkgName: com.google.android.gms, action: null
D/KeyguardUpdateMonitor( 2716): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2716): handleKeyguardVisibilityChanged(1)
D/STATUSBAR-StatusBarManagerService( 2461): manageDisableList what=0x0 pkg=Windo
wManager.LayoutParams
D/KeyguardUpdateMonitor( 2716): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2716): handleKeyguardVisibilityChanged(1)
D/RestrictionPolicy( 2461): isStatusBarExpansionAllowed : true
E/Volley  ( 3558): [146] BasicNetwork.performRequest: Unexpected response code 4
04 for https://www.googleapis.com/games/v1/achievements?language=en_US
W/AchievementAgent( 3558): {"code":404,"errors":[{"message":"The requested appli
cation with ID 571707973781 was not found.","domain":"global","reason":"notFound
"}]}
D/ActivityManager( 2461): bindService callerProcessName:com.google.android.gms,
calleePkgName: com.google.android.gms, action: null
E/Volley  ( 3558): [145] BasicNetwork.performRequest: Unexpected response code 4
04 for https://www.googleapis.com/games/v1/players/g06981514943057957822/achieve
ments?language=en_US&state=ALL
W/AchievementAgent( 3558): {"code":404,"errors":[{"message":"The requested appli
cation with ID 571707973781 was not found.","domain":"global","reason":"notFound
"}]}
W/AppOps  ( 2461): Bad call: specified package com.google.android.play.games und
er uid 10322 but it is really 10134
W/AppOps  ( 2461): Bad call: specified package com.google.android.play.games und
er uid 10322 but it is really 10134
V/GamesNativeSDK(19715): Encountered GmsCore error with status code: 4
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:33 -04:00 DEBUG: Ente
ring internal callback for AchievementManager#InternalFetchAllCallback
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:33 -04:00 DEBUG: Popu
lating Achievements, status = ERROR_INTERNAL
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
W/Unity   (19715): *** [Play Games Plugin DLL] 06/16/16 21:26:33 -04:00 ERROR: E
rror retrieving achievements - check the log for more information. Failing signi
n.
W/Unity   (19715):
W/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
W/Unity   (19715):
I/GamesNativeSDK(19715): Auth operation started: SIGN OUT
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:33 -04:00 DEBUG: Invo
king user callback on game thread
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
E/PopupManager( 3558): No content view usable to display popups. Popups will not
 be displayed in response to this client's calls. Use setViewForPopups() to set
your content view.
D/AccountUtils( 3558): Clearing selected account for com.Shite_Games.SHPIN
D/ActivityManager( 2461): caller:android.app.ApplicationThreadProxy@4370ac08, r.
packageName :com.google.android.gms
E/ViewRootImpl( 3558): Attempting to destroy the window while drawing!
E/ViewRootImpl( 3558):   window=android.view.ViewRootImpl@426f5080, title=
I/Unity   (19715):  [Play Games Plugin DLL] 06/16/16 21:26:33 -04:00 DEBUG: Star
ting Auth Transition. Op: SIGN_OUT status: ERROR_NOT_AUTHORIZED
I/Unity   (19715):
I/Unity   (19715): (Filename: ./artifacts/generated/common/runtime/UnityEngineDe
bugBindings.gen.cpp Line: 37)
I/Unity   (19715):
D/ActivityManager( 2461): caller:android.app.ApplicationThreadProxy@436ce178, r.
packageName :com.google.android.gms
W/GamesServiceBroker( 3558): Client connected with SDK 8487000, Services 9082036
, and Games 37230036
I/SurfaceFlinger( 1971): id=485 Removed  (9/11)
I/SurfaceFlinger( 1971): id=485 Removed  (-2/11)
D/KeyguardUpdateMonitor( 2716): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 2716): handleKeyguardVisibilityChanged(1)
D/ActivityManager( 2461): caller:android.app.ApplicationThreadProxy@43668a88, r.
packageName :com.google.android.gms
W/System.err( 2461): java.io.FileNotFoundException: /data/system/users/0/res_com
.google.android.gms.xml: open failed: ENOENT (No such file or directory)
W/System.err( 2461):    at libcore.io.IoBridge.open(IoBridge.java:409)
D/MoreAtomicFile( 2461): /data/system/users/0/res_com.google.android.gms.xml dur
ing check if it is damaged, rename it to /data/system/users/0/res_com.google.and
roid.gms.xml.crt
W/System.err( 2461):    at java.io.RandomAccessFile.<init>(RandomAccessFile.java
:118)
W/System.err( 2461):    at android.util.XmlMoreAtomicFile.isDamaged(XmlMoreAtomi
cFile.java:53)
W/System.err( 2461):    at android.util.MoreAtomicFile.openRead(MoreAtomicFile.j
ava:114)
W/System.err( 2461):    at com.android.server.pm.UserManagerService.readApplicat
ionRestrictionsLocked(UserManagerService.java:1584)
W/System.err( 2461):    at com.android.server.pm.UserManagerService.getApplicati
onRestrictionsForUser(UserManagerService.java:1374)
W/System.err( 2461):    at com.android.server.pm.UserManagerService.getApplicati
onRestrictions(UserManagerService.java:1357)
W/System.err( 2461):    at android.os.IUserManager$Stub.onTransact(IUserManager.
java:254)
W/System.err( 2461):    at android.os.Binder.execTransact(Binder.java:404)
W/System.err( 2461):    at dalvik.system.NativeStart.run(Native Method)
W/System.err( 2461): Caused by: libcore.io.ErrnoException: open failed: ENOENT (
No such file or directory)
W/System.err( 2461):    at libcore.io.Posix.open(Native Method)
W/System.err( 2461):    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
W/System.err( 2461):    at libcore.io.IoBridge.open(IoBridge.java:393)
W/System.err( 2461):    ... 9 more
W/ActivityManager( 2461): mDVFSHelper.release()
D/dalvikvm( 2461): GC_CONCURRENT freed 307K, 27% free 34430K/47060K, paused 12ms
+18ms, total 289ms
D/SSRMv2:SIOP( 2461): SIOP:: AP = 300 (0), Delta = 0
D/STATUSBAR-NetworkController( 2716): refreshSignalCluster - setNWBoosterIndicat
ors(false)
D/STATUSBAR-NetworkController( 2716): refreshSignalCluster: data=-1 bt=false
D/STATUSBAR-IconMerger( 2716): checkOverflow(336), More:false, Req:false Child:4

D/BatteryService( 2461): level:100, scale:100, status:5, health:2, present:true,
 voltage: 4294, temperature: 301, technology: Li-ion, AC powered:false, USB powe
red:true, Wireless powered:false, icon:17303674, invalid charger:0, online:4, cu
rrent avg:460, charge type:0, power sharing:false, high voltage charger:false
D/BatteryService( 2461): Sending ACTION_BATTERY_CHANGED.
D/KeyguardUpdateMonitor( 2716): received broadcast android.intent.action.BATTERY
_CHANGED
D/KeyguardUpdateMonitor( 2716): handleBatteryUpdate
D/STATUSBAR-PhoneStatusBar( 2716):  mBrightnessEnablebySettings = true mBrightne
ssEnablebyBattery = true mBrightnessEnablebyDisableFlag = true mPmsBrightnessEna
blebySettings = true
I/BusinessExecutor( 2956): registered Task#1067 : PowerInfoEventSource$1
I/BusinessExecutor( 2956): Task#1067 : #run() called
I/BusinessExecutor( 2956): Task#1067 : #run() ended
D/BatteryMeterView( 2716): ACTION_BATTERY_CHANGED : level:100 status:5 health:2
D/STATUSBAR-NetworkController( 2716): refreshSignalCluster - setNWBoosterIndicat
ors(false)
D/STATUSBAR-NetworkController( 2716): refreshSignalCluster: data=-1 bt=false
D/STATUSBAR-IconMerger( 2716): checkOverflow(336), More:false, Req:false Child:4

D/STATUSBAR-NetworkController( 2716): refreshSignalCluster - setNWBoosterIndicat
ors(false)
D/STATUSBAR-NetworkController( 2716): refreshSignalCluster: data=-1 bt=false
D/STATUSBAR-IconMerger( 2716): checkOverflow(336), More:false, Req:false Child:4

I/SktDrmDevice( 1974): network_regist : Status3;Idle0;CS0;PS0, radiostate : 10
I/SktDrmDevice( 1974): SKTDRM_IsServiceArea : 0
D/dalvikvm(19715): threadid=16: thread exiting, not yet detached (count=0)
V/GamesNativeSDK(19715): Detaching from JVM on thread main_dispatch
D/STATUSBAR-NetworkController( 2716): refreshSignalCluster - setNWBoosterIndicat
ors(false)
D/STATUSBAR-NetworkController( 2716): refreshSignalCluster: data=-1 bt=false
D/STATUSBAR-IconMerger( 2716): checkOverflow(336), More:false, Req:false Child:4

**Comment by simwodb1** [comment]
hi

**Comment by claywilkinson** [comment]
This message: `W/AchievementAgent( 3558): {"code":404,"errors":[{"message":"The requested appli
cation with ID 571707973781 was not found.","domain":"global","reason":"notFound
"}]}` is a little cryptic but points to a mismatch with the auth configuration on the console and the application.  

You'll want to double check the keystore  SHA1 fingerprint of the keystore you signed the app with and the one configured in the dev console.

It could also be the bundle ID, but that is hard to mess up since it is part of the resource data used when running Setup for the plugin.

Also, it could be that the player is not a tester for this game.

**Comment by shite** [comment]
Thanks for the help clay btw! But I was just wondering how you check the SHA1 on both the keystore and the dev console. Also, the bundle ID is the Application ID in the Dev Console? Thanks for the help.

**Comment by shite** [comment]
I checked the SHA1 and it seems to match. So that isn't the problem.

**Comment by hamzatt** [comment]
Were you ever able to solve the problem? I might be facing something similar.
