### ISSUE TITLE
Authentication Error. 

### ISSUE THREAD

**Issue by hikmatkhan** [playgameservices/play-games-plugin-for-unity#1256]
Hi,
I am getting this error. I don't from where it is getting this "608941808256" project ID. I also double checked my game is in apla testing mode and also linked with google play services.

06-25 06:31:25.734 9133-9212/? E/Volley: [49125] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/games/v1/players/me?language=en_GB
06-25 06:31:25.805 9133-26780/? E/SignInIntentService: Access Not Configured. Google Play Game Services API has not been used in project 608941808256 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/games/overview?project=608941808256 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
                                                       com.google.android.gms.games.server.error.GamesException
                                                           at com.google.android.gms.games.server.GamesServer.getResponseBlocking(GamesServer.java:174)
                                                           at com.google.android.gms.games.server.api.PlayersApi.getBlocking(PlayersApi.java:86)
                                                           at com.google.android.gms.games.broker.PlayerAgent.getPlayerFromNetwork(PlayerAgent.java:1638)
                                                           at com.google.android.gms.games.broker.PlayerAgent.fetchPlayer(PlayerAgent.java:633)
                                                           at com.google.android.gms.games.broker.DataBroker.loadSelf(DataBroker.java:1048)
                                                           at com.google.android.gms.games.service.PlayGamesSignInIntentService$LoadSelfOperation.executeInternal(PlayGamesSignInIntentService.java:294)
                                                           at com.google.android.gms.games.service.PlayGamesSignInIntentService$BaseOperation.execute(PlayGamesSignInIntentService.java:56)
                                                           at com.google.android.gms.games.service.PlayGamesSignInIntentService$OperationAdapter.execute(PlayGamesSignInIntentService.java:520)
                                                           at com.google.android.gms.chimera.BaseAsyncOperationService$OperationTask.run(BaseAsyncOperationService.java:177)
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                           at com.google.android.gms.common.util.concurrent.PriorityRunnable.run(PriorityRunnable.java:17)
                                                           at java.lang.Thread.run(Thread.java:818)

**Comment by croy-bkom** [comment]
How have you solved your problem, I have the exact same issue.

**Comment by claywilkinson** [comment]
Can you share a complete log?  Including the authentication call?
