### ISSUE TITLE
Failed to GetIdToken

### ISSUE THREAD

**Issue by sl0wth1nker** [playgameservices/play-games-plugin-for-unity#1312]
Hello i have some error when i called "PlayGamesPlatform.Instance.GetIdToken".

Unity version is 5.3.5f1.
My project use play-games-for-unity 0.9.34 and min target android is 4.1.
My android device version is  5.0.1.

08-06 14:28:52.174 14512-14883/? E/TokenFragment: Exception getting access token
                                                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/GoogleAuthUtil;
                                                      at com.google.games.bridge.TokenFragment$1.doInBackground(TokenFragment.java:240)
                                                      at com.google.games.bridge.TokenFragment$1.doInBackground(TokenFragment.java:211)
                                                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                      at java.lang.Thread.run(Thread.java:818)
                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.GoogleAuthUtil" on path: DexPathList[[zip file "/data/app/com.eglab.wordtagger-1/base.apk"],nativeLibraryDirectories=[/data/app/com.eglab.wordtagger-1/lib/arm, /vendor/lib, /system/lib]]
                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                      at com.google.games.bridge.TokenFragment$1.doInBackground(TokenFragment.java:240) 
                                                      at com.google.games.bridge.TokenFragment$1.doInBackground(TokenFragment.java:211) 
                                                      at android.os.AsyncTask$2.call(AsyncTask.java:288) 
                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                      at java.lang.Thread.run(Thread.java:818) 
                                                    Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.auth.GoogleAuthUtil
                                                      at java.lang.Class.classForName(Native Method)
                                                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                            ... 9 more
                                                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

Thank you for reading.

**Comment by claywilkinson** [comment]
This exception: `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/GoogleAuthUtil;` indicates that you are missing some client jar libraries such as play-services-basement-*.aar.

Also, beaware that GetIdToken is deprecated and you should instead use GetServerAuthCode and use that code on your backend server to exchange for an access token.

If all you need is a unique ID for the player, you can simply use player.id

**Comment by knivesout84** [comment]
Hi there,

Why has getIdToken been deprecated? Is there no other way to obtain the ID token through this plugin? I was hoping it would be the way to acquire an openID connect ID token in order to perform role-based authentication with amazon and access  HTTPS APIs directly from my game, without a back-end server. Is there any way to do this?

I've tried using the getserverauthcode path and I end up with an access token, not an ID token which is no good for me.

Cheers

**Comment by claywilkinson** [comment]
Version 0.9.37 of the plugin implements getting the auth code and id token correctly.  The access token is not available on Android.
