### ISSUE TITLE
com.google.android.gms.auth.GoogleAuthException: INVALID_AUDIENCE

### ISSUE THREAD

**Issue by MixMasterRickyC** [playgameservices/play-games-plugin-for-unity#1315]
Having an issue but it doesn't seem to happen on every device. On two devices it works fine and the Access Token is returned correctly. I then use this access token to log in, on the other two devices I get the same output via Logcat. 

All devices are running the same version of  Google Play Services V.9.4.52 and Google Play Games V.3.7.24. 

The devices that are failing are running Android 5.1 and 5.1.1 whilst the two which are successful are running Android 6.0.1 and 4.4.4.

I've tried searching for INVALID_AUDIENCE but it doesn't seem to be referenced on developers.google.com.

```
E/TokenFragment( 2524): Exception getting access token

E/TokenFragment( 2524): com.google.android.gms.auth.GoogleAuthException: INVALID_AUDIENCE

E/TokenFragment( 2524): 	at com.google.android.gms.auth.zzd$1.zzbr(Unknown Source)

E/TokenFragment( 2524): 	at com.google.android.gms.auth.zzd$1.zzbs(Unknown Source)

E/TokenFragment( 2524): 	at com.google.android.gms.auth.zzd.zza(Unknown Source)

E/TokenFragment( 2524): 	at com.google.android.gms.auth.zzd.zzc(Unknown Source)

E/TokenFragment( 2524): 	at com.google.android.gms.auth.zzd.getToken(Unknown Source)

E/TokenFragment( 2524): 	at com.google.android.gms.auth.zzd.getToken(Unknown Source)

E/TokenFragment( 2524): 	at com.google.android.gms.auth.zzd.getToken(Unknown Source)

E/TokenFragment( 2524): 	at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)

E/TokenFragment( 2524): 	at com.google.games.bridge.TokenFragment$1.doInBackground(TokenFragment.java:240)

E/TokenFragment( 2524): 	at com.google.games.bridge.TokenFragment$1.doInBackground(TokenFragment.java:211)

E/TokenFragment( 2524): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)

E/TokenFragment( 2524): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

E/TokenFragment( 2524): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)

E/TokenFragment( 2524): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

E/TokenFragment( 2524): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

E/TokenFragment( 2524): 	at java.lang.Thread.run(Thread.java:818)

D/TokenFragment( 2524): Done with tokenRequest status: 8
```

All the google play accounts are setup as testing accounts.

The only thing I can think of is that my Client ID doesn't have a '-' which meant updating the code for the "Google Play Games -> Setup -> Android setup..." so that the "Web Client App ID" would be accepted. Although the example given here (https://developers.google.com/games/services/console/enabling#client_id) doesn't either and the fact it works on some devices leads me to believe this isn't the issue.

Has anyone else had this issue?

**Comment by MixMasterRickyC** [comment]
Turns out, if you have "Enable Google Plus API Access" set to true it seems to work.

Although it doesn't explain why it worked on some devices, perhaps those devices already had the permissions enabled. 

Also the "INVALID_AUDIENCE" exception not being documented didn't help.
