### ISSUE TITLE
Runtime error: migrateExtraStreamToClipData() on a null object reference

### ISSUE THREAD

**Issue by JamesMcMahon** [playgameservices/play-games-plugin-for-unity#1368]
I'm seeing the follow error in my crash logs for some of my users,

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1494)
       at android.app.Activity.startActivityForResult(Activity.java:3848)
       at android.app.Activity.startActivityForResult(Activity.java:3802)
       at com.google.android.gms.common.internal.zzi$1.zztD(Unknown Source)
       at com.google.android.gms.common.internal.zzi.onClick(Unknown Source)
       at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:163)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5669)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

[This StackOverflow thread](https://stackoverflow.com/questions/38041230/intent-migrateextrastreamtoclipdata-on-a-null-object-reference) suggests that it may be an issue with the Google Play Services not being installed on the device. But I wanted to bring it up here to see if anyone else was seeing it or had a work around.

I also opened this other related question, [Checking if Google Play is supported at runtime?](https://github.com/playgameservices/play-games-plugin-for-unity/issues/1364).

**Comment by JamesMcMahon** [comment]
Might be related to https://github.com/google/gcm/issues/209.

**Comment by JamesMcMahon** [comment]
So if you upgrade the Google Play packages under **Window -> Google Play Games -> Downloads -> Google Play Games SDK (Android)** the plugin _should_ detect it's has new files and import them. That should upgrade the game to `9.4.0` or above.

**Comment by GrzegorzFeather** [comment]
Hi, I'm experiencing this exact same crash but with Google Maps, version 9.2.1

**Comment by JamesMcMahon** [comment]
@GrzegorzFeather Not sure what to do in the Google Maps situation if upgrading doesn't work.  You might want to to report an issue in the Google Maps repo.

You also might be able to adapt the work around at https://github.com/playgameservices/play-games-plugin-for-unity/issues/1346 to check for Google Maps support.

**Comment by Mohanben** [comment]
Why we need google play service for this Exception?

**Comment by SzotsLevente** [comment]
i'm experiencing the same issue on android 11, but only there

**Comment by dfg-1310** [comment]
try this in the base class

@Override    
public void startActivityForResult(Intent intent, int requestCode) {
    if (intent == null) {    
        intent = new Intent();        
    }       
    super.startActivityForResult(intent, requestCode);
}

Reference link: https://stackoverflow.com/questions/38041230/intent-migrateextrastreamtoclipdata-on-a-null-object-reference/46165052
