### ISSUE TITLE
Can't Save new file to cloud

### ISSUE THREAD

**Issue by SeanLangre** [playgameservices/play-games-plugin-for-unity#1394]
Our published version can still save new save files to cloud. On our working build we can't save to cloud if there isn't a previous file already there. This was possible before.

It might be something we did or it might be that we upgraded this plugin. Our users that already have a save won't have any problems but for new users this isn't viable.

Log (saving):

```
09-23  10:12:26.708  1421  4160 E Volley  : [135] BasicNetwork.performRequest: Unexpected response code 404 for https://www.googleapis.com/drive/v2internal/files/XXXXXXXXXXXXXXXXXXXXXXXXXX?prettyPrint=false&fields=owners(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),webContentLink,spaces,lastModifyingUser(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),originalFilename,headRevisionId,fileExtension,recencyReason,id,folderColorRgb,version,webViewLink,indexableText(text),editable,gplusMedia,quotaBytesUsed,properties(key,value,appId,visibility),writersCanShare,sharedWithMeDate,shared,explicitlyTrashed,authorizedAppIds,parents(isRoot,id),thumbnailLink,modifiedByMeDate,creatorAppId,labels(restricted,trashed,starred,viewed),appDataContents,md5Checksum,thumbnail(mimeType,image),localId(value,space,version),ownerNames,sharingUser(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),copyable,modifiedDate,userPermission(id,role,withLink,name,domain,additionalRoles,value,type,photoLink,emailAddress),etag,recency,createdDate,mimeType,alternateLink,lastViewedByMeDate,folderFeatures,title,description,fileSize,downloadUrl,embedLink,subscribed&acknowledgeAbuse=false&allProperties=true&fileScopeAppIds=XXXXXXXXXXXXXXX&updateViewedDate=false
 09-23  10:12:26.715  1421  2036 W NetworkResponseErrorDecoder: StatusCode:404 Reason:[notFound] Location:[file]
 09-23  10:12:26.778  1421  2036 E DriveAsyncService: Invalid parent folder.
 09-23  10:12:26.778  1421  2036 E DriveAsyncService: OperationException[Status{statusCode=Invalid parent folder., resolution=null}]
 09-23  10:12:26.778  1421  2036 E DriveAsyncService:   at kiq.j(:com.google.android.gms:760)
 09-23  10:12:26.778  1421  2036 E DriveAsyncService:   at kiq.a(:com.google.android.gms:555)
 09-23  10:12:26.778  1421  2036 E DriveAsyncService:   at kkf.a(:com.google.android.gms:65)
 09-23  10:12:26.778  1421  2036 E DriveAsyncService:   at kjn.a(:com.google.android.gms:1108)
 09-23  10:12:26.778  1421  2036 E DriveAsyncService:   at hno.run(:com.google.android.gms:191)
 09-23  10:12:26.778  1421  2036 E DriveAsyncService:   at jmg.run(:com.google.android.gms:450)
 09-23  10:12:26.778  1421  2036 E DriveAsyncService:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 09-23  10:12:26.778  1421  2036 E DriveAsyncService:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 09-23  10:12:26.778  1421  2036 E DriveAsyncService:   at jqr.run(:com.google.android.gms:17)
 09-23  10:12:26.778  1421  2036 E DriveAsyncService:   at java.lang.Thread.run(Thread.java:818)
 09-23  10:12:26.784  1421  7520 E SnapshotAgent: Folder could not be created: Status{statusCode=Invalid parent folder., resolution=null} 1502
 09-23  10:12:26.784  1421  7520 E SnapshotAgent: Could not find the games folder for game XXXXXXXXXXX
 09-23  10:12:26.784  1421  7520 W SnapshotAgent: Could not open snapshot folder for game XXXXXXXXXXX
```

Log (loading):

```
09-23  10:12:10.019  1421  2111 W NetworkResponseErrorDecoder: StatusCode:404 Reason:[notFound] Location:[file]
 09-23  10:12:10.247  1421  2111 E DriveAsyncService: Invalid parent folder.
 09-23  10:12:10.247  1421  2111 E DriveAsyncService: OperationException[Status{statusCode=Invalid parent folder., resolution=null}]
 09-23  10:12:10.247  1421  2111 E DriveAsyncService:   at kiq.j(:com.google.android.gms:760)
 09-23  10:12:10.247  1421  2111 E DriveAsyncService:   at kiq.a(:com.google.android.gms:555)
 09-23  10:12:10.247  1421  2111 E DriveAsyncService:   at kkf.a(:com.google.android.gms:65)
 09-23  10:12:10.247  1421  2111 E DriveAsyncService:   at kjn.a(:com.google.android.gms:1108)
 09-23  10:12:10.247  1421  2111 E DriveAsyncService:   at hno.run(:com.google.android.gms:191)
 09-23  10:12:10.247  1421  2111 E DriveAsyncService:   at jmg.run(:com.google.android.gms:450)
 09-23  10:12:10.247  1421  2111 E DriveAsyncService:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 09-23  10:12:10.247  1421  2111 E DriveAsyncService:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 09-23  10:12:10.247  1421  2111 E DriveAsyncService:   at jqr.run(:com.google.android.gms:17)
 09-23  10:12:10.247  1421  2111 E DriveAsyncService:   at java.lang.Thread.run(Thread.java:818)
 09-23  10:12:10.248  1421  7019 E SnapshotAgent: Folder could not be created: Status{statusCode=Invalid parent folder., resolution=null} 1502
 09-23  10:12:10.248  1421  7019 E SnapshotAgent: Could not find the games folder for game XXXXXXXXXXX
```

Full Log:

```
09-27 10:15:37.697 10022 10184 I GamesNativeSDK: Successfully connected to Google Play.
 09-27 10:15:37.728   781  4453 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:37.729   781   964 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:37.729   781   791 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:37.731   781  1738 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:37.769   781  1682 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:37.770   781 13703 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:37.836 10022 10053 I Unity   : GPG Login Success!
 09-27 10:15:37.836 10022 10053 I Unity   :  
 09-27 10:15:37.836 10022 10053 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
 09-27 10:15:37.836 10022 10053 I Unity   : 
 09-27 10:15:38.355  1421  4159 E Volley  : [134] BasicNetwork.performRequest: Unexpected response code 404 for https://www.googleapis.com/drive/v2internal/files/13IHv9kCIMac7JzkXRnKlLQZuOcUY?prettyPrint=false&fields=owners(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),webContentLink,spaces,lastModifyingUser(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),originalFilename,headRevisionId,fileExtension,recencyReason,id,folderColorRgb,version,webViewLink,indexableText(text),editable,gplusMedia,quotaBytesUsed,properties(key,value,appId,visibility),writersCanShare,sharedWithMeDate,shared,explicitlyTrashed,authorizedAppIds,parents(isRoot,id),thumbnailLink,modifiedByMeDate,creatorAppId,labels(restricted,trashed,starred,viewed),appDataContents,md5Checksum,thumbnail(mimeType,image),localId(value,space,version),ownerNames,sharingUser(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),copyable,modifiedDate,userPermission(id,role,withLink,name,domain,additionalRoles,value,type,photoLink,emailAddress),etag,recency,createdDate,mimeType,alternateLink,lastViewedByMeDate,folderFeatures,title,description,fileSize,downloadUrl,embedLink,subscribed&acknowledgeAbuse=false&allProperties=true&fileScopeAppIds=XXXXXXXXXXX&updateViewedDate=false
 09-27 10:15:38.363  1421 30602 W NetworkResponseErrorDecoder: StatusCode:404 Reason:[notFound] Location:[file]
 09-27 10:15:38.483  1421 30602 E DriveAsyncService: Invalid parent folder.
 09-27 10:15:38.483  1421 30602 E DriveAsyncService: OperationException[Status{statusCode=Invalid parent folder., resolution=null}]
 09-27 10:15:38.483  1421 30602 E DriveAsyncService:    at kiq.j(:com.google.android.gms:760)
 09-27 10:15:38.483  1421 30602 E DriveAsyncService:    at kiq.a(:com.google.android.gms:555)
 09-27 10:15:38.483  1421 30602 E DriveAsyncService:    at kkf.a(:com.google.android.gms:65)
 09-27 10:15:38.483  1421 30602 E DriveAsyncService:    at kjn.a(:com.google.android.gms:1108)
 09-27 10:15:38.483  1421 30602 E DriveAsyncService:    at hno.run(:com.google.android.gms:191)
 09-27 10:15:38.483  1421 30602 E DriveAsyncService:    at jmg.run(:com.google.android.gms:450)
 09-27 10:15:38.483  1421 30602 E DriveAsyncService:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 09-27 10:15:38.483  1421 30602 E DriveAsyncService:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 09-27 10:15:38.483  1421 30602 E DriveAsyncService:    at jqr.run(:com.google.android.gms:17)
 09-27 10:15:38.483  1421 30602 E DriveAsyncService:    at java.lang.Thread.run(Thread.java:818)
 09-27 10:15:38.489  1421 10194 E SnapshotAgent: Folder could not be created: Status{statusCode=Invalid parent folder., resolution=null} 1502
 09-27 10:15:38.489  1421 10194 E SnapshotAgent: Could not find the games folder for game XXXXXXXXXXX
 09-27 10:15:38.495   781  1436 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:38.495   781  4453 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:39.967   781   887 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 137]
 09-27 10:15:41.431  1421  4160 E Volley  : [135] BasicNetwork.performRequest: Unexpected response code 404 for https://www.googleapis.com/drive/v2internal/files/13IHv9kCIMac7JzkXRnKlLQZuOcUY?prettyPrint=false&fields=owners(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),webContentLink,spaces,lastModifyingUser(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),originalFilename,headRevisionId,fileExtension,recencyReason,id,folderColorRgb,version,webViewLink,indexableText(text),editable,gplusMedia,quotaBytesUsed,properties(key,value,appId,visibility),writersCanShare,sharedWithMeDate,shared,explicitlyTrashed,authorizedAppIds,parents(isRoot,id),thumbnailLink,modifiedByMeDate,creatorAppId,labels(restricted,trashed,starred,viewed),appDataContents,md5Checksum,thumbnail(mimeType,image),localId(value,space,version),ownerNames,sharingUser(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),copyable,modifiedDate,userPermission(id,role,withLink,name,domain,additionalRoles,value,type,photoLink,emailAddress),etag,recency,createdDate,mimeType,alternateLink,lastViewedByMeDate,folderFeatures,title,description,fileSize,downloadUrl,embedLink,subscribed&acknowledgeAbuse=false&allProperties=true&fileScopeAppIds=XXXXXXXXXXX&updateViewedDate=false
 09-27 10:15:41.433  1421 27474 W NetworkResponseErrorDecoder: StatusCode:404 Reason:[notFound] Location:[file]
 09-27 10:15:41.487  1421 27474 E DriveAsyncService: Invalid parent folder.
 09-27 10:15:41.487  1421 27474 E DriveAsyncService: OperationException[Status{statusCode=Invalid parent folder., resolution=null}]
 09-27 10:15:41.487  1421 27474 E DriveAsyncService:    at kiq.j(:com.google.android.gms:760)
 09-27 10:15:41.487  1421 27474 E DriveAsyncService:    at kiq.a(:com.google.android.gms:555)
 09-27 10:15:41.487  1421 27474 E DriveAsyncService:    at kkf.a(:com.google.android.gms:65)
 09-27 10:15:41.487  1421 27474 E DriveAsyncService:    at kjn.a(:com.google.android.gms:1108)
 09-27 10:15:41.487  1421 27474 E DriveAsyncService:    at hno.run(:com.google.android.gms:191)
 09-27 10:15:41.487  1421 27474 E DriveAsyncService:    at jmg.run(:com.google.android.gms:450)
 09-27 10:15:41.487  1421 27474 E DriveAsyncService:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 09-27 10:15:41.487  1421 27474 E DriveAsyncService:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 09-27 10:15:41.487  1421 27474 E DriveAsyncService:    at jqr.run(:com.google.android.gms:17)
 09-27 10:15:41.487  1421 27474 E DriveAsyncService:    at java.lang.Thread.run(Thread.java:818)
 09-27 10:15:41.495  1421 10243 E SnapshotAgent: Folder could not be created: Status{statusCode=Invalid parent folder., resolution=null} 1502
 09-27 10:15:41.495  1421 10243 E SnapshotAgent: Could not find the games folder for game XXXXXXXXXXX
 09-27 10:15:41.495  1421 10243 W SnapshotAgent: Could not open snapshot folder for game XXXXXXXXXXX
 09-27 10:15:41.495   781  1682 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:41.495   781  3777 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:42.142  1421  4163 E Volley  : [137] BasicNetwork.performRequest: Unexpected response code 404 for https://www.googleapis.com/drive/v2internal/files/13IHv9kCIMac7JzkXRnKlLQZuOcUY?prettyPrint=false&fields=owners(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),webContentLink,spaces,lastModifyingUser(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),originalFilename,headRevisionId,fileExtension,recencyReason,id,folderColorRgb,version,webViewLink,indexableText(text),editable,gplusMedia,quotaBytesUsed,properties(key,value,appId,visibility),writersCanShare,sharedWithMeDate,shared,explicitlyTrashed,authorizedAppIds,parents(isRoot,id),thumbnailLink,modifiedByMeDate,creatorAppId,labels(restricted,trashed,starred,viewed),appDataContents,md5Checksum,thumbnail(mimeType,image),localId(value,space,version),ownerNames,sharingUser(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),copyable,modifiedDate,userPermission(id,role,withLink,name,domain,additionalRoles,value,type,photoLink,emailAddress),etag,recency,createdDate,mimeType,alternateLink,lastViewedByMeDate,folderFeatures,title,description,fileSize,downloadUrl,embedLink,subscribed&acknowledgeAbuse=false&allProperties=true&fileScopeAppIds=XXXXXXXXXXX&updateViewedDate=false
 09-27 10:15:42.142  1421 27474 W NetworkResponseErrorDecoder: StatusCode:404 Reason:[notFound] Location:[file]
 09-27 10:15:42.189  1421 27474 E DriveAsyncService: Invalid parent folder.
 09-27 10:15:42.189  1421 27474 E DriveAsyncService: OperationException[Status{statusCode=Invalid parent folder., resolution=null}]
 09-27 10:15:42.189  1421 27474 E DriveAsyncService:    at kiq.j(:com.google.android.gms:760)
 09-27 10:15:42.189  1421 27474 E DriveAsyncService:    at kiq.a(:com.google.android.gms:555)
 09-27 10:15:42.189  1421 27474 E DriveAsyncService:    at kkf.a(:com.google.android.gms:65)
 09-27 10:15:42.189  1421 27474 E DriveAsyncService:    at kjn.a(:com.google.android.gms:1108)
 09-27 10:15:42.189  1421 27474 E DriveAsyncService:    at hno.run(:com.google.android.gms:191)
 09-27 10:15:42.189  1421 27474 E DriveAsyncService:    at jmg.run(:com.google.android.gms:450)
 09-27 10:15:42.189  1421 27474 E DriveAsyncService:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 09-27 10:15:42.189  1421 27474 E DriveAsyncService:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 09-27 10:15:42.189  1421 27474 E DriveAsyncService:    at jqr.run(:com.google.android.gms:17)
 09-27 10:15:42.189  1421 27474 E DriveAsyncService:    at java.lang.Thread.run(Thread.java:818)
 09-27 10:15:42.192  1421 10243 E SnapshotAgent: Folder could not be created: Status{statusCode=Invalid parent folder., resolution=null} 1502
 09-27 10:15:42.192  1421 10243 E SnapshotAgent: Could not find the games folder for game XXXXXXXXXXX
 09-27 10:15:42.192  1421 10243 W SnapshotAgent: Could not open snapshot folder for game XXXXXXXXXXX
 09-27 10:15:42.193   781  1738 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:42.194   781 13627 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:42.194 10022 10022 V GamesNativeSDK: Encountered GmsCore error with status code: 4005
 09-27 10:15:42.277 10022 10196 W Unity   : *** [Play Games Plugin DLL] 09/27/16 10:15:42 +02:00 ERROR: Encountered unknown status: ERROR_INTERNAL
 09-27 10:15:42.277 10022 10196 W Unity   :  
 09-27 10:15:42.277 10022 10196 W Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
 09-27 10:15:42.277 10022 10196 W Unity   : 
 09-27 10:15:42.307 10022 10053 I Unity   : Error opening game: InternalError
 09-27 10:15:42.307 10022 10053 I Unity   :  
 09-27 10:15:42.307 10022 10053 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
 09-27 10:15:42.307 10022 10053 I Unity   : 
 09-27 10:15:42.989   781   887 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 137]
 09-27 10:15:44.139 10022 10053 I Unity   : Loading game progress from the cloud.
 09-27 10:15:44.139 10022 10053 I Unity   :  
 09-27 10:15:44.139 10022 10053 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
 09-27 10:15:44.139 10022 10053 I Unity   : 
 09-27 10:15:44.701  1421  4162 E Volley  : [136] BasicNetwork.performRequest: Unexpected response code 404 for https://www.googleapis.com/drive/v2internal/files/13IHv9kCIMac7JzkXRnKlLQZuOcUY?prettyPrint=false&fields=owners(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),webContentLink,spaces,lastModifyingUser(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),originalFilename,headRevisionId,fileExtension,recencyReason,id,folderColorRgb,version,webViewLink,indexableText(text),editable,gplusMedia,quotaBytesUsed,properties(key,value,appId,visibility),writersCanShare,sharedWithMeDate,shared,explicitlyTrashed,authorizedAppIds,parents(isRoot,id),thumbnailLink,modifiedByMeDate,creatorAppId,labels(restricted,trashed,starred,viewed),appDataContents,md5Checksum,thumbnail(mimeType,image),localId(value,space,version),ownerNames,sharingUser(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),copyable,modifiedDate,userPermission(id,role,withLink,name,domain,additionalRoles,value,type,photoLink,emailAddress),etag,recency,createdDate,mimeType,alternateLink,lastViewedByMeDate,folderFeatures,title,description,fileSize,downloadUrl,embedLink,subscribed&acknowledgeAbuse=false&allProperties=true&fileScopeAppIds=XXXXXXXXXXX&updateViewedDate=false
 09-27 10:15:44.703  1421 27474 W NetworkResponseErrorDecoder: StatusCode:404 Reason:[notFound] Location:[file]
 09-27 10:15:44.757  1421 27474 E DriveAsyncService: Invalid parent folder.
 09-27 10:15:44.757  1421 27474 E DriveAsyncService: OperationException[Status{statusCode=Invalid parent folder., resolution=null}]
 09-27 10:15:44.757  1421 27474 E DriveAsyncService:    at kiq.j(:com.google.android.gms:760)
 09-27 10:15:44.757  1421 27474 E DriveAsyncService:    at kiq.a(:com.google.android.gms:555)
 09-27 10:15:44.757  1421 27474 E DriveAsyncService:    at kkf.a(:com.google.android.gms:65)
 09-27 10:15:44.757  1421 27474 E DriveAsyncService:    at kjn.a(:com.google.android.gms:1108)
 09-27 10:15:44.757  1421 27474 E DriveAsyncService:    at hno.run(:com.google.android.gms:191)
 09-27 10:15:44.757  1421 27474 E DriveAsyncService:    at jmg.run(:com.google.android.gms:450)
 09-27 10:15:44.757  1421 27474 E DriveAsyncService:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 09-27 10:15:44.757  1421 27474 E DriveAsyncService:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 09-27 10:15:44.757  1421 27474 E DriveAsyncService:    at jqr.run(:com.google.android.gms:17)
 09-27 10:15:44.757  1421 27474 E DriveAsyncService:    at java.lang.Thread.run(Thread.java:818)
 09-27 10:15:44.757  1421 10290 E SnapshotAgent: Folder could not be created: Status{statusCode=Invalid parent folder., resolution=null} 1502
 09-27 10:15:44.757  1421 10290 E SnapshotAgent: Could not find the games folder for game XXXXXXXXXXX
 09-27 10:15:44.757  1421 10290 W SnapshotAgent: Could not open snapshot folder for game XXXXXXXXXXX
 09-27 10:15:44.758   781   948 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:44.758   781  1738 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:45.174  1421  4159 E Volley  : [134] BasicNetwork.performRequest: Unexpected response code 404 for https://www.googleapis.com/drive/v2internal/files/13IHv9kCIMac7JzkXRnKlLQZuOcUY?prettyPrint=false&fields=owners(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),webContentLink,spaces,lastModifyingUser(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),originalFilename,headRevisionId,fileExtension,recencyReason,id,folderColorRgb,version,webViewLink,indexableText(text),editable,gplusMedia,quotaBytesUsed,properties(key,value,appId,visibility),writersCanShare,sharedWithMeDate,shared,explicitlyTrashed,authorizedAppIds,parents(isRoot,id),thumbnailLink,modifiedByMeDate,creatorAppId,labels(restricted,trashed,starred,viewed),appDataContents,md5Checksum,thumbnail(mimeType,image),localId(value,space,version),ownerNames,sharingUser(isAuthenticatedUser,picture(url),displayName,permissionId,emailAddress),copyable,modifiedDate,userPermission(id,role,withLink,name,domain,additionalRoles,value,type,photoLink,emailAddress),etag,recency,createdDate,mimeType,alternateLink,lastViewedByMeDate,folderFeatures,title,description,fileSize,downloadUrl,embedLink,subscribed&acknowledgeAbuse=false&allProperties=true&fileScopeAppIds=XXXXXXXXXXX&updateViewedDate=false
 09-27 10:15:45.176  1421 27474 W NetworkResponseErrorDecoder: StatusCode:404 Reason:[notFound] Location:[file]
 09-27 10:15:45.225  1421 27474 E DriveAsyncService: Invalid parent folder.
 09-27 10:15:45.225  1421 27474 E DriveAsyncService: OperationException[Status{statusCode=Invalid parent folder., resolution=null}]
 09-27 10:15:45.225  1421 27474 E DriveAsyncService:    at kiq.j(:com.google.android.gms:760)
 09-27 10:15:45.225  1421 27474 E DriveAsyncService:    at kiq.a(:com.google.android.gms:555)
 09-27 10:15:45.225  1421 27474 E DriveAsyncService:    at kkf.a(:com.google.android.gms:65)
 09-27 10:15:45.225  1421 27474 E DriveAsyncService:    at kjn.a(:com.google.android.gms:1108)
 09-27 10:15:45.225  1421 27474 E DriveAsyncService:    at hno.run(:com.google.android.gms:191)
 09-27 10:15:45.225  1421 27474 E DriveAsyncService:    at jmg.run(:com.google.android.gms:450)
 09-27 10:15:45.225  1421 27474 E DriveAsyncService:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 09-27 10:15:45.225  1421 27474 E DriveAsyncService:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 09-27 10:15:45.225  1421 27474 E DriveAsyncService:    at jqr.run(:com.google.android.gms:17)
 09-27 10:15:45.225  1421 27474 E DriveAsyncService:    at java.lang.Thread.run(Thread.java:818)
 09-27 10:15:45.230  1421 10290 E SnapshotAgent: Folder could not be created: Status{statusCode=Invalid parent folder., resolution=null} 1502
 09-27 10:15:45.230  1421 10290 E SnapshotAgent: Could not find the games folder for game XXXXXXXXXXX
 09-27 10:15:45.230  1421 10290 W SnapshotAgent: Could not open snapshot folder for game XXXXXXXXXXX
 09-27 10:15:45.230   781  1738 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:45.231   781  1682 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10391 but it is really 10061
 09-27 10:15:45.231 10022 10022 V GamesNativeSDK: Encountered GmsCore error with status code: 4005
 09-27 10:15:45.232 10022 10196 W Unity   : *** [Play Games Plugin DLL] 09/27/16 10:15:45 +02:00 ERROR: Encountered unknown status: ERROR_INTERNAL
 09-27 10:15:45.232 10022 10196 W Unity   :  
 09-27 10:15:45.232 10022 10196 W Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
 09-27 10:15:45.232 10022 10196 W Unity   : 
 09-27 10:15:45.254 10022 10053 I Unity   : Error opening game: InternalError
 09-27 10:15:45.254 10022 10053 I Unity   :  
 09-27 10:15:45.254 10022 10053 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
 09-27 10:15:45.254 10022 10053 I Unity   : 
 09-27 10:15:46.009   781   887 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 137]
```

**Comment by claywilkinson** [comment]
Can you share more of the log ideally including the authentication call to the load or save call?

**Comment by SeanLangre** [comment]
Wasn't sure what you wanted so pasted a full log from the point where we get confirmation that we are logged in to Google Play Services (edited original post).

Order:
* Initialized Google Play services and logged in
* Tried to save
* Tried to load

**Comment by SeanLangre** [comment]
It's
```
((PlayGamesPlatform)Social.Active).SavedGame.OpenWithAutomaticConflictResolution(m_saveName,
                DataSource.ReadNetworkOnly,  //ReadCacheOrNetwork returns error aswell
                ConflictResolutionStrategy.UseLongestPlaytime,
                SavedGameOpened);
```
that returns error in callback when opening a game that doesn't already exist. Probably same issue as many other have here. It's odd that it works on published build.

**Comment by SeanLangre** [comment]
Solved it by removing everything with Google Play Services from the build and then downloading version from Jul 27, 2016. 

Issue is still there but I guess we can close this.
