### ISSUE TITLE
CommandInvokationFailure: Unable to convert classes into dex format

### ISSUE THREAD

**Issue by alternativerichie** [playgameservices/play-games-plugin-for-unity#1417]
I'm tired of this plugin.  Had to get the latest because of an error that has just started to occur on initialise for google play services for some reason, I haven't changed anything.  Removed GooglePlayGames, PlayServicesResolver (which doesn't seem to work very well), and removed the plugins from the plugins folder.  Imported the latest package.  Now when I go to do a build, as I expected to happen with this, I get the error Build failure, Unable to convert classes into dex format.

"Now, how did I fix it last time?" I have to say to myself, here we go, waste my time on this again.

CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/Richie/Library/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity5_3_4_p3/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzde;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzdf;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzdg;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzdh;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzdj;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzdk;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzdl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzdq;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzdr;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
	... 9 more
]
stdout[

**Comment by alternativerichie** [comment]
My plugins look like this now :- 

<img width="195" alt="screen shot 2016-10-07 at 15 41 32" src="https://cloud.githubusercontent.com/assets/19594037/19194139/a673dfce-8ca4-11e6-8d8d-3defd3dd1f46.png">

**Comment by alternativerichie** [comment]
Thought I might need to update the Google Ads Mobile plugin, so I did.  Now I get this error:-

Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs(113,47): error CS1501: No overload for method `DoResolution' takes `3' arguments

**Comment by alternativerichie** [comment]
I re-imported google play games plugin and that has got rid of the error Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs(113,47): error CS1501: No overload for method DoResolution' takes3' arguments.

And now I'm back to the original Unable to convert classes into sex format error, so updating google ads plugin didn't work.

**Comment by alternativerichie** [comment]
If anyone has a step by step for this I sure would be grateful.  I just want google ads plugin with this plugin to build without the error.

**Comment by alternativerichie** [comment]
I returned to the older plugin and that is working now.  Still, it's bad that everytime I come to upgrade this plugin I get errors.
