### ISSUE TITLE
Open save game callback not called

### ISSUE THREAD

**Issue by kkondarev** [playgameservices/play-games-plugin-for-unity#1450]
Hi, I figured out, that if actual conflict resolving is involved, the callback for game being opened is not called at all. Scenario: 
Turn device online -> start the game -> authentication successful -> save game is created -> some gameplay -> game is saved successfully -> exit game -> 
Turn device offline -> start the game -> save game loaded successfully -> some gameplay -> game is saved successfully -> exit game -> 
Turn device online -> start game -> save game attempts to load -> callback is not called at all, so game hangs

Narrowed it down to following:
1. The game always starts successfully when the device is offline, the save game is also opened, all good
2. When the device is online, game loading is stuck on:
 ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame; savedGameClient.OpenWithAutomaticConflictResolution(saveName, DataSource.ReadCacheOrNetwork, ConflictResolutionStrategy.UseLongestPlaytime, onSavedGameOpened); 
-> No exceptions, no nothing
-> onSavedGameOpened callback is not called at all
-> If another app receives focus for a sec and then I switch back to the game - the callback is called and the save game is opened
-> if the game is restarted with device offline, the callback is called and the save is opened every time

Any comments or suggestions what to do/check/try?

**Comment by kkondarev** [comment]
Some more info: looking at the logs, I found the following:

`
10-26 22:38:48.854: W/GamesServiceBroker(6870): Client connected with SDK 8487000, Services 9877036, and Games 37240036
10-26 22:38:48.914: E/SnapshotEventService(6870): Error handling event: CompletionEvent [id=DriveId:CAESSDFfdWxkT2hXZ2o4bjFMQmpEeWwtMWlzWnlSNk9zQnY4OGRZWHRVNGtpMFVOb3dsaUlFR2VaSWJtb0xBbzBVOUwtMzVxeDJmaxjEBSCKyuvRxVEoAA==, status=2, trackingTag='info.dragonslabs.submarine<:>drive://g15862525828023294684/104358369895/DefaultGame<:>104358369895<:>6<:>https://www.googleapis.com/auth/games_lite<:>com.google']
10-26 22:38:48.914: E/SnapshotEventService(6870): java.lang.IllegalStateException: Attempting to underflow ref count for drive://g15862525828023294684/104358369895/DefaultGame
10-26 22:38:48.914: E/SnapshotEventService(6870): 	at com.google.android.gms.common.internal.Asserts.fail(Asserts.java:135)
10-26 22:38:48.914: E/SnapshotEventService(6870): 	at com.google.android.gms.games.broker.SnapshotAgent.decrementPendingChangeCount(SnapshotAgent.java:874)
10-26 22:38:48.914: E/SnapshotEventService(6870): 	at com.google.android.gms.games.service.PlaySnapshotEventService.onCompletionInner(PlaySnapshotEventService.java:107)
10-26 22:38:48.914: E/SnapshotEventService(6870): 	at com.google.android.gms.games.service.PlaySnapshotEventService.onCompletion(PlaySnapshotEventService.java:58)
10-26 22:38:48.914: E/SnapshotEventService(6870): 	at com.google.android.gms.chimera.DriveEventService.access$000(DriveEventService.java:70)
10-26 22:38:48.914: E/SnapshotEventService(6870): 	at com.google.android.gms.chimera.DriveEventService$EventHandler.handleMessage(DriveEventService.java:132)
10-26 22:38:48.914: E/SnapshotEventService(6870): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-26 22:38:48.914: E/SnapshotEventService(6870): 	at android.os.Looper.loop(Looper.java:176)
10-26 22:38:48.914: E/SnapshotEventService(6870): 	at com.google.android.gms.chimera.DriveEventService$1.run(DriveEventService.java:223)
`

Some help to decipher what it means, please?

**Comment by kkondarev** [comment]
Hey guys, any update on this one?

**Comment by claywilkinson** [comment]
I've passed it along to the SDK team.  Can you share the versions of the play-services libraries used and the complete log of authenticating and this error?

**Comment by gladieweb** [comment]
I have the same issue any suggestions?

**Comment by smile616** [comment]
@gladieweb, do you see `java.lang.IllegalStateException: Attempting to underflow ref count` in the logcat?

**Comment by gladieweb** [comment]
no I dont see that

**Comment by smile616** [comment]
@gladieweb, please open a new ticket with details about your case and include:
* version of the plugin
* step to reproduce the issue
* logcat logs around time of the issue
Anything else you think is important.

Thanks!
