### ISSUE TITLE
Unable to convert classes into dex format

### ISSUE THREAD

**Issue by zory** [playgameservices/play-games-plugin-for-unity#1517]
Hello.
I am having difficulty with placing google play services in one of my games. While building to Android I am getting "**Convert classes into dex format**" error.
I know it is mostly caused because of duplicating jar's, however I can't find duplicates anywhere.

My guess was "support-annotations-24.0.0" and "support-v4.24.0.0" (which came from google play) clashing with "support-v4-23.4.0" (which came from facebook, but it wasn't it.

I'm using official **facebook** android/iOS plugin and bunch of other self written plugins, but just one of them is using something related with play-services.

Maybe someone had same problem with these exact plugins or maybe I have missed something in exception code that could be of help for me?

Also, I tried finding/deleting some *.jar's from other threads like GooglePlay vs GoogleAnalytics compatibility suggested, but without success for now.

```
CommandInvokationFailure: Unable to convert classes into dex format.
C:/Program Files/Java/jdk1.8.0_77\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Program Files (x86)/Android/android-sdk\tools" -Dfile.encoding=UTF8 -jar "E:\Programs\Unity 5.5.0p1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/ItemListIntents;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/NoteIntents;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/ReserveIntents;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/actions/SearchIntents;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/ads/identifier/AdvertisingIdClient;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/ads/identifier/AdvertisingIdClient$Info;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/ads/identifier/AdvertisingIdClient$zza;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/AccountChangeEvent;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/AccountChangeEventsRequest;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
	... 9 more
]
stdout[
processing archive C:\Projects\MonsterBuster\Monster_Buster_project\Temp\StagingArea\android-libraries\MainLibProj\libs\.\play-games-plugin-support.jar...
```

**Comment by alexhofer** [comment]
I had the same issue last night, when you deleted "support-v4.24.0.0" from the project did you re-load Unity before attempting to rebuild? Unity doesn't unload DLLs until you close the program, they stay in memory.

**Comment by zory** [comment]
Thanks, I have tried it, but result was same.

I have ended up by deleting "google-play-services.jar" entirely. It seems some other plugin includes it (or at least part of its classes), but haven't found that jar, maybe it somewhere packed inside of some *.aar

After deleting so far so good everything works (at least Log-In and LeaderboardsUI, haven't tested other things yet).
