### ISSUE TITLE
Android - Bad call: specified package com.google.android.play.games under uid

### ISSUE THREAD

**Issue by gasior** [playgameservices/play-games-plugin-for-unity#1698]
Unity 5.5.2.f1, play games 0.9.37.

On our game, when user kills enemy, we report kill as incremental achievement like this:

```
GooglePlayGames.PlayGamesPlatform.Instance.IncrementAchievement(GetAchievementId(achievement), value, (bool success) =>
            {
                if (!success)
                {
                    OnAchievementReportFailure(achievement, value);
                }
            });
```
On one kill we can see several of these in logcat:

```
04-13 10:17:41.104  3723  4206 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10342 but it is really 10194
04-13 10:17:41.104  3723  4206 W AppOps  : java.lang.RuntimeException: here
04-13 10:17:41.104  3723  4206 W AppOps  : 	at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1356)
04-13 10:17:41.104  3723  4206 W AppOps  : 	at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1035)
04-13 10:17:41.104  3723  4206 W AppOps  : 	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
04-13 10:17:41.104  3723  4206 W AppOps  : 	at android.os.Binder.execTransact(Binder.java:573)
```

Before 5.5.2f1 we were using 5.3. 
I can remember "AppsOps: Bad" call messages there also, but without exception.
What's going on?

**Comment by Honikou** [comment]
same issue for us

**Comment by claywilkinson** [comment]
The Bad call message is annoying, but harmless log spam, as well as the RuntimeException: here message.

**Comment by shi-yh** [comment]
hello,had you sloved it? i have the same issue
