### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by dgiunchi** [playgameservices/play-games-plugin-for-unity#1723]
I have Unity 5.6, just test on Minimal example (used GPS unity plugin 0.9.37), create in google play console a test application.
I followed the instructions for setting up, update the sdk manager, sign the app, ... everything that can be found in the net basically.
When I simply try to click setup button in the Windows->Google Play Services ->Setup->Setup Android,
it gives me "invalid classname : An exception was thrown by a target of an invocation".

**Comment by blumersolutions** [comment]
Same here. Even more, it worked at some point with no changes on my side either. I wonder if there's something wrong with the Google services..?

**Comment by pradeepkulasekaran** [comment]
Can you give the log of the issue... I faced similar problem and i fixed using one of the thread..
#1721

**Comment by dgiunchi** [comment]
Sure, thanks!
There are two warnings
---------------------------------------------------------------------------------------------------------------
NULL package!!
UnityEngine.Debug:Log(Object)
GooglePlayGames.Editor.GPGSAndroidSetupUI:CheckBundleId() (at Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs:386)
GooglePlayGames.Editor.GPGSAndroidSetupUI:PerformSetup(String, String, String, String, String) (at Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs:103)
GooglePlayGames.Editor.GPGSAndroidSetupUI:DoSetup() (at Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs:311)
GooglePlayGames.Editor.GPGSAndroidSetupUI:OnGUI() (at Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs:283)
UnityEditor.HostView:OnGUI()

d by:
   at System.Environment.get_StackTrace() in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Environment.cs:line 227
   at Google.JarResolver.Dependency..ctor(System.String group, System.String artifact, System.String version, System.String[] packageIds, System.String[] repositories)
   at Google.JarResolver.PlayServicesSupport.GetDependencies(Google.JarResolver.Dependency dep, System.Collections.Generic.List`1 repoPaths)
   at Google.JarResolver.PlayServicesSupport.GetCurrentDependencies(System.Collections.Generic.Dictionary`2 dependencies, System.String destDirectory, Google.JarResolver.ExplodeAar explodeAar, System.Collections.Generic.List`1 repoPaths)
   at Google.JarResolver.PlayServicesSupport.DependenciesPresent(System.String destDirectory, Google.JarResolver.ExplodeAar explodeAar)
   at GooglePlayServices.ResolverVer1_1.DoResolution(Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation, System.Action resolutionComplete)
   at GooglePlayServices.PlayServicesResolver.Resolve(System.Action resolutionComplete)
   at GooglePlayServices.PlayServicesResolver.MenuResolve()
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:line 222
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:line 115
   at Google.VersionHandler.InvokeMethod(System.Type type, System.Object objectInstance, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2 namedArgs)
   at Google.VersionHandler.InvokeStaticMethod(System.Type type, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2 namedArgs)
   at GooglePlayGames.Editor.GPGSAndroidSetupUI.PerformSetup(System.String clientId, System.String classDirectory, System.String className, System.String resourceXmlData, System.String nearbySvcId) in C:\Users\dannox\Downloads\play-games-plugin-for-unity-master\play-games-plugin-for-unity-master\samples\Minimal\Source\Assets\GooglePlayGames\Editor\GPGSAndroidSetupUI.cs:line 113
   at GooglePlayGames.Editor.GPGSAndroidSetupUI.DoSetup() in C:\Users\dannox\Downloads\play-games-plugin-for-unity-master\play-games-plugin-for-unity-master\samples\Minimal\Source\Assets\GooglePlayGames\Editor\GPGSAndroidSetupUI.cs:line 311
   at GooglePlayGames.Editor.GPGSAndroidSetupUI.OnGUI() in C:\Users\dannox\Downloads\play-games-plugin-for-unity-master\play-games-plugin-for-unity-master\samples\Minimal\Source\Assets\GooglePlayGames\Editor\GPGSAndroidSetupUI.cs:line 283
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:line 222
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:line 115
   at UnityEditor.HostView.Invoke(System.String methodName, System.Object obj) in C:\buildslave\unity\build\Editor\Mono\HostView.cs:line 262
   at UnityEditor.HostView.Invoke(System.String methodName) in C:\buildslave\unity\build\Editor\Mono\HostView.cs:line 255
   at UnityEditor.HostView.OnGUI() in C:\buildslave\unity\build\Editor\Mono\HostView.cs:line 84

---------------------------------------------------------------------------------------------------------------
UnityEngine.Debug:Log(Object)
Google.JarResolver.PlayServicesSupport:Log(String, Boolean)
Google.JarResolver.PlayServicesSupport:FindCandidate(Dependency, List`1)
Google.JarResolver.PlayServicesSupport:GetDependencies(Dependency, List`1)
Google.JarResolver.PlayServicesSupport:GetCurrentDependencies(Dictionary`2, String, ExplodeAar, List`1)
Google.JarResolver.PlayServicesSupport:DependenciesPresent(String, ExplodeAar)
GooglePlayServices.ResolverVer1_1:DoResolution(PlayServicesSupport, String, OverwriteConfirmation, Action)
GooglePlayServices.PlayServicesResolver:Resolve(Action)
GooglePlayServices.PlayServicesResolver:MenuResolve()
System.Reflection.MethodBase:Invoke(Object, Object[])
Google.VersionHandler:InvokeMethod(Type, Object, String, Object[], Dictionary`2)
Google.VersionHandler:InvokeStaticMethod(Type, String, Object[], Dictionary`2)
GooglePlayGames.Editor.GPGSAndroidSetupUI:PerformSetup(String, String, String, String, String) (at Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs:113)
GooglePlayGames.Editor.GPGSAndroidSetupUI:DoSetup() (at Assets/GooglePlayGames/Editor/GPGSAndroidSetupUI.cs:311)

**Comment by rjeike** [comment]
Go to Build Settings and make sure Android platform is selected.

**Comment by pradeepkulasekaran** [comment]
Hi, 

To resolve the issues and to prevent issues from future releases please follow the steps.

**For Android SDK**

The plugin's required SDK and Android SDK were in mismatch at some point when the plugin/SDK got updated.
To remove the conflict Uninstall the android SDK(the one downloaded from Android Website) completely.
- Download the Code Works For Android from [https://developer.nvidia.com/codeworks-android]( https://developer.nvidia.com/codeworks-android)
- Code Works will notify if there is an Update in the SDK
- Set this path to Android SDK in the Unity Editor.

 **For JDK**     

- Download latest JDK from  [http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
- Set the path to JDK in the Unity Editor.

<img width="501" alt="screen shot 2017-05-04 at 12 43 57 pm" src="https://cloud.githubusercontent.com/assets/12084522/25693561/922de6f0-30c7-11e7-8cbe-a5c36b0733fe.png">

**For PlayServices Plugin** 

1. Uninstall the google play services plugin
2. Remove all Android based plugins (one signal , ad mob etc.,)
3. Download and install the latest google play services plugin  (0.9.37)
4. Set up the Google project from Window->Google Play Games->Setup

<img width="423" alt="screen shot 2017-05-04 at 12 49 28 pm" src="https://cloud.githubusercontent.com/assets/12084522/25694205/20c7d59e-30cb-11e7-8ec1-b8ecb72ff81e.png">

<img width="425" alt="screen shot 2017-05-04 at 12 49 43 pm" src="https://cloud.githubusercontent.com/assets/12084522/25694211/2537c8d2-30cb-11e7-99b7-77b4c01f5474.png">

Now you can take a build and Google play login works in Android version >4.4

If you face **CommandInvokationFailure: Unable to convert classes into dex format**
This is due to Android SDK or JDK(most probably JDK)

**For Adding Other Plugins**

Add other plugins if needed. Don't import PlayserviceResolver since you can use the one which came with Latest Google Play Services Plugin.
<img width="169" alt="screen shot 2017-05-04 at 1 14 12 pm" src="https://cloud.githubusercontent.com/assets/12084522/25694305/9c0fdde6-30cb-11e7-87a1-39197f29d1c2.png">

Plugin With automatically install play-services dependencies after asking a verification.

<img width="271" alt="screen shot 2017-05-04 at 1 15 00 pm" src="https://cloud.githubusercontent.com/assets/12084522/25694330/bf9403a0-30cb-11e7-9658-a9326e10eeeb.png">


Let me know if this works...

**Comment by dgiunchi** [comment]
I follow all these instruction but I get always this error
![error](https://cloud.githubusercontent.com/assets/240205/26462496/f6a13bac-4178-11e7-82da-92fdf57dcd14.png)

**Comment by dgiunchi** [comment]
ok , after an automatic replacement, the previous error was removed. For get google play service work, I had to recreate the app in google developer console.

**Comment by claywilkinson** [comment]
Sounds like it is working now.  OK to close this issue?

**Comment by Kmess** [comment]
I ran into this issue very recently - it turns out I thought I deleted the previous plugin but I left libgpg.so in the libs folder under Plugins/Android. Deleting this library fixed it, wanted to give a heads up to anyone who sees it when adding Firebase to their GPG already implemented projects
