### ISSUE TITLE
CommandInvokationFailure: Failed to re-package resources

### ISSUE THREAD

**Issue by vickysmalley** [playgameservices/play-games-plugin-for-unity#1777]
I am unable to build an apk after adding the plugin, I'm using Unity 5.4.5f1 and have previously installed the Firebase unity sdk, version 3.0.3, as well as an sdk from KTPlay

I have seen in other issues that there are problems with the latest version of Google Play Services so have downgraded to verion 10.0.1 for both play-services and firebase as described here:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/1604

The error I'm now getting when I attempt to build is: 

CommandInvokationFailure: Failed to re-package resources.
/Users/vickysmalley/AndroidSDK/adt-bundle-mac-x86_64-20131030/sdk/build-tools/25.0.2/aapt package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "/Users/vickysmalley/AndroidSDK/adt-bundle-mac-x86_64-20131030/sdk/platforms/android-23/android.jar" -F bin/resources.ap_ --extra-packages com.google.firebase.unity:com.android.vending.billing:com.unity.purchasing.googleplay:com.ktplay.sdk:com.google.example.games.mainlibproj:com.unity.purchasing:com.google.firebase.unity.app:com.google.firebase.auth.api:com.google.firebase.unity.auth:com.google.firebase:com.google.firebase.iid:com.google.firebase.messaging:com.google.firebase.unity.messaging:com.google.android.gms.ads.impl:com.google.android.gms.ads:com.google.android.gms.auth.api:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms:com.google.android.gms.clearcut:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.gass:com.google.android.gms.nearby:com.google.android.gms.tasks:android.support.compat:android.support.coreui:android.support.coreutils:android.support.fragment:android.support.mediacompat:android.support.v4 -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/Firebase/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/GoogleAIDL/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/GooglePlay/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/common/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/firebase-auth-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/firebase-common-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/firebase-iid-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/firebase-messaging-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/play-services-ads-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/play-services-ads-lite-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/play-services-auth-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/play-services-auth-base-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/play-services-base-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/play-services-basement-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/play-services-clearcut-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/play-services-drive-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/play-services-games-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/play-services-gass-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/play-services-nearby-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/play-services-tasks-10.0.1/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/support-compat-25.2.0/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/support-core-ui-25.2.0/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/support-core-utils-25.2.0/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/support-fragment-25.2.0/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/support-media-compat-25.2.0/res" -S "/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/support-v4-25.2.0/res"

stderr[
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_album.xml:16: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <ImageView>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_album.xml: note: using v17 attributes; synthesizing resource com.smalljelly.rocketrumble:layout/kryptanium_adapter_item_album for configuration v17.
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_blocked_users.xml:24: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <TextView>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_blocked_users.xml:24: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <TextView>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_blocked_users.xml:10: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentStart from <TextView>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_blocked_users.xml:10: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <TextView>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_blocked_users.xml: note: using v17 attributes; synthesizing resource com.smalljelly.rocketrumble:layout/kryptanium_adapter_item_chat_blocked_users for configuration v17.
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_list_normal.xml:62: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_list_normal.xml:62: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <LinearLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_list_normal.xml:84: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_list_normal.xml:84: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <LinearLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_list_normal.xml:71: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_list_normal.xml:71: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <TextView>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_list_normal.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <LinearLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_list_normal.xml:8: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_list_normal.xml: note: using v17 attributes; synthesizing resource com.smalljelly.rocketrumble:layout/kryptanium_adapter_item_chat_list_normal for configuration v17.
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_me.xml:19: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <LinearLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_me.xml:19: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_me.xml:61: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <RelativeLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_me.xml:151: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentStart from <com.ktplay.widget.KTEmojiText>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_me.xml:151: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <com.ktplay.widget.KTEmojiText>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_me.xml:151: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <com.ktplay.widget.KTEmojiText>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_me.xml:111: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <ProgressBar>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_me.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <ProgressBar>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_me.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <com.ktplay.widget.NoClickStateImageView>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_me.xml: note: using v17 attributes; synthesizing resource com.smalljelly.rocketrumble:layout/kryptanium_adapter_item_chat_me for configuration v17.
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_other.xml:21: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentStart from <LinearLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_other.xml:21: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_other.xml:73: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <RelativeLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_other.xml:99: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentStart from <com.ktplay.widget.KTEmojiText>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_other.xml:99: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <com.ktplay.widget.KTEmojiText>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_other.xml:99: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <com.ktplay.widget.KTEmojiText>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_other.xml:63: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <com.ktplay.widget.KTRoundRectImageView>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_other.xml:45: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <com.ktplay.widget.KTEmojiText>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_other.xml: note: using v17 attributes; synthesizing resource com.smalljelly.rocketrumble:layout/kryptanium_adapter_item_chat_other for configuration v17.
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_stranger.xml:19: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentStart from <RelativeLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_stranger.xml:19: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <RelativeLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_stranger.xml:37: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <RelativeLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_stranger.xml:75: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <RelativeLayout>
/Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/KTPlay/res/layout/kryptanium_adapter_item_chat_stranger.xml:103: note: removing attr<message truncated>

**Comment by claywilkinson** [comment]
Downgrading play-services rarely goes well :/  Unfortunately it looks like your post was truncated, I only see notes and not the error.  Did you try updating play-services to the latest - 10.2.6?

**Comment by vickysmalley** [comment]
I was on 10.2.4 with both firebase and play services. Will try upgrading to 10.2.6, thanks.

**Comment by claywilkinson** [comment]
Also make sure your android platform tools are up to date in the Android SDK.

**Comment by vickysmalley** [comment]
I've updated play-services to 10.2.6 but it's not possible to use the latest android platform tools with Unity - see this issue (which isn't resolved even though it has been marked as such).  
https://issuetracker.unity3d.com/issues/android-build-fails-when-the-latest-android-sdk-tools-25-dot-3-1-version-is-used
I've tried updating to the patched version of Unity (5.4.5p2) but am getting the same problem as everyone else with merging the manifest.

I'm currently getting a couple of warnings:
No compatible versions of com.android.support:support-v4 required by (com.google.android.gms:play-services-basement:10.2.6), will try using the latest version 25.2.0
No compatible versions of com.android.support:support-annotations required by (com.android.support:support-v4:24.0.0, com.android.support:support-compat:25.2.0), will try using the latest version 25.2.0\

and on attempting a build get this error:

CommandInvokationFailure: Unable to convert classes into dex format.
/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/vickysmalley/AndroidSDK/adt-bundle-mac-x86_64-20131030/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity_5.4.5p2/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorCompatHelper;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImplBase;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImplHC;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:613)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:605)
	... 9 more
]
stdout[
processing archive /Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/GoogleAIDL/libs/./classes.jar...
processing com/android/vending/billing/BuildConfig.class...
processing com/android/vending/billing/IInAppBillingService.class...
processing com/android/vending/billing/IInAppBillingService$Stub.class...
processing com/android/vending/billing/IInAppBillingService$Stub$Proxy.class...
processing archive /Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/GooglePlay/libs/./classes.jar...
processing com/unity/purchasing/googleplay/ActivityLauncher.class...
processing com/unity/purchasing/googleplay/BillingServiceManager.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$2.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$2.class...
processing com/unity/purchasing/googleplay/BillingServiceProcessor.class...
processing com/unity/purchasing/googleplay/BuildConfig.class...
processing com/unity/purchasing/googleplay/Consts.class...
processing com/unity/purchasing/googleplay/Consts$PurchaseState.class...
processing com/unity/purchasing/googleplay/Consts$ResponseCode.class...
processing com/unity/purchasing/googleplay/GooglePlayBillingUnAvailableException.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$1.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$2.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$3.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$4.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$5.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$6.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$7.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$Features.class...
processing com/unity/purchasing/googleplay/IActivityLauncher.class...
processing com/unity/purchasing/googleplay/IBillingServiceManager.class...
processing com/unity/purchasing/googleplay/IabException.class...
processing com/unity/purchasing/googleplay/IabHelper.class...
processing com/unity/purchasing/googleplay/IabHelper$1.class...
processing com/unity/purchasing/googleplay/IabHelper$2.class...
processing com/unity/purchasing/googleplay/IabHelper$2$1.class...
processing com/unity/purchasing/googleplay/IabHelper$3.class...
processing com/unity/purchasing/googleplay/IabHelper$4.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeMultiFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabPurchaseFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabSetupFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$QueryInventoryFinishedListener.class...
processing com/unity/purchasing/googleplay/IabResult.class...
processing com/unity/purchasing/googleplay/Inventory.class...
processing com/unity/purchasing/googleplay/Purchase.class...
processing com/unity/purchasing/googleplay/PurchaseActivity.class...
processing com/unity/purchasing/googleplay/PurchaseFailedEvent.class...
processing com/unity/purchasing/googleplay/SkuDetails.class...
processing archive /Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/MainLibProj/libs/./play-games-plugin-support.jar...
processing com/google/games/bridge/BuildConfig.class...
processing com/google/games/bridge/NativeBridgeActivity.class...
processing com/google/games/bridge/TokenFragment.class...
processing com/google/games/bridge/TokenFragment$1.class...
processing com/google/games/bridge/TokenFragment$TokenRequest.class...
processing com/google/games/bridge/TokenPendingResult.class...
processing com/google/games/bridge/TokenResult.class...
processing archive /Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/common/libs/./classes.jar...
processing com/unity/purchasing/BuildConfig.class...
processing com/unity/purchasing/common/DelayedHandler.class...
processing com/unity/purchasing/common/IDelayedExecutor.class...
processing com/unity/purchasing/common/INativeStore.class...
processing com/unity/purchasing/common/IStore.class...
processing com/unity/purchasing/common/IStoreCallback.class...
processing com/unity/purchasing/common/IUnityCallback.class...
processing com/unity/purchasing/common/InitializationFailureReason.class...
processing com/unity/purchasing/common/ProductDefinition.class...
processing com/unity/purchasing/common/ProductDescription.class...
processing com/unity/purchasing/common/ProductMetadata.class...
processing com/unity/purchasing/common/ProductType.class...
processing com/unity/purchasing/common/PurchaseFailedEvent.class...
processing com/unity/purchasing/common/PurchaseFailureDescription.class...
processing com/unity/purchasing/common/PurchaseFailureReason.class...
processing com/unity/purchasing/common/SaneJSONObject.class...
processing com/unity/purchasing/common/StoreDeserializer.class...
processing com/unity/purchasing/common/UnityPurchasing.class...
ignored resource /Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/firebase-app-unity-3.0.3/libs/./armeabi-v7a/libApp.so
processing archive /Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/firebase-app-unity-3.0.3/libs/./classes.jar...
ignored resource /Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/firebase-app-unity-3.0.3/libs/./x86/libApp.so
processing archive /Users/vickysmalley/Documents/SmallJelly/Bitbucket/rocket_rumble.android/Temp/StagingArea/android-libraries/firebase-auth-10.2.4/libs/./classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/internal/
processing com/google/android/gms/internal/zzblr.class...
processing com/google/android/gms/internal/zzbls.class...
processing com/google/android/gms/internal/zzbls$zza.class...
processing com/google/android/gms/internal/zzbls$zzb.class...
processing com/google/android/gms/internal/zzbls$zzc.class...
processing com/google/android/gms/internal/zzbls$zzd.class...
processing com/google/android/gms/internal/zzbls$zze.class...
processing com/google/android/gms/internal/zzbls$zzf.class...
processing com/google/android/gms/internal/zzbls$zzg.class...
processing co

**Comment by claywilkinson** [comment]
This error: `Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;`

Is probably caused by having multiple versions of support-v4 in your project.

Can you make sure you have only one version of the aar files in Assets/Plugins/Android.

If it still does not work, can you share the directory listing of  Assets/Plugins/Android?

I have confirmed that the latest tools work with 5.4.5p2 - if it was not working, you would not get to the the merging manifest stage - it just errors out with: `Build fails "CommandInvokationFailure: Unable to list target platforms. Please make sure the android sdk path is correct. See the Console for more details. ..."`

Make sure if you are using the patched version (p2) that your tools are updated to version 26 or greater.

**Comment by vickysmalley** [comment]
Hi,

I definitely only have one version of support-v4 in my project and one version of each aar in the plugins folder.

With the latest tools and version 5.4.5p2 I get the error
CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/vickysmalley/Library/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity_5.4.5p2/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

I've attached a screenshot of the files in Assets/Plugins/Android

![screen shot 2017-06-08 at 11 34 59](https://user-images.githubusercontent.com/13088944/26924624-8fccebee-4c3e-11e7-9f91-1d522c4b3608.png)

Thanks in advance for your help.

**Comment by claywilkinson** [comment]
From the file list, you want to have all the same versions of play-services*.  So you definitely want to remove or replace play-services-ads-lite-10.2.1 with 10.2.6

As far as the unable to merge, can you save the output of the command (it is in Unity console and is very long) to a [Gist](https://gist.github.com/) or a file so it is not truncated?

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
