### ISSUE TITLE
Upon opening Leaderboard, Long Load Times and Crashes

### ISSUE THREAD

**Issue by johnW-ret** [playgameservices/play-games-plugin-for-unity#1788]
I am using the latest stable version of the plugin (v0.9.39).

Signing into Google Play Games works fine, but accessing a leaderboard takes a really long time on a fast internet connection: 20+ seconds, and I've had it take even longer, up to +60 seconds. Occasionally, I'll get a crash when switching to world leaderboard, but I can't get you the logcat information on it yet because it randomly crashes and I've yet to trigger it with Android Studio open. A beta tester has reported that he can't get it to open without it crashing. When it crashes, it says "Google Play Games has stopped", but the game closes as well.

Stack trace (from Google Play Console):
`java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2017.1.0b7
Device model      : motorola Moto G (4)
Device fingerprint: motorola/athene/athene:7.0/NPJS25.93-14-4/4:user/release-keys
Caused by
  at com.google.android.gms.common.internal.zzf$zza.zzb(Unknown Source:0)
  at com.google.android.gms.common.internal.zzf$zza.zzu(Unknown Source:0)
  at com.google.android.gms.common.internal.zzf$zze.zzxH(Unknown Source:0)
  at com.google.android.gms.common.internal.zzf$zzd.handleMessage(Unknown Source:0)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6123)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

Additional stack trace (from Google Play Console): signal 11 (SIGSEGV), code 2 (SEGV_ACCERR) `backtrace:
  native: pc 000000000001756c  /system/lib/libc.so (memcpy+100)
  native: pc 0000000000177c2b  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN9BltDevice17ExecFastCopyBlockEPvPKvjjjjPK7BltRectS5_i+106)
  native: pc 00000000001780ad  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN9BltDevice14ExecFastSwCopyEP13BltExecSwCopy+844)
  native: pc 000000000017dde5  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN9BltDevice18ExecSwCopyInternalEP13BltExecSwCopy+7076)
  native: pc 000000000017df2f  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN9BltDevice10ExecSwCopyEP13BltExecSwCopy+174)
  native: pc 00000000001534a3  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN9EsxBltLib16CopyHostPtrBltSwEPK17EsxBltCopyHostPtr+1218)
  native: pc 000000000012788b  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN11EsxResource23UpdateSubResourceDirectEP10EsxContextjPK6EsxBoxPK20EsxSurfaceAccessDesci+650)
  native: pc 00000000000e7ed5  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxContext17UpdateSubResourceEP11EsxResourcejPK6EsxBoxPK20EsxSurfaceAccessDesc+788)
  native: pc 0000000000139e13  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN15EsxBufferObject6UpdateEP10EsxContextyjPKv+114)
  native: pc 00000000000d0285  /system/vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxContext12GlBufferDataEjlPKvj+100)
  native: pc 00000000000b8581  /system/vendor/lib/egl/libGLESv2_adreno.so (glBufferData+32)
  native: pc 00000000005d3334  /data/app/com.Retruate.DropTower-1/lib/arm/libunity.so
  native: pc 00000000005a94c4  /data/app/com.Retruate.DropTower-1/lib/arm/libunity.so
  native: pc 00000000005a93ec  /data/app/com.Retruate.DropTower-1/lib/arm/libunity.so
  native: pc 00000000005b8f64  /data/app/com.Retruate.DropTower-1/lib/arm/libunity.so
  native: pc 00000000005ba400  /data/app/com.Retruate.DropTower-1/lib/arm/libunity.so
  native: pc 00000000002b133c  /data/app/com.Retruate.DropTower-1/lib/arm/libunity.so
  native: pc 00000000002b0478  /data/app/com.Retruate.DropTower-1/lib/arm/libunity.so
  native: pc 000000000048ede8  /data/app/com.Retruate.DropTower-1/lib/arm/libunity.so
  native: pc 0000000000258838  /data/app/com.Retruate.DropTower-1/lib/arm/libunity.so
  native: pc 00000000002217e4  /data/app/com.Retruate.DropTower-1/lib/arm/libunity.so
  native: pc 0000000000630414  /data/app/com.Retruate.DropTower-1/lib/arm/libunity.so
  native: pc 00000000006328e4  /data/app/com.Retruate.DropTower-1/lib/arm/libunity.so
  native: pc 0000000000016501  /data/app/com.Retruate.DropTower-1/oat/arm/base.odex`

If there's any more germane information I can share to help solve the issue (like some of my code), I'd be glad.

Thanks.

**Comment by HarryDemch** [comment]
I have a similar problem.
I'm using v0.9.39a and Unity 5.6.2f1 (64-bit), everything works as expected (sign in, sign out and achievements), but when I'm trying to open leaderboards, it never opens, just trying to load.
I'm testing on Beta with Google Play App Signing turned on.

When I'm installing the app directly from PC on my device, I can't sign in. I guess it's because of Google Play App Signing.

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
