### ISSUE TITLE
Crash when activating android application

### ISSUE THREAD

**Issue by mkorotetsky** [playgameservices/play-games-plugin-for-unity#1792]
Hi,
I have rare crash when I resume my application from background.

java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 5.5.3p4
Device model      : Sony D5503
Device fingerprint: Sony/D5503/D5503:5.1.1/14.6.A.1.236/2031203603:user/release-keys
Caused by: java.lang.SecurityException: Not signed in when calling API
	at android.os.Parcel.readException(Parcel.java:1553)
	at android.os.Parcel.readException(Parcel.java:1505)
	at com.google.android.gms.games.internal.IGamesService$Stub$Proxy.zzuB(Unknown Source)
	at com.google.android.gms.games.internal.GamesClientImpl.zzuB(Unknown Source)
	at com.google.android.gms.common.internal.zzf$zzj.zzxG(Unknown Source)
	at com.google.android.gms.common.internal.zzf$zza.zzb(Unknown Source)
	at com.google.android.gms.common.internal.zzf$zza.zzu(Unknown Source)
	at com.google.android.gms.common.internal.zzf$zze.zzxH(Unknown Source)
	at com.google.android.gms.common.internal.zzf$zzd.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5389)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by claywilkinson** [comment]
Can you share more of the log?  Can you share steps to reproduce this?

**Comment by JimmyDeemo** [comment]
@mkorotetsky @claywilkinson  Did anything come of this? We have a few hundred of these a day? Unfortunately I don't have any additional information other than the android version breakdown;

![image](https://user-images.githubusercontent.com/4234718/31615995-52721390-b283-11e7-8535-160172eafd42.png)

Any ideas on what sort of things to try to repro this crash? Could it be linked to the recent fix for stopping the GPG dialogue popping up on resume of application? Seen with Unity versions 5.4.5f1 and 2017.1.1p3.

**Comment by DevByStarlight** [comment]
@claywilkinson
Seeing the same thing on Pixel XL2, Moto Z2, and other devices.

Environment:
- Unity 2017.3.0f3
- Google Play Games plugin for Unity v0.9.41
- Android Build Tools 26.0.1
- Google play services API libraries v11.0.4
  .. eg, "play-services-games:11.0.4@aar"
- Targeting Android API 25
-- (same happens if target API 26 but I have a service not Oreo compatible which I need to migrate)
- proguarded _with_ obfuscation enabled

Code runs fine most of the time - successful login, access google play games, etc. So it does not appear to be a proguard stripping of a class (ie, not seeing ClassNotFoundException).

In my local builds I can get it to happen fairly regularly. Most often when uninstall/reinstall when previous install had the player signed in to GPGS. 

My crash stack mirrors the OP's.

Searching the magical internet shows this has been an issue for Google Games (not specifically Unity's plugin) for many years - as far back as 2012.
- https://stackoverflow.com/questions/26902935/android-api-isconnected-returning-true-after-signing-out
- https://forums.coronalabs.com/topic/59310-google-play-game-service-crash-if-when-logout/
- https://github.com/ptgamr/cordova-google-play-game/issues/2

The apparent fix _seems_ to be to force a disconnect via 'onActivityResult' (as per above SO posts). However, with the GPG unity plugin the access is sort of abstracted and we don't really implement anything java-side nor have access to the GPGS API client instance, etc.

Is there, perhaps, a missing a step in the plugin install add some handling in onActivityResult?

I _do_ have a native plugin. And I can certainly extend the UnityPlayerNativeActivity to add something if necessary.

(Side note: App is in alpha with some friendly testers. I get a somewhat small but notable occurrence of these exceptions. Affects about 2-3% of my testers. In other words, would be very nice to get this fixed.)

Thanks in advance!

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
