### ISSUE TITLE
Instant crash on game startup. (0.9.39a)

### ISSUE THREAD

**Issue by Royy212** [playgameservices/play-games-plugin-for-unity#1820]
Hi guys, first time using the play game services.
I'm pretty sure I've set everything up correctly. 
Whenever I start the game on mobile, the game immediately stops.
I'm using GooglePlayGamesPlugin-0.9.39a and when I turn this off the game is running fine.

Is there any know bugs/fix for this problem?

**Comment by JimmyDeemo** [comment]
I think that responsers are going to need more information. Suggest setting `PlayGamesPlatform.DebugLogEnabled = true` and grabbing a log using `adb logcat`, posting the response.

**Comment by Royy212** [comment]
Hi I've followed another video and saw that I missed some steps. Now I've another issue when I want to build the APK. The issue is: "Unable to convert classes into dex format."

This is showed in the console:

`CommandInvokationFailure: Unable to convert classes into dex format.
D:/jdk1.8.0_131\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="D:/Local/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorCompatHelper;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImplBase;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle$ActionBarDrawerToggleImplHC;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:613)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at SDKMain.main(SDKMain.java:130)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:605)
	... 9 more
]
stdout[
processing archive D:\Unity\FruitRun\Temp\StagingArea\android-libraries\MainLibProj\libs\.\play-games-plugin-support.jar...
processing com/google/games/bridge/BuildConfig.class...
processing com/google/games/bridge/NativeBridgeActivity.class...
processing com/google/games/bridge/TokenFragment.class...
processing com/google/games/bridge/TokenFragment$1.class...
processing com/google/games/bridge/TokenFragment$2.class...
processing com/google/games/bridge/TokenFragment$TokenRequest.class...
processing com/google/games/bridge/TokenPendingResult.class...
processing com/google/games/bridge/TokenResult.class...
processing archive D:\Unity\FruitRun\Temp\StagingArea\android-libraries\play-services-auth-10.0.1\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/auth/
ignored resource com/google/android/gms/auth/api/
processing com/google/android/gms/auth/api/Auth.class...
processing com/google/android/gms/auth/api/Auth$1.class...
processing com/google/android/gms/auth/api/Auth$2.class...
processing com/google/android/gms/auth/api/Auth$3.class...
processing com/google/android/gms/auth/api/Auth$AuthCredentialsOptions.class...
processing com/google/android/gms/auth/api/Auth$AuthCredentialsOptions$Builder.class...
ignored resource com/google/android/gms/auth/api/credentials/
processing com/google/android/gms/auth/api/credentials/Credential.class...
processing com/google/android/gms/auth/api/credentials/Credential$Builder.class...
processing com/google/android/gms/auth/api/credentials/CredentialPickerConfig.class...
processing com/google/android/gms/auth/api/credentials/CredentialPickerConfig$1.class...
processing com/google/android/gms/auth/api/credentials/CredentialPickerConfig$Builder.class...
processing com/google/android/gms/auth/api/credentials/CredentialPickerConfig$Prompt.class...
processing com/google/android/gms/auth/api/credentials/CredentialRequest.class...
processing com/google/android/gms/auth/api/credentials/CredentialRequest$1.class...
processing com/google/android/gms/auth/api/credentials/CredentialRequest$Builder.class...
processing com/google/android/gms/auth/api/credentials/CredentialRequestResult.class...
processing com/google/android/gms/auth/api/credentials/CredentialsApi.class...
processing com/google/android/gms/auth/api/credentials/HintRequest.class...
processing com/google/android/gms/auth/api/credentials/HintRequest$1.class...
processing com/google/android/gms/auth/api/credentials/HintRequest$Builder.class...
processing com/google/android/gms/auth/api/credentials/IdToken.class...
processing com/google/android/gms/auth/api/credentials/IdentityProviders.class...
processing com/google/android/gms/auth/api/credentials/PasswordSpecification.class...
processing com/google/android/gms/auth/api/credentials/PasswordSpecification$zza.class...
processing com/google/android/gms/auth/api/credentials/PasswordSpecification$zzb.class...
processing com/google/android/gms/auth/api/credentials/zza.class...
processing com/google/android/gms/auth/api/credentials/zzb.class...
processing com/google/android/gms/auth/api/credentials/zzc.class...
processing com/google/android/gms/auth/api/credentials/zzd.class...
processing com/google/android/gms/auth/api/credentials/zze.class...
processing com/google/android/gms/auth/api/credentials/zzf.class...
ignored resource com/google/android/gms/auth/api/signin/
processing com/google/android/gms/auth/api/signin/GoogleSignInApi.class...
processing com/google/android/gms/auth/api/signin/GoogleSignInResult.class...
processing com/google/android/gms/auth/api/signin/GoogleSignInStatusCodes.class...
processing com/google/android/gms/auth/api/signin/RevocationBoundService.class...
processing com/google/android/gms/auth/api/signin/SignInAccount.class...
ignored resource com/google/android/gms/auth/api/signin/internal/
processing com/google/android/gms/auth/api/signin/internal/SignInConfiguration.class...
processing com/google/android/gms/auth/api/signin/internal/SignInHubActivity.class...
processing com/google/android/gms/auth/api/signin/internal/SignInHubActivity$1.class...
processing com/google/android/gms/auth/api/signin/internal/SignInHubActivity$zza.class...
processing com/google/android/gms/auth/api/signin/internal/zza.class...
processing com/google/android/gms/auth/api/signin/internal/zzb.class...
processing com/google/android/gms/auth/api/signin/internal/zzc.class...
processing com/google/android/gms/auth/api/signin/internal/zzd.class...
processing com/google/android/gms/auth/api/signin/internal/zze.class...
processing com/google/android/gms/auth/api/signin/internal/zze$1.class...
processing com/google/android/gms/auth/api/signin/internal/zze$1$1.class...
processing com/google/android/gms/auth/api/signin/internal/zze$2.class...
processing com/google/android/gms/auth/api/signin/internal/zze$2$1.class...
processing com/google/android/gms/auth/api/signin/internal/zze$3.class...
processing com/google/android/gms/auth/api/signin/internal/zze$3$1.class...
processing com/google/android/gms/auth/api/signin/internal/zze$zza.class...
processing com/google/android/gms/auth/api/signin/internal/zzg.class...
processing com/google/android/gms/auth/api/signin/internal/zzg$zza.class...
processing com/google/android/gms/auth/api/signin/internal/zzh.class...
processing com/google/android/gms/auth/api/signin/internal/zzh$zza.class...
processing com/google/android/gms/auth/api/signin/internal/zzh$zza$zza.class...
processing com/google/android/gms/auth/api/signin/internal/zzi.class...
processing com/google/android/gms/auth/api/signin/internal/zzi$zza.class...
processing com/google/android/gms/auth/api/signin/internal/zzi$zza$zza.class...
processing com/google/android/gms/auth/api/signin/internal/zzj.class...
processing com/google/android/gms/auth/api/signin/internal/zzk.class...
processing com/google/android/gms/auth/api/signin/zzc.class...
ignored resource com/google/android/gms/internal/
processing com/google/android/gms/internal/zzun.class...
processing com/google/android/gms/internal/zzuo.class...
processing com/google/android/gms/internal/zzup.class...
processing com/google/android/gms/internal/zzuq.class...
processing com/google/android/gms/internal/zzuq$zza.class...
processing com/google/android/gms/internal/zzuq$zza$zza.class...
processing com/google/android/gms/internal/zzur.class...
processing com/google/android/gms/internal/zzur$zza.class...
processing com/google/android/gms/internal/zzur$zza$zza.class...
processing com/google/android/gms/internal/zzus.class...
processing com/google/android/gms/internal/zzut.class...
processing com/google/android/gms/internal/zzuu.class...
processing com/google/android/gms/internal/zzuv.class...
processing com/google/android/gms/internal/zzuw.class...
processing com/google/android/gms/internal/zzuw$1.class...
processing com/google/android/gms/internal/zzuw$1$1.class...
processing com/google/android/gms/internal/zzuw$2.class...
processing com/google/android/gms/internal/zzuw$3.class...
processing com/google/android/gms/internal/zzuw$4.class...
processing com/google/android/gms/internal/zzuw$zza.class...
processing com/google/android/gms/internal/zzux.class...
processing com/google/android/gms/internal/zzuy.class...
processing com/google/android/gms/internal/zzuz.class...
processing com/google/android/gms/internal/zzva.class...
processing com/google/android/gms/internal/zzvb.class...
processing com/google/android/gms/internal/zzvc.class...
processing com/google/android/gms/internal/zzvd.class...
processing com/google/android/gms/internal/zzve.class...
processing com/google/android/gms/internal/zzve$zza.class...
processing com/google/android/gms/internal/zzve$zza$zza.class...
processing com/google/android/gms/internal/zzvf.class...
processing com/google/android/gms/internal/zzvf$zza.class...
processing com/google/android/gms/internal/zzvf$zza$zza.class...
processing com/google/android/gms/internal/zzvg.class...
processing com/google/android/gms/internal/zzvh.class...
processing archive D:\Unity\FruitRun\Temp\StagingArea\android-libraries\play-services-auth-base-10.0.1\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/auth/
processing com/google/android/gms/auth/AccountChangeEvent.class...
processing com/google/android/gms/auth/AccountChangeEventsRequest.class...
processing com/google/android/gms/auth/AccountChangeEventsResponse.class...
processing com/google/android/gms/auth/GoogleAuthException.class...
processing com/google/android/gms/auth/GoogleAuthUtil.class...
processing com/google/android/gms/auth/GooglePlayServicesAvailabilityException.class...
processing com/google/android/gms/auth/TokenData.class...
processing com/google/android/gms/auth/UserRecoverableAuthException.class...
processing com/google/android/gms/auth/UserRecoverableNotifiedException.class...
ignored resource com/google/android/gms/auth/account/
processing com/google/android/gms/auth/account/WorkAccount.class...
processing com/google/android/gms/auth/account/WorkAccount$1.class...
processing com/google/android/gms/auth/account/WorkAccountApi.class...
processing com/google/android/gms/auth/account/WorkAccountApi$AddAccountResult.class...
processing com/google/android/gms/auth/account/zza.class...
processing com/google/android/gms/auth/account/zza$zza.class...
processing com/google/android/gms/auth/account/zza$zza$zza.class...
processing com/google/android/gms/auth/account/zzb.class...
processing com/google/android/gms/auth/account/zzb$zza.class...
processing com/google/android/gms/auth/account/zzb$zza$zza.class...
ignored resource com/google/android/gms/auth/api/
ignored resource com/google/android/gms/auth/api/proxy/
processing com/google/android/gms/auth/api/proxy/AuthApiStatusCodes.class...
processing com/google/android/gms/auth/api/proxy/ProxyApi.class...
processing com/google/android/gms/auth/api/proxy/ProxyApi$ProxyResult.class...
processing com/google/android/gms/auth/api/proxy/ProxyRequest.class...
processing com/google/android/gms/auth/api/proxy/ProxyRequest$Builder.class...
processing com/google/android/gms/auth/api/proxy/ProxyResponse.class...
processing com/google/android/gms/auth/api/proxy/zza.class...
processing com/google/android/gms/auth/api/proxy/zzb.class...
processing com/google/android/gms/auth/api/proxy/zzc.class...
processing com/google/android/gms/auth/api/proxy/zzd.class...
processing com/google/android/gms/auth/api/zza.class...
processing com/google/android/gms/auth/api/zza$1.class...
processing com/google/android/gms/auth/api/zzb.class...
processing com/google/android/gms/auth/zza.class...
processing com/google/android/gms/auth/zzb.class...
processing com/google/android/gms/auth/zzc.class...
processing com/google/android/gms/auth/zzd.class...
processing com/google/android/gms/auth/zze.class...
processing com/google/android/gms/auth/zze$1.class...
processing com/google/android/gms/auth/zze$2.class...
processing com/google/android/gms/auth/zze$3.class...
processing com/google/android/gms/auth/zze$4.class...
processing com/google/android/gms/auth/zze$zza.class...
processing com/google/android/gms/auth/zzf.class...
ignored resource com/google/android/gms/internal/
processing com/google/android/gms/internal/zzbz.class...
processing com/google/android/gms/internal/zzbz$zza.class...
processing com/google/android/gms/internal/zzbz$zza$zza.class...
processing com/google/android/gms/internal/zzul.class...
processing com/google/android/gms/internal/zzul$1.class...
processing com/google/android/gms/internal/zzul$2.class...
processing com/google/android/gms/internal/zzul$2$1.class...
processing com/google/android/gms/internal/zzul$3.class...
processing com/google/android/gms/internal/zzul$3$1.class...
processing com/google/android/gms/internal/zzul$zza.class...
processing com/google/android/gms/internal/zzul$zzb.class...
processing com/google/android/gms/internal/zzul$zzc.class...
processing com/google/android/gms/internal/zzum.class...
processing com/google/android/gms/internal/zzvi.class...
processing com/google/android/gms/internal/zzvj.class...
processing com/google/android/gms/internal/zzvk.class...
processing com/google/android/gms/internal/zzvk$zza.class...
processing com/google/android/gms/internal/zzvk$zza$zza.class...
processing com/google/android/gms/internal/zzvl.class...
processing com/google/android/gms/internal/zzvl$zza.class...
processing com/google/android/gms/internal/zzvl$zza$zza.class...
processing com/google/android/gms/internal/zzvm.class...
processing com/google/android/gms/internal/zzvn.class...
processing com/google/android/gms/internal/zzvn$1.class...
processing com/google/android/gms/internal/zzvn$1$1.class...
processing com/google/android/gms/internal/zzvo.class...
processing com/google/android/gms/internal/zzvp.class...
processing archive D:\Unity\FruitRun\Temp\StagingArea\android-libraries\play-services-base-10.0.1\libs\.\classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/auth/
ignored resource com/google/android/gms/auth/api/
ignored resource com/google/android/gms/auth/api/signin/
processing com/google/android/gms/auth/api/signin/GoogleSignInAccount.class...
processing com/google/android/<message truncated>`

**Comment by claywilkinson** [comment]
Can you share a log of when you are trying to show the achievements or leaderboard?

**Comment by Royy212** [comment]
I just posted a new post, totally forgot about this one. I thought I was able to login, but I changed my code. And when I login succesfully (succes), then I change some text in my app telling me it was succesfull. I do the same when I fail to login. And the text always changes to failed to login.

I'm going to try to post a log, I'm pretty new trying to debug android.

**Comment by Royy212** [comment]
You have to make sure you have enrolled app signing in the google play console and have your game linked in the game services (also in the google play console).

Then after that, you have to go app signing and COPY your SHA1 upload certificate (You find this in google play console > App Signing.)
Then you have to go to this site: https://console.developers.google.com
Open up your project > go to credentials > then find your OAuth 2.0 client IDs (this is linked to your APK you uploaded.) 
Then you have to click on edit OAuth client.
Here you will need to paste your copied SHA-1 certificate with the existing SHA-1 cerfitcate.
After that save it and you should be able to login to the google play services!.

Here are some images to guide you through: http://imgur.com/a/zw0Os

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
