### ISSUE TITLE
Unable to convert classes into dex format.

### ISSUE THREAD

**Issue by STobiasS** [playgameservices/play-games-plugin-for-unity#1860]
Hello,
I am having difficulty with this error in Unity: Unable to convert classes into dex format.
I get this Error if i want to Buld my Game to an APK (Android)
I read much about this Error in connection to Google Play Service and Facebook etc., but i dont use this i only use the Unity Ad Service for my game, and i looked in my Project if i have files dual, like aar files.

I looked 3 days for the Error and delete my Library in the Project, nothing happend.

```
> CommandInvokationFailure: Unable to convert classes into dex format.
> C:\Program Files\Java\jdk1.7.0_71\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/Alexander/AppData/Local/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -
> 
> stderr[
> Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:274)
> 	at SDKMain.main(SDKMain.java:128)
> ]
> stdout[
> 
> ]
> exit code: 1
> UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
> UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
> UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
> UnityEditor.HostView:OnGUI()
```

**Comment by MaxTyT** [comment]
Just update you Java to version 1.8
