### ISSUE TITLE
Unale to launch play store intent

### ISSUE THREAD

**Issue by breineng** [playgameservices/play-games-plugin-for-unity#1902]
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): Unable to launch play store intent
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.google.android.play.games&pcampaignid=GPG_playGamesUpsell flg=0x80000 pkg=com.android.vending }
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1765)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1485)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at android.app.Activity.startActivityForResult(Activity.java:3736)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at fo.startActivityForResult(:com.google.android.gms:1)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at fy.startActivityForResult(:com.google.android.gms:2)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at buo.superStartActivityForResult(:com.google.android.gms:1)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at com.google.android.chimera.Activity.startActivityForResult(:com.google.android.gms:1)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at buo.startActivityForResult(:com.google.android.gms:5)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at android.app.Activity.startActivityForResult(Activity.java:3697)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at fy.startActivityForResult(:com.google.android.gms:1)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at buo.superStartActivityForResult(:com.google.android.gms:0)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at com.google.android.chimera.Activity.startActivityForResult(:com.google.android.gms:0)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at buo.startActivityForResult(:com.google.android.gms:2)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at android.app.Activity.startActivity(Activity.java:4007)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at buo.superStartActivity(:com.google.android.gms:1)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at com.google.android.chimera.Activity.startActivity(:com.google.android.gms:1)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at buo.startActivity(:com.google.android.gms:5)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at android.app.Activity.startActivity(Activity.java:3975)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at buo.superStartActivity(:com.google.android.gms:0)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at com.google.android.chimera.Activity.startActivity(:com.google.android.gms:0)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at sdq.onClick(:com.google.android.gms:6)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at wy.handleMessage(:com.google.android.gms:1)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at android.os.Looper.loop(Looper.java:211)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at android.app.ActivityThread.main(ActivityThread.java:5321)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at java.lang.reflect.Method.invoke(Native Method)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at java.lang.reflect.Method.invoke(Method.java:372)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
09-01 12:53:18.177: E/GamesUpgradeActivity(16169): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by claywilkinson** [comment]
Is the play store installed?  This usually happens when the full suite of Google apps is not installed on the device.  This happens especially in the Emulator.

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
