### ISSUE TITLE
The problem with creating apk for the android in the Unity3D.

### ISSUE THREAD

**Issue by Drift2020** [playgameservices/play-games-plugin-for-unity#1948]
Hello everyone, I began to master the work with the apk and encountered the following problem. Here's the detailed error: 
`CommandInvokationFailure: Failed to build apk.
E:/Java/jdk-9\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="E:/Android/android-sdk-windows\tools" -Dfile.encoding=UTF8 -jar "E:\Unity3D\Unity3Dw\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at SDKMain.main(SDKMain.java:130)
Caused by: java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
	at com.android.sdklib.internal.build.SignedJarBuilder.<init>(SignedJarBuilder.java:177)
	at com.android.sdklib.build.ApkBuilder.init(ApkBuilder.java:446)
	at com.android.sdklib.build.ApkBuilder.<init>(ApkBuilder.java:422)
	at com.android.sdklib.build.ApkBuilder.<init>(ApkBuilder.java:362)
	at UnityApkBuilder.<init>(UnityApkBuilder.java:214)
	at UnityApkBuilder.main(UnityApkBuilder.java:34)
	... 5 more
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 11 more
]
stdout[

]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.HostView:OnGUI()`

My resources: 
![image](https://user-images.githubusercontent.com/32417036/31047169-3be1900a-a60e-11e7-96f0-3b0d16283718.png)
![image](https://user-images.githubusercontent.com/32417036/31047174-4f26a79a-a60e-11e7-84eb-038620e1512c.png)

Unity 5.6.3p2 (64-bit)

I'm trying to build on android 5.1.

![image](https://user-images.githubusercontent.com/32417036/31047190-a08c3ece-a60e-11e7-852b-eca635e57aba.png)

The third day I rack my brains on the forums, I ask humbly your help)

**Comment by idurvesh** [comment]
I am in problem too, Crashing game when try to log into account.used to work good previously. I had similar issue like you where I deleted all the plugins and reimported them again, it fixed that issue

**Comment by moshr** [comment]
Hi! Had the same problem as you. Downgraded to jdk 8, it fixed it for me :) Note that you will probable also need to change the system variables path to your new install folder.

**Comment by Drift2020** [comment]
does not help, I put windows 10 and a new bug ...

1)CommandInvokationFailure: Unable to list target platforms. Please make sure the android sdk path is correct. See the Console for more details. 
C:/Program Files/Java/jdk1.8.0_152\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="F:/Android/SDK\tools" -Dfile.encoding=UTF8 -jar "F:\Unity3d\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error:Invalid command android
]
stdout[

]
exit code: 64
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)



2)UnityEditor.BuildPlayerWindow+BuildMethodException: 3 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x00207] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:172 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00050] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:83 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)


3)UnityEditor.BuildPlayerWindow+BuildMethodException: 3 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x00207] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:172 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00050] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:83 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by Schizo** [comment]
I've downgraded to jdk-8u151 and realized as well that I've never installed JRE (Skipped it apparently when installing jdk, it appears right after the install). However now i got it working.

**Comment by mikecsanders** [comment]
@Drift2020 I had this exact issue as well (actually both of these, but in reverse). Anyway here is the solution I found for the "CommandInvokationFailure: Unable to list target platforms. Please make sure the android sdk path is correct" problem...same sort of thing, need to downgrade your Android SDK as well:

https://answers.unity.com/questions/1323731/unable-to-list-target-platforms-please-make-sure-t.html

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
