### ISSUE TITLE
 java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment

### ISSUE THREAD

**Issue by rheros** [playgameservices/play-games-plugin-for-unity#1976]
build apk success 
install to phone success
when want to connect google ,something not right
here is the trace

UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:400)
	at java.lang.Class.forName(Class.java:326)
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	at com.unity3d.player.UnityPlayer.c(Unknown Source)
	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:159)
	at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.games.bridge.TokenFragment" on path: DexPathList[[zip file "/data/app/com.nutcg.Rush-2/base.apk"],nativeLibraryDirectories=[/data/app/com.nutcg.Rush-2/lib/arm, /data/app/com.nutcg.Rush-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 9 more
  at UnityEngine.AndroidJNISafe.CheckException () [0x0008c] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs:24 
  at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00011] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs:207 
  at UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x002d8] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:460 
  at UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00004] in /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/AndroidJavaBindings.gen.cs:82 
  at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x0001e] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:591 
  at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00013] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:611 
  at UnityEngine.AndroidJavaClass..ctor (System.String className) [0x00009] in /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/AndroidJavaBindings.gen.cs:92 
  at GooglePlayGames.Android.AndroidTokenClient.DoFetchToken (System.Action`1 callback) [0x0002a] in D:\WorkSpace\SpaceBake\UnitySpace\RunningMan\Assets\GooglePlayGames\Platforms\Android\AndroidTokenClient.cs:144 
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
GooglePlayGames.Android.AndroidTokenClient:DoFetchToken(Action`1) (at D:\WorkSpace\SpaceBake\UnitySpace\RunningMan\Assets\GooglePlayGames\Platforms\Android\AndroidTokenClient.cs:180)
GooglePlayGames.Android.<FetchTokens>c__AnonStorey0:<>m__0() (at D:\WorkSpace\SpaceBake\UnitySpace\RunningMan\Assets\GooglePlayGames\Platforms\Android\AndroidTokenClient.cs:134)
GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at D:\WorkSpace\SpaceBake\UnitySpace\RunningMan\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
 
(Filename: D Line: 0)

**Comment by rheros** [comment]
resolved "
delete the version 4.1 files  
reimport version 4.0
every is ok
ps:
version4.1 bug
1、when build can't find service version in AndroidManifest 
2、 com.google.games.bridge.TokenFragment  can't find

**Comment by alex-lushiku** [comment]
What v4.1 files ?

**Comment by Kendja** [comment]
@rheros can you please specify version 4.1 of what? Have the same problem

**Comment by heishi1989** [comment]
I have same problem

I use Unity 2018.3.0f2 and GooglePlayGamesPlugin-0.9.53

Is there any way to solve this problem?
