### ISSUE TITLE
APP crash triying to authenticate with Google Play Games

### ISSUE THREAD

**Issue by asierbh** [playgameservices/play-games-plugin-for-unity#1980]
When i try to authenticate a local user my app crash.
I already doublecheck the next things:
- All the installation/configuration process of the plugin for unity.
- SDK tools needed are up to date.
- Game is updated to google console in Alpha version and im testing google play games login with the correct mail.

My Unity version is : 5.5.4p4
Play Games plugin version: 0.9.41

This is how im triying to authenticate local user in my menu script:

```
using GooglePlayGames;
using UnityEngine.SocialPlatforms;
using GooglePlayGames.BasicApi;

public class MenuScript : MonoBehaviour {
// Use this for initialization
	void Start () {

		PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder ().Build ();
		PlayGamesPlatform.InitializeInstance(config);
		GooglePlayGames.PlayGamesPlatform.DebugLogEnabled = true;
		PlayGamesPlatform.Activate();		
	}
        //Call when achivements button is pressed
	public void ShowAchivements(){

		if (GoogleLogin()) {
			Social.ShowAchievementsUI ();
		} else {
			Debug.Log ("Error login in Google games services");
		}
	}

         public bool GoogleLogin(){
		
		bool resp = false;

		Social.localUser.Authenticate((bool success) => {
			resp = success;
		});

		return resp;
	}

}
```

This is the catlog generated:

[logcat2.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/1384872/logcat2.txt)

Thank you for your time.

**Comment by AsierBH** [comment]
I already found this too using Android Device Monitor in Runtime:

```
10-15 05:27:15.521: W/System.err(3372): 	at com.google.protobuf.AbstractMessageLite$Builder.mergeFrom(AbstractMessageLite.java:153)
10-15 05:27:20.148: I/GamesNativeSDK(9237): Connecting to Google Play...
10-15 05:27:20.175: I/Unity(9237): Error login in Google games services
10-15 05:27:20.216: E/ValidateServiceOp(10854): Using Google Play games services requires a metadata tag with the name "com.google.android.gms.games.APP_ID" in the application tag of the manifest for com.HechiGames.test
10-15 05:27:20.219: E/AndroidRuntime(9237): 	at com.google.android.gms.common.internal.zzf$zza.zzb(Unknown Source)
10-15 05:27:20.219: E/AndroidRuntime(9237): 	at com.google.android.gms.common.internal.zzf$zza.zzu(Unknown Source)
10-15 05:27:20.219: E/AndroidRuntime(9237): 	at com.google.android.gms.common.internal.zzf$zze.zzxH(Unknown Source)
10-15 05:27:20.219: E/AndroidRuntime(9237): 	at com.google.android.gms.common.internal.zzf$zzd.handleMessage(Unknown Source)
```

Looks like it's a problem with the generated XML:

`10-15 05:27:20.216: E/ValidateServiceOp(10854): Using Google Play games services requires a metadata tag with the name "com.google.android.gms.games.APP_ID" in the application tag of the manifest for com.HechiGames.test
`
But idk why, the manifest already have the com.google.android.gms.games.APP_ID metadata populated with App ID.

**Comment by Hondune** [comment]
After building the app, go into the temp > staging folder and open the android manifest that is in there. This will be the final merged manifest unity creates during build time. Make sure those lines are being merged into it correctly. If not, you can copy that final created manifest into the Plugins > Android folder in your project and then add those lines manually and try play services again.

**Comment by AsierBH** [comment]
@Hondune It works! , now the connection modal works correctly but the achivements UI doesn't appear.  It's a great advance for me since i got stuck on this a day ago, thank you.

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
