### ISSUE TITLE
Leaderboard Not opening 

### ISSUE THREAD

**Issue by acsudeep** [playgameservices/play-games-plugin-for-unity#2008]
I am able to sign in but not able to show Leaderboard in my multiple games made with Unity3D. Leaderboard loads and closes without showing anything instantly. 

I have tried almost all the possible solution such as fixing the SHA in developers console. I am using Latest version of Android SDK, Unity and the Plugins as well as of November 6.

My log is as follows:
```
11-06 14:28:16.972 22817-23048/? W/GamesServiceBroker: Client connected with SDK 11220000, Services 11745448, and Games 52250048
11-06 14:28:17.000 22817-4757/? W/GamesServiceBroker: Client connected with SDK 11411000, Services 11745448, and Games 52250048
11-06 14:28:17.061 1416-1432/? W/AppOps: Bad call: specified package com.google.android.play.games under uid 10551 but it is really 10117
                                         java.lang.RuntimeException: here
                                             at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1326)
                                             at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1028)
                                             at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
                                             at android.os.Binder.execTransact(Binder.java:453)
11-06 14:28:17.137 22817-4757/? W/GamesServiceBroker: Client connected with SDK 11411000, Services 11745448, and Games 52250048
11-06 14:28:17.151 25132-25132/? V/GamesNativeSDK: Play Games callback indicates connection.
11-06 14:28:17.163 25132-25760/? I/GamesNativeSDK: Successfully connected to Google Play.
11-06 14:28:17.225 22817-20174/? W/GamesServiceBroker: Client connected with SDK 11220000, Services 11745448, and Games 52250048
11-06 14:28:17.244 22817-4770/? W/GamesServiceBroker: Client connected with SDK 11411000, Services 11745448, and Games 52250048
11-06 14:28:17.289 648-674/? E/QCALOG: [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
11-06 14:28:17.289 648-674/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWiFi-PE] unknown deliver target [OS-Agent]
11-06 14:28:17.302 1416-4717/? W/AppOps: Bad call: specified package com.google.android.play.games under uid 10551 but it is really 10117
                                         java.lang.RuntimeException: here
                                             at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1326)
                                             at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1028)
                                             at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
                                             at android.os.Binder.execTransact(Binder.java:453)
11-06 14:28:17.356 684-864/? W/XTCC-5.1.0.13: [CS-RIL-LISTENER] timerCallback fired for ril update registering, re-register
11-06 14:28:17.356 648-674/? E/QCALOG: [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
11-06 14:28:17.367 22817-4770/? W/GamesServiceBroker: Client connected with SDK 11411000, Services 11745448, and Games 52250048
11-06 14:28:17.377 25132-25132/? V/GamesNativeSDK: Play Games callback indicates connection.
11-06 14:28:17.394 25132-25760/? I/GamesNativeSDK: Successfully connected to Google Play.
11-06 14:28:17.405 25401-25401/? W/Binder:25391_1: type=1400 audit(0.0:75167): avc: denied { search } for name="638" dev="proc" ino=12239099 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:zygote:s0 tclass=dir permissive=0
11-06 14:28:17.444 22817-32735/? W/GamesServiceBroker: Client connected with SDK 11220000, Services 11745448, and Games 52250048
11-06 14:28:17.467 22817-4757/? W/GamesServiceBroker: Client connected with SDK 11411000, Services 11745448, and Games 52250048
```

**Comment by Xandev** [comment]
You're not alone. I have exactly the same problem.

**Comment by acsudeep** [comment]
I have written one article with my experience on solving this problem. This may help you.

https://hellocoding.wordpress.com/2017/11/08/fixing-google-play-games-plugin-and-unity-integration-error-android/

**Comment by Xandev** [comment]
@acsudeep your article doesn't help me 😞
I have tried reinstalling GPGS, recreating keys, just everything that is mentioned in your article.

**Comment by acsudeep** [comment]
What is your errror message, can you post your log?

**Comment by Xandev** [comment]
@acsudeep sure, here you go: https://pastebin.com/r313mEiq
This is log from alpha version downloaded from google play.
I'm added to testers ofc.
In log you can see "Sukces auth" which is my Debug.LogError added when authorization is successfully called:

> Social.localUser.Authenticate(success =>
>         {
>             if (success)
>             {
>                 Debug.LogError("Sukces auth");
>                 Social.ShowLeaderboardUI();
>             }
>             else
>             {
>                 Debug.LogError("Fail auth");
>             }
>         });

I have also tried to call Social.ShowLeaderboardUI() as coroutine.

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
