### ISSUE TITLE
Infinite loop during the Google Play login screen

### ISSUE THREAD

**Issue by SebThePro** [playgameservices/play-games-plugin-for-unity#2042]
I've have been testing google play login for more than a week now and I am encountering a random loop problem during the Google Play authentification process. 

Everything seem to be setup correctly on the Google Play Console. I am able to login normallly most of the time.

But rarely (let say 1 time out of 50 on a fresh app install), i'm hitting this infinite loop during the authenticate process. The Unity app goes into background, I'm seeing this green rectangular UI for the google play login in the middle of the screen. After a second, the google play UI dissapear and reappear a moment later and then this loop restart again indifinitly. During the loop, I never receive any callback in the c# code of unity, no fail or success callback. No log inside unity app, stuck in the native part. To get out of this loop, the only way I find is to press the home button (the app goes into background) and then reopen the app (the app unpause) and then google play authentification process finally finish. From here, I am finally able to receive a succees callback with all the info I want (including IdToken and ServerAuthCode) to be able to send them to a backend.

Here the code I am using to initialize the plugin:

```cs
PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
			.RequestServerAuthCode(false)
			.RequestIdToken()
			.AddOauthScope("profile")
			.Build();

			PlayGamesPlatform.DebugLogEnabled = true;
			PlayGamesPlatform.InitializeInstance(config);
			PlayGamesPlatform.Activate();
```

And then when I want to login, I'm calling this code:
```cs

PlayGamesPlatform.Instance.Authenticate((success, error) =>
		{
			if (success)
			{
				//callback success
			}
			else
			{
				//callback failed
			}
		}, false);
```

This only happen on a brand new installation of my app. Else the sign in process is being silent (no green rectangular google play ui).

Anyone has any idea what could be the cause of that thing or encountered a similar issue. It is so rare and random and I don't have any  clue what could cause this thing. 

Thanks.

**Comment by SebThePro** [comment]
I was finally able to get a log when this random bug happen. Does anyone know what could sometime cause this issue... Thanks.

```cs
12-08 14:41:22.936: W/Unity(23656): !!! [Play Games Plugin DLL] 12/08/17 14:41:22 -05:00 WARNING: Creating new PlayGamesPlatform
12-08 14:41:22.936: W/Unity(23656):  
12-08 14:41:22.936: W/Unity(23656): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
12-08 14:41:22.941: I/Unity(23656):  [Play Games Plugin DLL] 12/08/17 14:41:22 -05:00 DEBUG: Activating PlayGamesPlatform.
12-08 14:41:22.941: I/Unity(23656):  
12-08 14:41:22.941: I/Unity(23656): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
12-08 14:41:22.946: I/Unity(23656):  [Play Games Plugin DLL] 12/08/17 14:41:22 -05:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
12-08 14:41:22.946: I/Unity(23656):  
12-08 14:41:22.946: I/Unity(23656): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
12-08 14:41:22.946: I/Unity(23656):  [Play Games Plugin DLL] 12/08/17 14:41:22 -05:00 DEBUG: Creating platform-specific Play Games client.
12-08 14:41:22.946: I/Unity(23656):  
12-08 14:41:22.946: I/Unity(23656): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
12-08 14:41:22.951: I/Unity(23656):  [Play Games Plugin DLL] 12/08/17 14:41:22 -05:00 DEBUG: Creating Android IPlayGamesClient Client
12-08 14:41:22.951: I/Unity(23656):  
12-08 14:41:22.951: I/Unity(23656): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
12-08 14:41:23.026: D/TokenFragment(23656): Creating fragment
12-08 14:41:23.031: D/TokenFragment(23656): onStart()
12-08 14:41:23.031: D/TokenFragment(23656): onResume called
12-08 14:41:23.031: D/TokenFragment(23656): Building client for: 44bea00 (a:true e:false i:true wc: 124356979064-u6ml1pnvlb5c2th8fmu5cksinuggn78h.apps.googleusercontent.com f: false)
12-08 14:41:23.096: I/Unity(23656): ---- [0] -- 29
12-08 14:41:23.096: I/Unity(23656):  
12-08 14:41:23.096: I/Unity(23656): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
12-08 14:41:23.151: W/PopupManager(23656): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
12-08 14:41:23.281: D/TokenFragment(23656): Done with processRequest, result is pending.
12-08 14:41:23.301: W/ResourcesManager(11845): getTopLevelResources: /data/app/com.google.android.play.games-1/base.apk / 1.0 running in com.google.android.gms rsrc of package null
12-08 14:41:23.301: W/ResourcesManager(11845): getTopLevelResources: /data/app/com.google.android.play.games-1/base.apk / 1.0 running in com.google.android.gms rsrc of package null
12-08 14:41:23.381: W/GamesServiceBroker(11845): Client connected with SDK 11200000, Services 11951438, and Games 52250038
12-08 14:41:23.421: W/ResourcesManager(11845): getTopLevelResources: /data/app/com.google.android.play.games-1/base.apk / 1.0 running in com.google.android.gms rsrc of package null
12-08 14:41:23.511: W/GamesServiceBroker(11845): Client connected with SDK 11411000, Services 11951438, and Games 52250038
12-08 14:41:23.541: W/GamesServiceBroker(11845): Client connected with SDK 11411000, Services 11951438, and Games 52250038
12-08 14:41:23.566: I/TokenFragment(23656): onConnected called
12-08 14:41:23.631: D/BatteryService(4139): !@BatteryListener : batteryPropertiesChanged!
12-08 14:41:23.631: D/BatteryService(4139): level:100, scale:100, status:5, health:2, present:true, voltage: 4240, temperature: 306, technology: Li-ion, AC powered:false, USB powered:true, POGO powered:false, Wireless powered:false, icon:17303558, invalid charger:0, maxChargingCurrent:0
12-08 14:41:23.631: D/BatteryService(4139): online:4, current avg:350, charge type:1, power sharing:false, high voltage charger:false, capacity:280000, batterySWSelfDischarging:false, current_now:350
12-08 14:41:23.636: D/BatteryService(4139): Sending ACTION_BATTERY_CHANGED.
12-08 14:41:23.636: I/MotionRecognitionService(4139): Plugged
12-08 14:41:23.636: D/MotionRecognitionService(4139):   cableConnection= 1
12-08 14:41:23.641: D/MotionRecognitionService(4139): setPowerConnected | current backoffstate  = 1024 , state =1024
12-08 14:41:23.641: D/MotionRecognitionService(4139): skip setTransmitPower. 
12-08 14:41:23.646: D/KeyguardUpdateMonitor(4559): received broadcast android.intent.action.BATTERY_CHANGED
12-08 14:41:23.646: I/PERF(4559): received broadcast android.intent.action.BATTERY_CHANGED
12-08 14:41:23.646: D/KeyguardUpdateMonitor(4559): handleBatteryUpdate
12-08 14:41:23.656: D/BatteryMeterView(4559): ACTION_BATTERY_CHANGED : level:100 status:5 health:2
12-08 14:41:23.661: D/BatteryMeterView(4559): ACTION_BATTERY_CHANGED : level:100 status:5 health:2
12-08 14:41:23.661: D/BatteryMeterView(4559): ACTION_BATTERY_CHANGED : level:100 status:5 health:2
12-08 14:41:23.751: I/Timeline(23656): Timeline: Activity_launch_request id:com.bhvr.wwmobile time:188128999
12-08 14:41:23.896: E/Parcel(4139): Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
12-08 14:41:23.896: E/Parcel(4139): java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
12-08 14:41:23.896: E/Parcel(4139): 	at java.lang.Class.classForName(Native Method)
12-08 14:41:23.896: E/Parcel(4139): 	at java.lang.Class.forName(Class.java:324)
12-08 14:41:23.896: E/Parcel(4139): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
12-08 14:41:23.896: E/Parcel(4139): 	at android.os.Parcel.readParcelable(Parcel.java:2358)
12-08 14:41:23.896: E/Parcel(4139): 	at android.os.Parcel.readValue(Parcel.java:2264)
12-08 14:41:23.896: E/Parcel(4139): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
12-08 14:41:23.896: E/Parcel(4139): 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
12-08 14:41:23.896: E/Parcel(4139): 	at android.os.BaseBundle.getString(BaseBundle.java:920)
12-08 14:41:23.896: E/Parcel(4139): 	at android.content.Intent.getStringExtra(Intent.java:6183)
12-08 14:41:23.896: E/Parcel(4139): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2695)
12-08 14:41:23.896: E/Parcel(4139): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2157)
12-08 14:41:23.896: E/Parcel(4139): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6345)
12-08 14:41:23.896: E/Parcel(4139): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6123)
12-08 14:41:23.896: E/Parcel(4139): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170)
12-08 14:41:23.896: E/Parcel(4139): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3995)
12-08 14:41:23.896: E/Parcel(4139): 	at android.os.Binder.execTransact(Binder.java:453)
12-08 14:41:23.896: E/Parcel(4139): Caused by: java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
12-08 14:41:23.896: E/Parcel(4139): 	at java.lang.Class.classForName(Native Method)
12-08 14:41:23.896: E/Parcel(4139): 	at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
12-08 14:41:23.896: E/Parcel(4139): 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
12-08 14:41:23.896: E/Parcel(4139): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
12-08 14:41:23.896: E/Parcel(4139): 	... 16 more
12-08 14:41:23.896: E/Parcel(4139): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
12-08 14:41:23.901: W/ResourcesManager(4139): getTopLevelResources: /data/app/com.bhvr.wwmobile-1/base.apk / 1.0 running in null rsrc of package null
12-08 14:41:23.931: D/CustomFrequencyManagerService(4139): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1800000  uid : 1000  pid : 4139  pkgName : ACTIVITY_RESUME_BOOSTER@7
12-08 14:41:23.936: D/ActivityManager(4139): mDVFSHelper.acquire()
12-08 14:41:23.941: V/WindowManager(4139): addAppToken: AppWindowToken{d1fa84 token=Token{1aaa897 ActivityRecord{4adc716 u0 com.bhvr.wwmobile/com.google.android.gms.auth.api.signin.internal.SignInHubActivity t171}}} to stack=1 task=171 at 1
12-08 14:41:23.946: D/InputDispatcher(4139): Focused application set to: xxxx
12-08 14:41:23.951: D/InputDispatcher(4139): Focus left window: 23656
12-08 14:41:23.956: D/PointerIcon(4139): setMouseIconStyle1 pointerType: 1001 iconType:101 flag:0 pid:4139 uid:1000
12-08 14:41:23.956: D/PointerIcon(4139): setMouseCustomIcon IconType is same.101
12-08 14:41:23.956: D/PointerIcon(4139): setHoveringSpenIconStyle1 pointerType: 10001 iconType:1 flag:0 pid:4139 uid:1000
12-08 14:41:23.956: D/PointerIcon(4139): setHoveringSpenCustomIcon IconType is same.1
12-08 14:41:24.086: I/System.out(23656): (HTTPLog)-Static: isSBSettingEnabled false
12-08 14:41:24.086: I/System.out(23656): (HTTPLog)-Static: isSBSettingEnabled false
12-08 14:41:24.111: I/Unity(23656): BHVR Logger - Pausing, device uptime synching needed on resume...
12-08 14:41:24.111: I/Unity(23656):  
12-08 14:41:24.111: I/Unity(23656): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
12-08 14:41:24.116: V/Adjust(23656): Foreground timer suspended with 38.3 seconds left
12-08 14:41:24.116: V/Adjust(23656): Subsession end
12-08 14:41:24.121: D/Adjust(23656): Wrote Activity state: ec:0 sc:1 ssc:1 sl:21.7 ts:21.7 la:11:12:13 uuid:c9487ce8-1180-4132-9fe6-3835ac3b691e
12-08 14:41:24.151: I/Sensors(4139): Acc old sensor_state 1, new sensor_state : 0 en : 0
12-08 14:41:24.176: V/MARsPolicyManager(4139): updatePackagesScore PackageInfo name -- com.bhvr.wwmobile
12-08 14:41:24.206: W/System.err(26713): stat failed: ENOENT (No such file or directory) : /storage/emulated/0/Android/data/com.bhvr.wwmobile/files/Unity/107ef2d5-ca7b-408f-956e-8d8c471cc85b/Analytics/ArchivedEvents/151276206200003.4e629fc1_tmp/g
12-08 14:41:24.226: W/ResourcesManager(23656): getTopLevelResources: /data/app/com.bhvr.wwmobile-1/base.apk / 1.0 running in com.bhvr.wwmobile rsrc of package null
12-08 14:41:24.256: E/Parcel(4139): Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
12-08 14:41:24.256: E/Parcel(4139): java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
12-08 14:41:24.256: E/Parcel(4139): 	at java.lang.Class.classForName(Native Method)
12-08 14:41:24.256: E/Parcel(4139): 	at java.lang.Class.forName(Class.java:324)
12-08 14:41:24.256: E/Parcel(4139): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
12-08 14:41:24.256: E/Parcel(4139): 	at android.os.Parcel.readParcelable(Parcel.java:2358)
12-08 14:41:24.256: E/Parcel(4139): 	at android.os.Parcel.readValue(Parcel.java:2264)
12-08 14:41:24.256: E/Parcel(4139): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
12-08 14:41:24.256: E/Parcel(4139): 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
12-08 14:41:24.256: E/Parcel(4139): 	at android.os.BaseBundle.getString(BaseBundle.java:920)
12-08 14:41:24.256: E/Parcel(4139): 	at android.content.Intent.getStringExtra(Intent.java:6183)
12-08 14:41:24.256: E/Parcel(4139): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2695)
12-08 14:41:24.256: E/Parcel(4139): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2157)
12-08 14:41:24.256: E/Parcel(4139): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6345)
12-08 14:41:24.256: E/Parcel(4139): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6123)
12-08 14:41:24.256: E/Parcel(4139): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:170)
12-08 14:41:24.256: E/Parcel(4139): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3995)
12-08 14:41:24.256: E/Parcel(4139): 	at android.os.Binder.execTransact(Binder.java:453)
12-08 14:41:24.256: E/Parcel(4139): Caused by: java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
12-08 14:41:24.256: E/Parcel(4139): 	at java.lang.Class.classForName(Native Method)
12-08 14:41:24.256: E/Parcel(4139): 	at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
12-08 14:41:24.256: E/Parcel(4139): 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
12-08 14:41:24.256: E/Parcel(4139): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
12-08 14:41:24.256: E/Parcel(4139): 	... 16 more
12-08 14:41:24.256: E/Parcel(4139): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
12-08 14:41:24.256: W/ResourcesManager(4139): getTopLevelResources: /data/app/com.google.android.gms-2/base.apk / 1.0 running in null rsrc of package null
12-08 14:41:24.261: I/APM::AudioPolicyManager(3682): stopOutput() output 2, stream 3, session 1984
12-08 14:41:24.296: D/CustomFrequencyManagerService(4139): releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1800000  uid : 1000  pid : 4139  tag : ACTIVITY_RESUME_BOOSTER@7
12-08 14:41:24.296: D/CustomFrequencyManagerService(4139): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1800000  uid : 1000  pid : 4139  pkgName : ACTIVITY_RESUME_BOOSTER@7
12-08 14:41:24.301: D/ActivityManager(4139): mDVFSHelper.acquire()
12-08 14:41:24.301: V/WindowManager(4139): addAppToken: AppWindowToken{1e73733 token=Token{a373ea2 ActivityRecord{9d4126d u0 
```

**Comment by JimmyDeemo** [comment]
I too have seen this unmarshalling error and unfortunately don't have an explaination for it right now.

**Comment by spixy** [comment]
I also have this problem. What is interesting:
- on Galaxy J7 I have this error and sign-in is not working
- on Galaxy S5 I have this error but sign-in is working
- on other phones I dont have this error and sign-in is working

**Comment by SebThePro** [comment]
This is really interesting, I am doing a lot's of tests on a Galaxy S5 and I have the exact same behavior as you describe. Didn't test on Galaxy J7... So this seem to be really device specific. Did you find any fixes or workaround? Thanks for the info!

**Comment by doyongid** [comment]
Did you solve this? I have the same problem.

**Comment by Antik22** [comment]
Having the same problem now, going to add **"com.google.android.gms.auth.api.signin.internal"** to **progurd** file:
`-keep class com.google.android.gms.auth.** { *; }`

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
