### ISSUE TITLE
Gradle failed to fetch dependencies.

### ISSUE THREAD

**Issue by hellolw** [playgameservices/play-games-plugin-for-unity#2048]
Environment: 
WIN7+Unity5.6.4f1+GooglePlayGamesPlugin-0.9.42.unitypackage

Description: 
Just import GooglePlayGamesPlugin to my unity project, such issue encoutered. 
If I build a APK file after imported GooglePlayGamesPlugin, then unity tell me "Failed to re-package resources".
On another laptop which installed WIN10, I import GooglePlayGamesPlugin as what I did on thelaptop which installed WIN7, there is no error! And when I build APK, which is successful. Check the path project\Assets\Plugins\Android, find there are many .aar files missed on laptop installed WIN7.

Error info as following:

Gradle failed to fetch dependencies.

Failed to run 'D:\u3d_workplace\Texas\Temp\PlayServicesResolverGradle\gradlew.bat -b "D:\u3d_workplace\Texas\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" --no-daemon "-PANDROID_HOME=D:/develop/ECLIPSE/adt-bundle-windows-x86-20140702/sdk" "-PTARGET_DIR=D:\u3d_workplace\Texas\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///D:/u3d_workplace/Texas/Assets/GooglePlayGames/Editor/m2repository;https://maven.google.com" "-PPACKAGES_TO_COPY=com.android.support:support-v4:25.3.1;com.android.support:appcompat-v7:25.3.1;com.android.support:cardview-v7:25.3.1;com.android.support:customtabs:25.3.1;com.google.games:gpgs-plugin-support:0+;com.google.android.gms:play-services-games:10+;com.google.android.gms:play-services-nearby:10+;com.google.android.gms:play-services-auth:10+"'
stdout:
Unzipping C:\Users\Think\.gradle\wrapper\dists\gradle-4.2.1-bin\dajvke9o8kmaxbu0kc5gcgeju\gradle-4.2.1-bin.zip to C:\Users\Think\.gradle\wrapper\dists\gradle-4.2.1-bin\dajvke9o8kmaxbu0kc5gcgeju

stderr:
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
	at org.gradle.wrapper.Install.unzip(Install.java:215)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:75)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

exit code: 1

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__1F(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__28()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by OpenLevel** [comment]
You should try 0.9.39.
I managed to build with Gradle with v0.9.39.
My environment: Win8.1 + Unity2017.2.0.f3 + GooglePlayGamesPlugin-0.9.39.unitypackage
Good luck.

**Comment by hellolw** [comment]
Hello, Where can I get the v0.9.39? @OpenLevel

**Comment by OpenLevel** [comment]
@hellolw 
You can get the v0.9.39 from here:
https://github.com/playgameservices/play-games-plugin-for-unity/raw/0a84170ab344f0ce7e778e11a3fee4d3cbc5b45c/current-build/GooglePlayGamesPlugin-0.9.39.unitypackage

I spend my Sunday to solve this problem. Good luck.

**Comment by OpenLevel** [comment]
If you are using Proguard, add these line:
<pre><code># GPGS
-keep class com.google.android.gms.** { *; }
-keep interface com.google.android.gms.** { *; }
</code></pre>

**Comment by Sibz23** [comment]
@OpenLevel  thanks alot. A series of errors and atlast I get it working. V 0.9.39 works perfectly.

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
