### ISSUE TITLE
Crash during App start: NoClassDefFoundError

### ISSUE THREAD

**Issue by MoinTom** [playgameservices/play-games-plugin-for-unity#2058]
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/core/internal/FastSafeIterableMap;
                                                       at android.arch.lifecycle.LifecycleRegistry.<init>(LifecycleRegistry.java:59)
                                                       at android.support.v4.app.SupportActivity.<init>(SupportActivity.java:47)
                                                       at android.support.v4.app.BaseFragmentActivityApi14.<init>(BaseFragmentActivityApi14.java:28)
                                                       at android.support.v4.app.BaseFragmentActivityApi16.<init>(BaseFragmentActivityApi16.java:34)
                                                       at android.support.v4.app.FragmentActivity.<init>(FragmentActivity.java:67)
                                                       at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.<init>(Unknown Source:0)
                                                       at java.lang.Class.newInstance(Native Method)
                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1173)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by richardelms** [comment]
Hi guys, did you get anywhere with this? i'm also finding this issue with unity gradle

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
