### ISSUE TITLE
Package not importing "Plugins" folder, Gradle failed to fetch dependencies and Resolution Failed when importing

### ISSUE THREAD

**Issue by RenalPraba** [playgameservices/play-games-plugin-for-unity#2194]
I have no other plugin installed, It happen whenever I try importing google play games plugin, an error message is showing

_System.IO.DirectoryNotFoundException: Directory 'Assets/Plugins/Android' not found.
  at System.IO.Directory.GetFileSystemEntries (System.String path, System.String searchPattern, FileAttributes mask, FileAttributes attrs) [0x000f7] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/Directory.cs:514 
  at System.IO.Directory.GetDirectories (System.String path, System.String searchPattern) [0x00000] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/Directory.cs:275 
  at System.IO.Directory.GetDirectories (System.String path) [0x00000] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/Directory.cs:270 
  at GooglePlayGames.Editor.GPGSUpgrader.CleanDuplicates (System.String root) [0x00002] in /Users/arbregame/Documents/Work/Projects/Jump!/Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:124 
  at GooglePlayGames.Editor.GPGSUpgrader..cctor () [0x0013d] in /Users/arbregame/Documents/Work/Projects/Jump!/Assets/GooglePlayGames/Editor/GPGSUpgrader.cs:92 
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()_

All the package contents are imported, except the Plugins folder, only give me Android folder without any file in it

Then after done importing package, two messages are showing

The first one is

Gradle failed to fetch dependencies.

Failed to run '/Users/arbregame/Documents/Work/Projects/Jump!/Temp/PlayServicesResolverGradle/gradlew -b "/Users/arbregame/Documents/Work/Projects/Jump!/Temp/PlayServicesResolverGradle/PlayServicesResolver.scripts.download_artifacts.gradle" --no-daemon "-PANDROID_HOME=/Users/arbregame/Library/Android/sdk" "-PTARGET_DIR=/Users/arbregame/Documents/Work/Projects/Jump!/Assets/Plugins/Android" "-PMAVEN_REPOS=file:////Users/arbregame/Documents/Work/Projects/Jump!/Assets/GooglePlayGames/Editor/m2repository" "-PPACKAGES_TO_COPY=com.google.games:gpgs-plugin-support:0.9.50"'
stdout:

stderr:
Exception in thread "main" java.lang.RuntimeException: Could not determine wrapper version.
	at org.gradle.wrapper.GradleWrapperMain.wrapperVersion(GradleWrapperMain.java:111)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: No build receipt resource found.
	at org.gradle.wrapper.GradleWrapperMain.wrapperVersion(GradleWrapperMain.java:97)
	... 1 more

exit code: 1

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__1F(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__28()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

And the second error message

Resolution failed

Failed to fetch the following dependencies:
com.google.games:gpgs-plugin-support:0.9.50

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.ResolverVer1_1:LogMissingDependenciesError(List`1)
GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey18:<>m__26(List`1)
GooglePlayServices.<GradleResolution>c__AnonStorey14:<>m__1F(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey15:<>m__28()
GooglePlayServices.PlayServicesResolver:PumpUpdateQueue()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

I can't resolve or force resolve it, reimporting same or previous package version give me the same results.

I'm using Unity 5.6.5,
Play Services Version 0.9.50 / 0.9.42 
JDK 1.8.0_172,
SDK Platforms Android API 27,
SDK Build-Tools 26.0.2
SDK Platform-Tools 27.0.1
SDK Tools 26.1.1

**Comment by RenalPraba** [comment]
Downgraded it to version 0.9.39 seems to be working.
