### ISSUE TITLE
Sign in failed, 402 for v1/players/me?language=es-MX, "Game not licensed to player"

### ISSUE THREAD

**Issue by tenpn** [playgameservices/play-games-plugin-for-unity#2281]
Unity 2017.4.5, PGP 0.9.50.

We're a game in soft launch in several countries, with a published play games project on the play store. Internally we can sign in to google play games fine, and we know there are players in the wild who can sign in. 

When the internal google featuring reviewers played our game, they couldn't sign in to google play games. We have a full log from them, and these lines seem most suspicious: 

    08-28 13:48:43.444: W/GamesServiceBroker(29394): Client connected with SDK 13589000, Services 12874032, and Games 65510040
    08-28 13:48:43.701: I/SignInActivity(14186): Transition from 7 to 8
    08-28 13:48:43.713: W/GamesServiceBroker(29394): Client connected with SDK 13589000, Services 12874032, and Games 65510040
    08-28 13:48:44.304: E/Volley(29394): [1248] BasicNetwork.performRequest: Unexpected response code 402 for https://www.googleapis.com/games/v1/players/me?language=es-MX
    08-28 13:48:44.363: E/SignInIntentService(29394): Game 1032530929579 not licensed to player.
    08-28 13:48:44.363: E/SignInIntentService(29394): iey
    08-28 13:48:44.363: E/SignInIntentService(29394): 	at hwz.a(:com.google.android.play.games@65510040@5.11.6551 (209213077.209213077-000400):54)
    08-28 13:48:44.363: E/SignInIntentService(29394): 	at ibj.a(:com.google.android.play.games@65510040@5.11.6551 (209213077.209213077-000400):4)
    08-28 13:48:44.363: E/SignInIntentService(29394): 	at gtx.d(:com.google.android.play.games@65510040@5.11.6551 (209213077.209213077-000400):17)
    08-28 13:48:44.363: E/SignInIntentService(29394): 	at gtx.a(:com.google.android.play.games@65510040@5.11.6551 (209213077.209213077-000400):407)
    08-28 13:48:44.363: E/SignInIntentService(29394): 	at gsa.d(:com.google.android.play.games@65510040@5.11.6551 (209213077.209213077-000400):73)
    08-28 13:48:44.363: E/SignInIntentService(29394): 	at igt.a(:com.google.android.play.games@65510040@5.11.6551 (209213077.209213077-000400):13)
    08-28 13:48:44.363: E/SignInIntentService(29394): 	at igv.a(:com.google.android.play.games@65510040@5.11.6551 (209213077.209213077-000400):5)
    08-28 13:48:44.363: E/SignInIntentService(29394): 	at faz.run(:com.google.android.play.games@65510040@5.11.6551 (209213077.209213077-000400):1)
    08-28 13:48:44.363: E/SignInIntentService(29394): 	at fvn.run(:com.google.android.play.games@65510040@5.11.6551 (209213077.209213077-000400):28)
    08-28 13:48:44.363: E/SignInIntentService(29394): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    08-28 13:48:44.363: E/SignInIntentService(29394): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    08-28 13:48:44.363: E/SignInIntentService(29394): 	at psy.run(Unknown Source:7)
    08-28 13:48:44.363: E/SignInIntentService(29394): 	at java.lang.Thread.run(Thread.java:764)
    08-28 13:48:44.365: I/SignInActivity(14186): Transition from 8 to 11
    08-28 13:48:44.365: W/SignInActivity(14186): onSignInFailed()...

You see there's a 402 and a licensing error in there. They claim to have installed via google play, but I guess google's reviewers have their own systems for getting around the soft launch region restrictions? 

I'm interested in how to fix their issue, short of adding all their reviewer emails to our test account list, or indeed what more info I could ask from them. As I said, other in-the-wild users are signing in fine.

**Comment by tenpn** [comment]
...turns out the googlers _were_ sideloading the app, so the license check was correct. now they installed properly from Play and it all works. sorry for the noise!
