### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf"

### ISSUE THREAD

**Issue by Vah94** [playgameservices/play-games-plugin-for-unity#2282]
Unity3D project.
There are...
GooglePlayGamesPlugin-0.9.50
Appodeal-Unity-2.8.45-130818-all
FirebaseAuth
FirebaseDatabase
FirebaseRemoteConfig
Crashlytics
devtodev
Fabric

08-29 12:20:44.568 30897-30897/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rhinogames.gnomes, PID: 30897
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
        at com.google.android.gms.auth.api.Auth.<clinit>(Unknown Source:0)
        at com.google.games.bridge.TokenFragment.buildClient(TokenFragment.java:382)
        at com.google.games.bridge.TokenFragment.processRequest(TokenFragment.java:279)
        at com.google.games.bridge.TokenFragment.onResume(TokenFragment.java:506)
        at android.app.Fragment.performResume(Fragment.java:2657)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1319)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1549)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1611)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2154)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2055)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf" on path: DexPathList[[
     dex file "/data/user/0/com.rhinogames.gnomes/app_working/vungle.dex", 
     dex file "/data/user/0/com.rhinogames.gnomes/app_working/unity_ads.dex", 
     dex file "/data/user/0/com.rhinogames.gnomes/app_working/tapjoy.dex", 
     dex file "/data/user/0/com.rhinogames.gnomes/app_working/mopub.dex", 
     dex file "/data/user/0/com.rhinogames.gnomes/app_working/mailru.dex", 
     dex file "/data/user/0/com.rhinogames.gnomes/app_working/ironsource.dex", 
     dex file "/data/user/0/com.rhinogames.gnomes/app_working/facebook.dex", 
     dex file "/data/user/0/com.rhinogames.gnomes/app_working/chartboost.dex", 
     dex file "/data/user/0/com.rhinogames.gnomes/app_working/applovin.dex", 
     dex file "/data/user/0/com.rhinogames.gnomes/app_working/amazon_ads.dex", 
     zip file "/data/app/com.rhinogames.gnomes-xXVgFXdt_iQrhtmTfaigiA==/base.apk"],
     nativeLibraryDirectories=[/data/app/com.rhinogames.gnomes-xXVgFXdt_iQrhtmTfaigiA==/lib/arm, /data/app/com.rhinogames.gnomes-xXVgFXdt_iQrhtmTfaigiA==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.auth.api.Auth.<clinit>(Unknown Source:0) 
        at com.google.games.bridge.TokenFragment.buildClient(TokenFragment.java:382) 
        at com.google.games.bridge.TokenFragment.processRequest(TokenFragment.java:279) 
        at com.google.games.bridge.TokenFragment.onResume(TokenFragment.java:506) 
        at android.app.Fragment.performResume(Fragment.java:2657) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1319) 
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1549) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1611) 
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210) 
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2154) 
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2055) 
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:718) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 

Anyone know how it solve?

**Comment by Vah94** [comment]
![image](https://user-images.githubusercontent.com/42799443/44775642-2ab15700-ab87-11e8-843f-fab51ee7cf03.png)
![image](https://user-images.githubusercontent.com/42799443/44775667-39980980-ab87-11e8-8ba8-388229f7e2a1.png)

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
