### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.api.zzd"

### ISSUE THREAD

**Issue by FancisLuo** [playgameservices/play-games-plugin-for-unity#2304]
![image](https://user-images.githubusercontent.com/10607925/45672105-e8fa4780-bb59-11e8-8507-ab1df5e3922e.png)

Unity 2018.1.6f1 with  gpgs-plugin-support-0.9.50 version.
it's crashed when start the game with error "Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/zzd;"
 
detailed information:
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/zzd;
                      at com.google.android.gms.auth.api.Auth.<clinit>(Unknown Source)
                      at com.google.games.bridge.TokenFragment.buildClient(TokenFragment.java:382)
                      at com.google.games.bridge.TokenFragment.processRequest(TokenFragment.java:279)
                      at com.google.games.bridge.TokenFragment.onResume(TokenFragment.java:506)
                      at android.app.Fragment.performResume(Fragment.java:2263)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1008)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
                      at android.app.BackStackRecord.run(BackStackRecord.java:806)
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
                      at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5554)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:935)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.api.zzd" on path: DexPathList[[zip file "/data/app/com.tcminplay.goalonandroid-2/base.apk", zip file "/data/app/com.tcminplay.goalonandroid-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.tcminplay.goalonandroid-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.tcminplay.goalonandroid-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.tcminplay.goalonandroid-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.tcminplay.goalonandroid-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.tcminplay.goalonandroid-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.tcminplay.goalonandroid-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.tcminplay.goalonandroid-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.tcminplay.goalonandroid-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.tcminplay.goalonandroid-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.tcminplay.goalonandroid-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.tcminplay.goalonandroid-2/lib/arm, /data/app/com.tcminplay.goalonandroid-2/base.apk!/lib/armeabi-v7a, /data/app/com.tcminplay.goalonandroid-2/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.tcminplay.goalonandroid-2/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.tcminplay.goalonandroid-2/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.tcminplay.goalonandroid-2/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.tcminplay.goalonandroid-2/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.tcminplay.goalonandroid-2/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.tcminplay.goalonandroid-2/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.tcminplay.goalonandroid-2/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.tcminplay.goalonandroid-2/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.tcminplay.goalonandroid-2/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.tcminplay.goalonandroid-2/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                      at com.google.android.gms.auth.api.Auth.<clinit>(Unknown Source) 
                      at com.google.games.bridge.TokenFragment.buildClient(TokenFragment.java:382) 
                      at com.google.games.bridge.TokenFragment.processRequest(TokenFragment.java:279) 
                      at com.google.games.bridge.TokenFragment.onResume(TokenFragment.java:506) 
                      at android.app.Fragment.performResume(Fragment.java:2263) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1008) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148) 
                      at android.app.BackStackRecord.run(BackStackRecord.java:806) 
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535) 
                      at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482) 
                      at android.os.Handler.handleCallback(Handler.java:739) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5554) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:935) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726) 
                  	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.auth.api.zzd
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                  		at java.lan

it's strange for me since the said "zzd" is exist in com.google.android.gms.auth.api.signin.internal.zzd.

Could anyone do me a favor?

**Comment by FancisLuo** [comment]
the issue is resolved. The reason is that the project lack of auth-base package
