### ISSUE TITLE
game crashes after play around 30 minutes to 35 minutes

### ISSUE THREAD

**Issue by boyzone09x** [playgameservices/play-games-plugin-for-unity#2329]
Hi everyone. i have a problem with my game. game crashes after play about 30minutes to 35 minutes in internet mode. it is not crash in no internet mode. i don't find any problem causes of crash.
i used log cat to debug. it crashed after call packageName com.google.android.gms
this is log cat : https://paste.ofcode.org/patEdGjTqJbcvrmhKDhmDd
Please help me. Thanks a lot !

**Comment by olehkuznetsov** [comment]
Can you add the crash exception from the logcat, please? It seems that part is missing.

**Comment by boyzone09x** [comment]
[log.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/2518459/log.txt)

**Comment by boyzone09x** [comment]
> Can you add the crash exception from the logcat, please? It seems that part is missing.

Thanks for your reply, i reup logcat. Please help me

**Comment by boyzone09x** [comment]
> Try to disable proguard for you build and check if it continues to crash, please.

thanks you, i will try but can you show me what causes of crashes ?

**Comment by boyzone09x** [comment]
i am using unity 5.6.6. how to disable proguard ?
sorry for asking many question guys.

**Comment by olehkuznetsov** [comment]
Those log parts could be related to crash:
I/ActivityManager(  956): Start proc 2860:com.cleanmaster.sdk:bg.clean/u0a45 for service com.cleanmaster.sdk/com.cleanmaster.CleanService
...
W/ActivityManager(  956): Unable to start service Intent { cmp=com.google.android.gms/.drive.api.ApiService } U=0: not found
...
E/CRASH   (31970): 	#00  pc 00002856  /system/lib/libnativehelper.so (jniGetFDFromFileDescriptor+93)
E/CRASH   (31970): 	#01  pc 0000a707  /system/lib/libjavacrypto.so
E/CRASH   (31970): 	#02  pc 0000ee6b  /system/lib/libjavacrypto.so
E/CRASH   (31970): 	#03  pc 0000f1e9  /system/lib/libjavacrypto.so
E/CRASH   (31970): 	#04  pc 002fa6e3  /data/dalvik-cache/arm/system@framework@boot.oat
F/mono    (31970): * Assertion: should not be reached at mini.c:2215

Can you try to remove/disable 'Cheetah Mobile CleanMaster SDK' and try without it, please.

**Comment by boyzone09x** [comment]
> Those log parts could be related to crash:
> I/ActivityManager( 956): Start proc 2860:com.cleanmaster.sdk:bg.clean/u0a45 for service com.cleanmaster.sdk/com.cleanmaster.CleanService
> ...
> W/ActivityManager( 956): Unable to start service Intent { cmp=com.google.android.gms/.drive.api.ApiService } U=0: not found
> ...
> E/CRASH (31970): #00 pc 00002856 /system/lib/libnativehelper.so (jniGetFDFromFileDescriptor+93)
> E/CRASH (31970): #1 pc 0000a707 /system/lib/libjavacrypto.so
> E/CRASH (31970): #2 pc 0000ee6b /system/lib/libjavacrypto.so
> E/CRASH (31970): #3 pc 0000f1e9 /system/lib/libjavacrypto.so
> E/CRASH (31970): #4 pc 002fa6e3 /data/dalvik-cache/arm/system@[framework@boot.oat](mailto:framework@boot.oat)
> F/mono (31970): * Assertion: should not be reached at mini.c:2215
> 
> Can you try to remove/disable 'Cheetah Mobile CleanMaster SDK' and try without it, please.

Yes. sure but i think it is not problem because it crashes on another device without cleanmaster application install

**Comment by olehkuznetsov** [comment]
Can you check if you have the same crash lines on another device too, please?

**Comment by boyzone09x** [comment]
> Can you check if you have the same crash lines on another device too, please?

Yes. Sure, the game crashes on another devices without Clean Master application install.

**Comment by MaxTyT** [comment]
I have the same bug. I use plugin v.0.9.61 with Unity 2017.4.30, gradle.
When I start game and wait 10-20 minutes game crashes, logs:
`10-28 20:17:02.209   536   536 V GamesNativeSDK: Play Games callback indicates disconnection.
10-28 20:17:10.618   536  1055 W GmsClient: IGmsServiceBroker.getService failed
10-28 20:17:10.618   536  1055 W GmsClient: android.os.DeadObjectException
10-28 20:17:10.618   536  1055 W GmsClient: 	at android.os.BinderProxy.transact(Native Method)
10-28 20:17:10.618   536  1055 W GmsClient: 	at com.google.android.gms.common.internal.IGmsServiceBroker$Stub$zza.getService(Unknown Source)
10-28 20:17:10.618   536  1055 W GmsClient: 	at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(Unknown Source)
10-28 20:17:10.618   536  1055 W GmsClient: 	at com.google.android.gms.common.api.internal.zaaq.zaan(Unknown Source)
10-28 20:17:10.618   536  1055 W GmsClient: 	at com.google.android.gms.common.api.internal.zaau.run(Unknown Source)
10-28 20:17:10.618   536  1055 W GmsClient: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
10-28 20:17:10.618   536  1055 W GmsClient: 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
10-28 20:17:10.618   536  1055 W GmsClient: 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
10-28 20:17:10.618   536  1055 W GmsClient: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
10-28 20:17:10.618   536  1055 W GmsClient: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
10-28 20:17:10.618   536  1055 W GmsClient: 	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
10-28 20:17:10.618   536  1055 W GmsClient: 	at java.lang.Thread.run(Thread.java:856)
10-28 20:17:10.618   536   536 V GamesNativeSDK: Play Games callback indicates connection failure.
10-28 20:17:10.618   536   536 E GamesNativeSDK: Unexpected response: connection failed.
10-28 20:17:26.595   536   823 F mono    : * Assertion: should not be reached at mini.c:2215`

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
