### ISSUE TITLE
FATAL EXCEPTION : java.lang.NoClassDefFoundError v0.9.58

### ISSUE THREAD

**Issue by UnityKR** [playgameservices/play-games-plugin-for-unity#2420]
Unity : 2018.3.2f1
GPGS : v0.9.58
AdMob Plugin : v3.15.1
Build System : Gradle
Managed Stripping Level : Disabled

Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/AuthProxy;
        at com.google.android.gms.auth.api.Auth.<clinit>(Unknown Source)
        at com.google.android.gms.auth.api.signin.GoogleSignInClient.<init>(Unknown Source)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getClient(Unknown Source)
        at com.google.games.bridge.TokenFragment.buildClient(TokenFragment.java:342)
        at com.google.games.bridge.TokenFragment.processRequest(TokenFragment.java:287)
        at com.google.games.bridge.TokenFragment.onResume(TokenFragment.java:416)
        at android.app.Fragment.performResume(Fragment.java:2329)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1023)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1163)
        at android.app.BackStackRecord.run(BackStackRecord.java:793)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1552)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:487)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by UnityKR** [comment]
Caused by Jar Resolver...
Solved by Force Resolve..
