### ISSUE TITLE
[bug] Google Auth crash app from few days ago

### ISSUE THREAD

**Issue by green4you** [playgameservices/play-games-plugin-for-unity#2440]
Google Auth works well.
but It crashes the app from a few days ago.
I didn't change anything, it is an internal test version on google play.

here is versions
Unity 2018.2.10f1 (64-bit)
GooglePlayGamesPlugin-0.9.50
play-services-resolver-1.2.95.0

build with gradle

this is logcat error
02-03 04:55:15.397 5280-18186/? E/ValidateServiceOp: Application ID ( 2631365469) must be a numeric value. Please verify that your manifest refers to the correct project ID.

02-03 04:16:30.547 11893-11930/? W/Unity: !!! [Play Games Plugin DLL] 02/03/19 4:16:30 +09:00 WARNING: Creating new PlayGamesPlatform
     
02-03 04:16:30.547 11893-11930/? I/Unity:  [Play Games Plugin DLL] 02/03/19 4:16:30 +09:00 DEBUG: Creating platform-specific Play Games client.
     
 [Play Games Plugin DLL] 02/03/19 4:16:30 +09:00 DEBUG: Creating Android IPlayGamesClient Client
     
02-03 04:16:30.587 11893-11930/? I/Unity: ---- [0] -- 978321433

  Caused by: java.lang.IllegalStateException: A fatal developer error has occurred. Class name: zzf. Start service action: com.google.android.gms.games.service.START. Service Descriptor: com.google.android.gms.games.internal.IGamesService. 
        at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(Unknown Source)
        at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(Unknown Source)
        at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at com.google.android.gms.internal.common.zze.dispatchMessage(Unknown Source)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5094)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by green4you** [comment]
self solution

fine all "com.google.android.gms.games.APP_ID" in project

remove empty space in "android:value"

**Comment by green4you** [comment]
> Update to the latest version (0.9.60).

I don't want to update it because it probably has another bug.

**Comment by Noah1911** [comment]
Everything is somehow bugged. However check #2013 if you want possible solution for this.

**Comment by ishnu47** [comment]
Hello,
I still got these crashes on some Android 10 devices (100% from Crashlytics).
I'm using GPS version 0.10.06, Unity 2018.4.14f1.
Any updates for Android 10 then?

**Comment by MartinRouterKing64** [comment]
I got the same issue...

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
