### ISSUE TITLE
Crash during sign-in failure at TokenFragment line 258

### ISSUE THREAD

**Issue by cobbpg** [playgameservices/play-games-plugin-for-unity#2444]
We're seeing crash reports across all kinds of devices and Android versions with the following stacktrace:

```java
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent com.google.android.gms.auth.api.signin.GoogleSignInClient.getSignInIntent()' on a null object reference
       at com.google.games.bridge.TokenFragment$2.onFailure(TokenFragment.java:258)
       at com.google.android.gms.tasks.zzl.run(Unknown Source:4)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:186)
       at android.app.ActivityThread.main(ActivityThread.java:6509)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
```

It seems that `mGoogleSignInClient` is somehow null at the time the failure callback is invoked.

**Comment by olehkuznetsov** [comment]
Which plugin version do you use?

**Comment by cobbpg** [comment]
It happens at least with 0.9.58 and 0.9.60. For now we went back to 0.9.53, which is the last version before this part was refactored, and it doesn't crash.

**Comment by olehkuznetsov** [comment]
Should be fixed in v0.9.61

**Comment by cobbpg** [comment]
I can confirm that this fixed the issue for all our users.

**Comment by olehkuznetsov** [comment]
Thanks for confirmation.
