### ISSUE TITLE
When start application its not pop up google play game services.

### ISSUE THREAD

**Issue by onurigdi** [playgameservices/play-games-plugin-for-unity#2445]
W/Unity   (28372): *** [Play Games Plugin DLL] 02/07/19 11:56:53 +02:00 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment

i got this. i couldnt solve this in 2 day. can any one help ? 

I/Unity   (28372): Easy Mobile runtime has been initialized.
I/Unity   (28372):
I/Unity   (28372): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
I/Unity   (28372):
I/Unity   (28372): Starting Auth with token client.
I/Unity   (28372):
I/Unity   (28372): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
I/Unity   (28372):
W/Unity   (28372): !!! [Play Games Plugin DLL] 02/07/19 11:56:53 +02:00 WARNING: Creating new PlayGamesPlatform
W/Unity   (28372):
W/Unity   (28372): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
W/Unity   (28372):
W/Unity   (28372): *** [Play Games Plugin DLL] 02/07/19 11:56:53 +02:00 ERROR: Exception launching token request: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
W/Unity   (28372):
W/Unity   (28372): (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
W/Unity   (28372):
W/Unity   (28372): *** [Play Games Plugin DLL] 02/07/19 11:56:53 +02:00 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
W/Unity   (28372): java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
W/Unity   (28372):      at java.lang.Class.classForName(Native Method)
W/Unity   (28372):      at java.lang.Class.forName(Class.java:251)
W/Unity   (28372):      at java.lang.Class.forName(Class.java:216)
W/Unity   (28372):      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
W/Unity   (28372):      at com.unity3d.player.UnityPlayer.c(Unknown Source)
W/Unity   (28372):      at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
W/Unity   (28372):      at android.os.MessageQueue.next(MessageQueue.java:207)
W/Unity   (28372):      at android.os.Looper.loop(Looper.java:123)
W/Unity   (28372):      at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
W/Unity   (28372): Caused by: java.lang.NoClassDefFoundError: com/google/games/bridge/TokenFragment
W/Unity   (28372):      ... 9 more
W/Unity   (28372): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.games.bridge.TokenFragment" on path: DexPathList[[zip file "/data/app/com.belyum.airworld-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.b
E/Unity   (28372): AndroidJavaException: java.lang.ClassNotFoundException: com.sglib.easymobile.androidnative.AppUtil
E/Unity   (28372): java.lang.ClassNotFoundException: com.sglib.easymobile.androidnative.AppUtil
E/Unity   (28372):      at java.lang.Class.classForName(Native Method)
E/Unity   (28372):      at java.lang.Class.forName(Class.java:251)
E/Unity   (28372):      at java.lang.Class.forName(Class.java:216)
E/Unity   (28372):      at com.unity3d.player.UnityPlayer.nativePause(Native Method)
E/Unity   (28372):      at com.unity3d.player.UnityPlayer.l(Unknown Source)
E/Unity   (28372):      at com.unity3d.player.UnityPlayer$21.run(Unknown Source)
E/Unity   (28372):      at android.os.Handler.handleCallback(Handler.java:733)
E/Unity   (28372):      at android.os.Handler.dispatchMessage(Handler.java:95)
E/Unity   (28372):      at android.os.Looper.loop(Looper.java:136)
E/Unity   (28372):      at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
E/Unity   (28372): Caused by: java.lang.NoClassDefFoundError: com/sglib/easymobile/androidnative/AppUtil
E/Unity   (28372):      ... 10 more
E/Unity   (28372): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sglib.easymobile.androidnative.AppUtil" on path: DexPathList[[zip file "/data/app/com.belyum.airworld-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.bely
E/Unity   (28372): AndroidJavaException: java.lang.ClassNotFoundException: com.sglib.easymobile.androidnative.AppUtil
E/Unity   (28372): java.lang.ClassNotFoundException: com.sglib.easymobile.androidnative.AppUtil
E/Unity   (28372):      at java.lang.Class.classForName(Native Method)
E/Unity   (28372):      at java.lang.Class.forName(Class.java:251)
E/Unity   (28372):      at java.lang.Class.forName(Class.java:216)
E/Unity   (28372):      at com.unity3d.player.UnityPlayer.nativeFocusChanged(Native Method)
E/Unity   (28372):      at com.unity3d.player.UnityPlayer.a(Unknown Source)
E/Unity   (28372):      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source)
E/Unity   (28372):      at android.os.Handler.dispatchMessage(Handler.java:98)
E/Unity   (28372):      at android.os.Looper.loop(Looper.java:136)
E/Unity   (28372):      at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
E/Unity   (28372): Caused by: java.lang.NoClassDefFoundError: com/sglib/easymobile/androidnative/AppUtil
E/Unity   (28372):      ... 9 more

**Comment by olehkuznetsov** [comment]
Try Force Resolve and check if you have proguard disabled, please.

**Comment by onurigdi** [comment]
> Try Force Resolve and check if you have proguard disabled, please.

thnx for answer. i tried it but didnt solve my problem. 

"C:\Users\[user name]\.gradle\wrapper\dists\gradle-4.10-bin\bg6py687nqv2mbe6e1hdtk57h\gradle-4.10-bin.zip"  this archive was corrupted. i download it again and delete old one put it the path. then depencies resolving done succesfully. after that they are all worked well.

**Comment by ffff1111** [comment]
Same problem here.
It seems to be a issue with Gradle builds.
Using Internal build system I get no errors.

**Comment by amirkhavari99** [comment]
I'm also getting this error when I build the game. I have reimported the package over and over but nothing seems to help.
`Error Unity java.lang.ClassNotFoundException: com.sglib.easymobile.androidnative.AppUtil`

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
