### ISSUE TITLE
Realtime Multiplayer Quick match error when call.

### ISSUE THREAD

**Issue by kaninhot004** [playgameservices/play-games-plugin-for-unity#2481]
Run by: **Build & Run** ( Development Build: **On**, Script Debuging: **On** )

This is my code.

Everything work fine in production you can see here: https://play.google.com/store/apps/details?id=com.KTGames.ZARTs .
(Except Cloud save that waiting for Google to fix it.)

```
void Start()
{
 PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
            .Build();
        PlayGamesPlatform.InitializeInstance(config);
        PlayGamesPlatform.Activate();
}
```

Then quick match button

```
    public void QuickMatch()
    {
        const int minEnemy = 1;
        const int maxEnemy = 1;
        const int playerSkillRating = 1;
        PlayGamesPlatform.Instance.RealTime.CreateQuickGame(minEnemy, maxEnemy, playerSkillRating, this);
    }
```

```
03-05 11:15:31.305: E/pttSocketApp(506):          aniAsfIpc.c:971 Error(105):Recv failed, ipcPtr [0x9d41b000], sd 4
03-05 11:15:31.305: E/pttSocketApp(506):       pttSocketApp.c:759 IPC Recv failed
03-05 11:15:31.305: E/WLAN_PSA(506): NL MSG RCV err -1 105


03-05 11:15:34.737: E/Volley(2744): [189] BasicNetwork.performRequest: Unexpected response code 401 for https://www.googleapis.com/games/v1/rooms/create?language=en-GB
03-05 11:15:34.809: E/DataHolderOperation(2744): There is no linked app associated with this client ID.
03-05 11:15:34.809: E/DataHolderOperation(2744): jwl
03-05 11:15:34.809: E/DataHolderOperation(2744): 	at jon.a(:com.google.android.play.games@87040046@2019.02.8704 (234222928.234222928-000406):55)
03-05 11:15:34.809: E/DataHolderOperation(2744): 	at ijn.a(:com.google.android.play.games@87040046@2019.02.8704 (234222928.234222928-000406):133)
03-05 11:15:34.809: E/DataHolderOperation(2744): 	at ihf.a(:com.google.android.play.games@87040046@2019.02.8704 (234222928.234222928-000406):650)
03-05 11:15:34.809: E/DataHolderOperation(2744): 	at kcm.b(:com.google.android.play.games@87040046@2019.02.8704 (234222928.234222928-000406):2)
03-05 11:15:34.809: E/DataHolderOperation(2744): 	at jze.a(:com.google.android.play.games@87040046@2019.02.8704 (234222928.234222928-000406):2)
03-05 11:15:34.809: E/DataHolderOperation(2744): 	at gqp.a(:com.google.android.play.games@87040046@2019.02.8704 (234222928.234222928-000406):12)
03-05 11:15:34.809: E/DataHolderOperation(2744): 	at gqm.run(:com.google.android.play.games@87040046@2019.02.8704 (234222928.234222928-000406):1)
03-05 11:15:34.809: E/DataHolderOperation(2744): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-05 11:15:34.809: E/DataHolderOperation(2744): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-05 11:15:34.809: E/DataHolderOperation(2744): 	at java.lang.Thread.run(Thread.java:761)
```

I follow the guide from here: https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/RTMP.md

Thank you for help!

**Comment by 0c0de** [comment]
Did you link your app in play game services in google developer console, and enabled google multiplayer features, also make sure you checked your id is correct

**Comment by kaninhot004** [comment]
Yes I linked it.

In Production Build
Sign In: OK
Leaderboards: OK
Achievements: OK
Cloud Save: Wait for Google
Multiplayer: Not test. ( My internet is slow for upload & download (56kbps in 2019 year lol) so if I need to re-upload everytime that's horrible for me T_T )

In Development Build
Sign In: OK
Leaderboards: OK
Achievements: OK
Cloud Save: Wait for Google
Multiplayer: Failed

**Comment by kaninhot004** [comment]
@0c0de I was test by upload it on Google Play Console ( Close Track ) and it's working.
But it's was so hard to dev by upload it everytime lol.
![image](https://user-images.githubusercontent.com/9493525/53866776-eebee900-4024-11e9-99c2-f514c45a8dbd.png)
