### ISSUE TITLE
v0.9.62 SignIn Error

### ISSUE THREAD

**Issue by UnityKR** [playgameservices/play-games-plugin-for-unity#2485]
Unity 2018.3.7f1
GPGS v0.9.62
SHV-E300L
Android 5.0.1

Don't update to v0.9.62 !!!

03-06 12:07:12.613 3100-4250/? E/Parcel: Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
    java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:308)
        at java.lang.Class.forName(Class.java:272)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2275)
        at android.os.Parcel.readParcelable(Parcel.java:2239)
        at android.os.Parcel.readValue(Parcel.java:2146)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
        at android.os.BaseBundle.unparcel(BaseBundle.java:221)
        at android.os.BaseBundle.getString(BaseBundle.java:918)
        at android.content.Intent.getStringExtra(Intent.java:5386)
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1770)
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1324)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4844)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4681)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:142)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3173)
        at android.os.Binder.execTransact(Binder.java:446)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.api.signin.internal.SignInConfiguration" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:308) 
        at java.lang.Class.forName(Class.java:272) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2275) 
        at android.os.Parcel.readParcelable(Parcel.java:2239) 
        at android.os.Parcel.readValue(Parcel.java:2146) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2479) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
        at android.os.BaseBundle.getString(BaseBundle.java:918) 
        at android.content.Intent.getStringExtra(Intent.java:5386) 
        at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1770) 
        at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1324) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4844) 
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4681) 
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:142) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3173) 
        at android.os.Binder.execTransact(Binder.java:446) 
    	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 18 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by UnityKR** [comment]
using IL2CPP, gradle build : not working.
using mono, internal build : working.

update available.
but java.lang.ClassNotFoundException is continuing.

**Comment by olehkuznetsov** [comment]
Do you have proguard enabled for your build?

**Comment by Pourcentage** [comment]
Is this plugin compatible with proguard or not?

**Comment by olehkuznetsov** [comment]
It is compatible but depends on the proguard options. You need to mark gms classes to be not obfuscated or removed.

**Comment by Pourcentage** [comment]
Ok, thank you very much!
