### ISSUE TITLE
Android 8.x can not sign

### ISSUE THREAD

**Issue by tanding0304** [playgameservices/play-games-plugin-for-unity#2527]
04-04 01:02:12.249 24166-24229/? W/Unity: *** [Play Games Plugin DLL] 04/04/19 1:02:12 +08:00 ERROR: Exception launching token request: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/DisplayCutout;
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:LogWarning(Object)
    GooglePlayGames.OurUtils.<e>c__AnonStorey2:<>m__0() (at F:\IronForce2_5.6\IronForce2Client\Assets\GooglePlayGames\OurUtils\Logger.cs:77)
    GooglePlayGames.OurUtils.PlayGamesHelperObject:Update() (at F:\IronForce2_5.6\IronForce2Client\Assets\GooglePlayGames\OurUtils\PlayGamesHelperObject.cs:135)
     
    (Filename: F Line: 0)
04-04 01:02:12.250 24166-24229/? W/Unity: *** [Play Games Plugin DLL] 04/04/19 1:02:12 +08:00 ERROR: UnityEngine.AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/DisplayCutout;
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/DisplayCutout;
        at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
        at java.lang.reflect.Method.getParameterTypes(Method.java:179)
        at java.lang.Class.getDeclaredMethods(Class.java:1881)
        at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:91)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
        at android.os.MessageQueue.next(MessageQueue.java:394)
        at android.os.Looper.loop(Looper.java:142)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.DisplayCutout" o

**Comment by tanding0304** [comment]
I tested v0.9.61 and v0.9.62 have this problem, but 0950 does not have this problem.

**Comment by olehkuznetsov** [comment]
Can't reproduce, have you tried 'force resolve' option?

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
