### ISSUE TITLE
OpenWithAutomaticConflictResolution  return InternalError 

### ISSUE THREAD

**Issue by chenhuo2** [playgameservices/play-games-plugin-for-unity#2566]
SavedGameRequestStatus is InternalError
When I call OpenWithAutomaticConflictResolution 

        ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame;
        savedGameClient.OpenWithAutomaticConflictResolution(filename, DataSource.ReadCacheOrNetwork,
            ConflictResolutionStrategy.UseLongestPlaytime, (status,game)=> {
    
                Log(status);
                if (status == SavedGameRequestStatus.Success)
                    savedGameClient.ReadBinaryData(game, OnReadFileFinishCallback);

            });

05-06 17:21:07.164 10703-10895/? E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.firebase.internal.api.FirebaseNoSignedInUserException: Please sign in before trying to get a token.
05-06 17:21:07.211 10703-10897/? E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.firebase.internal.api.FirebaseNoSignedInUserException: Please sign in before trying to get a token.
05-06 17:21:07.218 10703-10898/? E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.firebase.internal.api.FirebaseNoSignedInUserException: Please sign in before trying to get a token.
05-06 17:21:10.372 3614-10475/? E/WakeLock: GCM_HB_ALARM release without a matched acquire!
05-06 17:21:10.376 3614-10475/? E/GCM: Connection closed with errorCode 20
05-06 17:21:14.050 10703-10907/? E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.firebase.internal.api.FirebaseNoSignedInUserException: Please sign in before trying to get a token.
05-06 17:21:21.168 17205-17286/? E/Volley: [1775] BasicNetwork.performRequest: Unexpected response code 401 for https://www.googleapis.com/games/v1/applications/played
05-06 17:21:22.870 17205-17288/? E/Volley: [1776] BasicNetwork.performRequest: Unexpected response code 401 for https://www.googleapis.com/games/v1/applications/played
05-06 17:21:27.370 17205-8550/? E/FileContentDownloadTask: Error starting a download: FileContentDownloadTask[EntrySpec[22]]
    tio
        at tiu.a(:com.google.android.gms@16091019@16.0.91 (040400-244116403):40)
        at tiu.b(:com.google.android.gms@16091019@16.0.91 (040400-244116403):9)
        at tiu.a(:com.google.android.gms@16091019@16.0.91 (040400-244116403):50)
        at tiv.a(:com.google.android.gms@16091019@16.0.91 (040400-244116403):6)
        at tim.run(:com.google.android.gms@16091019@16.0.91 (040400-244116403):1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at rrt.b(:com.google.android.gms@16091019@16.0.91 (040400-244116403):32)
        at rrt.run(:com.google.android.gms@16091019@16.0.91 (040400-244116403):21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at rxx.run(:com.google.android.gms@16091019@16.0.91 (040400-244116403))
        at java.lang.Thread.run(Thread.java:761)
05-06 17:21:27.373 17205-10935/? E/SnapshotAgent: Failed to open contents. Result: Status{statusCode=Error downloading file, resolution=null}
05-06 17:21:27.930 3686-13249/? E/PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 17:21:28.049 3686-3960/? E/PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 17:21:29.372 3614-10928/? E/WakeLock: GCM_HB_ALARM release without a matched acquire!
05-06 17:21:38.140 3614-10990/? E/AppUsageEventWatcher: wrong time range: [1558883043998, 1557134498140)
05-06 17:22:17.056 22691-22724/? E/PBSessionCacheImpl: sessionId[99797630511689427] not persisted.
05-06 17:22:17.276 518-11053/? E/audio_route: unable to find path 'set-capture-format-default'
05-06 17:22:18.978 22691-10140/? E/AudioSource: Stop listening is called on already closed AudioSource
05-06 17:22:19.735 3614-10981/? E/WakeLock: GCM_HB_ALARM release without a matched acquire!
05-06 17:22:19.748 3614-10981/? E/GCM: Connection closed with errorCode 20
05-06 17:22:31.929 22691-22724/? E/PBSessionCacheImpl: sessionId[99797630511689427] not persisted.
05-06 17:22:32.102 518-11180/? E/audio_route: unable to find path 'set-capture-format-default'
05-06 17:22:34.305 22691-10137/? E/AudioSource: Stop listening is called on already closed AudioSource
05-06 17:22:37.325 22691-22724/? E/PBSessionCacheImpl: sessionId[99797630511689427] not persisted.
05-06 17:22:37.425 518-11205/? E/audio_route: unable to find path 'set-capture-format-default'
05-06 17:22:43.953 3614-11213/? E/AppUsageEventWatcher: wrong time range: [1558883043998, 1557134563953)
05-06 17:22:49.676 22691-10139/? E/AudioSource: Stop listening is called on already closed AudioSource
05-06 17:22:51.324 22691-22724/? E/PBSessionCacheImpl: sessionId[99797630511689427] not persisted.
05-06 17:22:51.517 518-11252/? E/audio_route: unable to find path 'set-capture-format-default'
05-06 17:22:53.993 22691-10138/? E/AudioSource: Stop listening is called on already closed AudioSource
05-06 17:22:55.518 518-663/? E/volume_listener: check_and_set_gain_dep_cal: Failed to set gain dep cal level
05-06 17:23:05.539 11261-11438/? E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.firebase.internal.api.FirebaseNoSignedInUserException: Please sign in before trying to get a token.
05-06 17:23:05.582 11261-11441/? E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.firebase.internal.api.FirebaseNoSignedInUserException: Please sign in before trying to get a token.
05-06 17:23:05.585 11261-11442/? E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.firebase.internal.api.FirebaseNoSignedInUserException: Please sign in before trying to get a token.
05-06 17:23:09.170 11261-11452/? E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.firebase.internal.api.FirebaseNoSignedInUserException: Please sign in before trying to get a token.
05-06 17:23:15.218 17205-17285/? E/Volley: [1774] BasicNetwork.performRequest: Unexpected response code 401 for https://www.googleapis.com/games/v1/applications/played
05-06 17:23:15.930 17205-17286/? E/Volley: [1775] BasicNetwork.performRequest: Unexpected response code 401 for https://www.googleapis.com/games/v1/applications/played
05-06 17:23:18.132 17205-7214/? E/FileContentDownloadTask: Error starting a download: FileContentDownloadTask[EntrySpec[22]]
    tio
        at tiu.a(:com.google.android.gms@16091019@16.0.91 (040400-244116403):40)
        at tiu.b(:com.google.android.gms@16091019@16.0.91 (040400-244116403):9)
        at tiu.a(:com.google.android.gms@16091019@16.0.91 (040400-244116403):50)
        at tiv.a(:com.google.android.gms@16091019@16.0.91 (040400-244116403):6)
        at tim.run(:com.google.android.gms@16091019@16.0.91 (040400-244116403):1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at rrt.b(:com.google.android.gms@16091019@16.0.91 (040400-244116403):32)
        at rrt.run(:com.google.android.gms@16091019@16.0.91 (040400-244116403):21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at rxx.run(:com.google.android.gms@16091019@16.0.91 (040400-244116403))
        at java.lang.Thread.run(Thread.java:761)
05-06 17:23:18.136 17205-11472/? E/SnapshotAgent: Failed to open contents. Result: Status{statusCode=Error downloading file, resolution=null}
05-06 17:23:19.834 3686-3724/? E/PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 17:23:19.965 3686-4080/? E/PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
05-06 17:24:18.192 3614-11531/? E/AppUsageEventWatcher: wrong time range: [1558883043998, 1557134658191)

**Comment by mcolombo** [comment]
Im having the exact same problem...
Anyone?

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
