### ISSUE TITLE
Play game UID's Are not matching

### ISSUE THREAD

**Issue by howlmoon123** [playgameservices/play-games-plugin-for-unity#2579]
Upgraded to 2019 and newest plugin, also added the Android Jar resolver.  I created an empty project and had everything working before the upgrade, So Google know about the Game. Here is the LOGCAT portion that tells what it is:

`2019-05-25 06:43:55.875 1538-3033/? W/AppOps: Bad call: specified package com.google.android.play.games under uid 10334 but it is really 10213
    java.lang.RuntimeException: here
        at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1402)
        at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1106)
        at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
        at android.os.Binder.execTransact(Binder.java:682)
2019-05-25 06:43:55.876 1538-3033/? W/AppOps: Bad call: specified package com.google.android.play.games under uid 10334 but it is really 10213
    java.lang.RuntimeException: here
        at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1402)
        at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1106)
        at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
        at android.os.Binder.execTransact(Binder.java:682)
2019-05-25 06:43:55.892 1538-4834/? W/AppOps: Bad call: specified package com.google.android.play.games under uid 10334 but it is really 10213
    java.lang.RuntimeException: here
        at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1402)
        at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1106)
        at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
        at android.os.Binder.execTransact(Binder.java:682)
`

**Comment by howlmoon123** [comment]
Downgraded play plugin to .50 and got into play games first time I opened the game. after that every attempt I got the same failure as above. Is there something somewhere I am missing. I tried the Proguard solution and it just threw up a lot of errors.

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
