### ISSUE TITLE
Should I use this plugin?

### ISSUE THREAD

**Issue by UnityKR** [playgameservices/play-games-plugin-for-unity#2610]
Unity 2019.1.7.f1
Android 9
Galaxy S9 +
GPGS 0.9.64
Managed Stripping Level : Disabled

using CubicPilot Sample

Build > Login > Application.Quit() > App Restart > Crash !!!! > App Restart > Not Crash..

--------- beginning of crash
2019-06-24 14:52:31.851 2188-3132/? E/AndroidRuntime: FATAL EXCEPTION: UnityMain
    Process: PACKAGE_NAME, PID: 2188
    java.lang.Error: signal 6 (SIGABRT), code -6 (?), fault addr --------
    Build fingerprint: 'samsung/star2lteks/star2lteks:9/PPR1.180610.011/G965NKSU1CSE3:user/release-keys'
    Revision: '26'
    pid: 2188, tid: 3132, name: UnityMain  >>> PACKAGE_NAME <<<
        r0 00000000  r1 00000c3c  r2 00000006  r3 00000008
        r4 0000088c  r5 00000c3c  r6 d7ab5ad4  r7 0000010c
        r8 d4637858  r9 d4634160  sl d475a6c0  fp d7ab5b10
        ip d7ab5a70  sp d7ab5ac0  lr f32aeeb9  pc f32a5eae  cpsr 00000c3c
    
        at libc.abort(abort:57)
        at libmonobdwgc-2.mono_log_write_logcat(mono_log_write_logcat:244)
        at libmonobdwgc-2.0040ff18(Native Method)
        at libmonobdwgc-2.monoeg_g_logv(monoeg_g_logv:176)
        at libmonobdwgc-2.monoeg_assertion_message(monoeg_assertion_message:92)
        at libmonobdwgc-2.00290dd0(Native Method)
        at libmonobdwgc-2.mono_init_version(mono_init_version:44)
        at libmonobdwgc-2.mini_init(mini_init:1528)
        at libmonobdwgc-2.mono_jit_init_version(mono_jit_init_version:28)
        at libunity.0063de60(Native Method)
        at libunity.0064a884(Native Method)
        at libunity.006a72a8(Native Method)
        at libunity.006a7ddc(Native Method)
        at libunity.006b60a0(Native Method)
        at base.00000e9b(Native Method)

**Comment by olehkuznetsov** [comment]
Should be fixed in v0.10.06. Feel free to reopen if it reproduces there.
