### ISSUE TITLE
what cause this error？，0.9.53 is normal， but 0.9.62 and 0.9.64 has this error.

### ISSUE THREAD

**Issue by pfjhetg** [playgameservices/play-games-plugin-for-unity#2630]
aused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/fragment/app/FragmentActivity;
        at com.google.android.gms.common.api.internal.LifecycleActivity.isSupport(Unknown Source)
        at com.google.android.gms.common.api.internal.LifecycleCallback.getFragment(Unknown Source)
        at com.google.android.gms.common.api.internal.LifecycleCallback.getFragment(Unknown Source)
        at com.google.android.gms.common.api.internal.zaae.zaa(Unknown Source)
        at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source)
        at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source)
        at com.google.android.gms.auth.api.signin.GoogleSignInClient.<init>(Unknown Source)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getClient(Unknown Source)
        at com.google.games.bridge.TokenFragment.buildClient(TokenFragment.java:326)
        at com.google.games.bridge.TokenFragment.processRequest(TokenFragment.java:271)
        at com.google.games.bridge.TokenFragment.onResume(TokenFragment.java:400)
        at android.app.Fragment.performResume(Fragment.java:2263)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1008)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
        at android.app.BackStackRecord.run(BackStackRecord.java:793)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5487)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:765)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:655)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.fragment.app.FragmentActivity" on path: DexPathList[[zip file "/data/app/com.Xchange.Zombie2-2/base.apk"],nativeLibraryDirectories=[/data/app/com.Xchange.Zombie2-2/lib/arm, /data/app/com.Xchange.Zombie2-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.google.android.gms.common.api.internal.LifecycleActivity.isSupport(Unknown Source) 
        at com.google.android.gms.common.api.internal.LifecycleCallback.getFragment(Unknown Source) 
        at com.google.android.gms.common.api.internal.LifecycleCallback.getFragment(Unknown Source) 
        at com.google.android.gms.common.api.internal.zaae.zaa(Unknown Source) 
        at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source) 
        at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source) 
        at com.google.android.gms.auth.api.signin.GoogleSignInClient.<init>(Unknown Source) 
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getClient(Unknown Source) 
        at com.google.games.bridge.TokenFragment.buildClient(TokenFragment.java:326) 
        at com.google.games.bridge.TokenFragment.processRequest(TokenFragment.java:271) 
        at com.google.games.bridge.TokenFragment.onResume(TokenFragment.java:400) 
        at android.app.Fragment.performResume(Fragment.java:2263) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1008) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148) 
        at android.app.BackStackRecord.run(BackStackRecord.java:793) 
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535) 
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5487) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:765) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:655) 
    	Suppressed: java.lang.NoClassDefFoundError: androidx.fragment.app.FragmentActivity
        at dalvik.system.DexFile.defineClassNative(Native Method)
        at dalvik.system.DexFile.defineClass(DexFile.java:226)
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
        at dalvik.system.DexPathList.findClass(DexPathList.java:338)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
        		... 26 more
    	Suppressed: java.lang.ClassNotFoundException: androidx.fragment.app.FragmentActivity
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 25 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-12 16:13:26.054 4337-4427/? E/ConfigurationUpdateTask: Get configuration fail. Connection to http://223.202.110.11 refused, class org.apache.http.conn.HttpHostConnectException, Connection to http://223.202.110.11 refused
07-12 16:13:26.054 4337-4431/? E/AppOnlineConfigurationUpdateTask: Get app configuration fail. Connection to http://223.202.110.11 refused, class org.apache.http.conn.HttpHostConnectException, Connection to http://223.202.110.11 refused
07-12 16:13:26.474 27955-28173/? E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found

**Comment by pfjhetg** [comment]
we have integration audience-network-unity-sdk-5.4.1 and GoogleMobileAds-v3.18.0 in it.

**Comment by legas1** [comment]
Make sure you use either all plugins compiled with AndroidX support or with preAndroidX support. If you have all plugins AndroidX compatible, make sure you enabled Jetifier in Resolver, further reference: https://github.com/googlesamples/unity-jar-resolver/issues/241#issuecomment-505036511.
