### ISSUE TITLE
unity game crash when calling google play sign in(Social.localuser.authenticate) on android or ignore the gpgs authentification

### ISSUE THREAD

**Issue by Phoenixrider23** [playgameservices/play-games-plugin-for-unity#2676]
Hello, I am at the alpha testing of my game and the apk is perfectly functional until I call the google authentification, 
gpgs used to work perfectly fine before, I had to upgrade unity from 2017.1.1f1 to 2017.4.30f1 to fit the requirement of google play console application, at this point I noticed that the google play service was no longer functioning, I haven't made a build a long time before that, then upgraded the gpgs and it was still not functioning, after making a wrong apk track release I had to create another application on the google play console, new Keystore, new game service, etc., I then made all appropriate changes and once testing the game on my phone the game just crashes on google play authentification I have been trying to fix this issue for days now, any help would be appreciated
It crash both when I build the apk directly to the device as well as when I upload it to google play for alpha testing,
the game works fine when I do not request the gpgs authentication sign in

Unity version: 2017.4.30f1
GPGS version: 0.9.64
build: gradle

I have tried all the solution that I could find online including:

-Try with both the upload and certificate signing
-change appID \ to \u003 in the sets/GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin android manifest and also the template android manifest
-google saved game and anti-piracy is off
-added all appropriate email in the application alpha tract and the game service
-package name and application Id is correct in all appropriate location
-reimported all gpsg
-proguard file is enabled in build setting
-replacing Social.localuser.authenticate to PlayGamePlatform.Instance.IsAuthenticated()
-proper library imported: using GooglePlayGames; & using UnityEngine.SocialPlatforms;
-deleting gpgs and reinstalling
-android manifest in the android studio has all the appropriate attribute(package name, applicationID, version code, etc.)

I don't know what else to try at this point, any help would be appreciated
As much as possible I would rather not switch the build system from Gradle back to internal

Here is the adb logcat information once I called for authentication:

08-06 17:31:29.958 32155 32177 I Unity   : Starting Auth with token client.
08-06 17:31:29.958 32155 32177 I Unity   : GooglePlayGames.Native.NativeClient:Authenticate(Action`2, Boolean)
08-06 17:31:29.958 32155 32177 I Unity   : UnityEngine.Events.UnityEvent:Invoke()
08-06 17:31:29.958 32155 32177 I Unity   : UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
08-06 17:31:29.958 32155 32177 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
08-06 17:31:29.958 32155 32177 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
08-06 17:31:29.958 32155 32177 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:Process()
08-06 17:31:29.958 32155 32177 I Unity   :
08-06 17:31:29.958 32155 32177 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
08-06 17:31:29.958 32155 32177 I Unity   :
08-06 17:31:30.014 32155 32177 W Unity   : !!! [Play Games Plugin DLL] 08/06/19 17:31:30 -04:00 WARNING: Creating new PlayGamesPlatform
08-06 17:31:30.014 32155 32177 W Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
08-06 17:31:30.014 32155 32177 W Unity   :
08-06 17:31:30.014 32155 32177 W Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
08-06 17:31:30.014 32155 32177 W Unity   :
08-06 17:31:32.293 32155 32155 I Unity   : Building GPG services, implicitly attempts silent auth
08-06 17:31:32.293 32155 32155 I Unity   : GooglePlayGames.Native.NativeClient:InitializeGameServices()
08-06 17:31:32.293 32155 32155 I Unity   : GooglePlayGames.Native.<Authenticate>c__AnonStorey0:<>m__0(Int32)
08-06 17:31:32.293 32155 32155 I Unity   : System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
08-06 17:31:32.293 32155 32155 I Unity   : UnityEngine.AndroidJavaProxy:Invoke(String, Object[])
08-06 17:31:32.293 32155 32155 I Unity   : UnityEngine._AndroidJNIHelper:InvokeJavaProxyMethod(AndroidJavaProxy, IntPtr, IntPtr)
08-06 17:31:32.293 32155 32155 I Unity   :
08-06 17:31:32.293 32155 32155 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
08-06 17:31:32.293 32155 32155 I Unity   :

In my latest attempt:

I switched back from upload signing to certificate signing on the google API console and also enabling custom Gradle template:
The gpgs authentification gets ignored, the game is operational but the gpgs are not functioning.

08-06 19:28:32.084 11787 11809 I Unity   : Starting Auth with token client.
08-06 19:28:32.084 11787 11809 I Unity   : GooglePlayGames.Native.NativeClient:Authenticate(Action`2, Boolean)
08-06 19:28:32.084 11787 11809 I Unity   : UnityEngine.Events.UnityEvent:Invoke()
08-06 19:28:32.084 11787 11809 I Unity   : UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
08-06 19:28:32.084 11787 11809 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
08-06 19:28:32.084 11787 11809 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
08-06 19:28:32.084 11787 11809 I Unity   : UnityEngine.EventSystems.StandaloneInputModule:Process()
08-06 19:28:32.084 11787 11809 I Unity   :
08-06 19:28:32.084 11787 11809 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
08-06 19:28:32.084 11787 11809 I Unity   :
08-06 19:28:32.125 11787 11809 W Unity   : !!! [Play Games Plugin DLL] 08/06/19 19:28:32 -04:00 WARNING: Creating new PlayGamesPlatform
08-06 19:28:32.125 11787 11809 W Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
08-06 19:28:32.125 11787 11809 W Unity   :
08-06 19:28:32.125 11787 11809 W Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
08-06 19:28:32.125 11787 11809 W Unity   :
08-06 19:28:32.191 11787 11809 W Unity   : *** [Play Games Plugin DLL] 08/06/19 19:28:32 -04:00 ERROR: Exception launching token request: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
08-06 19:28:32.191 11787 11809 W Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
08-06 19:28:32.191 11787 11809 W Unity   :
08-06 19:28:32.191 11787 11809 W Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)
08-06 19:28:32.191 11787 11809 W Unity   :
08-06 19:28:32.199 11787 11809 W Unity   : *** [Play Games Plugin DLL] 08/06/19 19:28:32 -04:00 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
08-06 19:28:32.199 11787 11809 W Unity   : java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
08-06 19:28:32.199 11787 11809 W Unity   :      at java.lang.Class.classForName(Native Method)
08-06 19:28:32.199 11787 11809 W Unity   :      at java.lang.Class.forName(Class.java:453)
08-06 19:28:32.199 11787 11809 W Unity   :      at java.lang.Class.forName(Class.java:378)
08-06 19:28:32.199 11787 11809 W Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
08-06 19:28:32.199 11787 11809 W Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
08-06 19:28:32.199 11787 11809 W Unity   :      at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
08-06 19:28:32.199 11787 11809 W Unity   :      at android.os.MessageQueue.next(MessageQueue.java:394)
08-06 19:28:32.199 11787 11809 W Unity   :      at android.os.Looper.loop(Looper.java:142)
08-06 19:28:32.199 11787 11809 W Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
08-06 19:28:32.199 11787 11809 W Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.games.bridge.TokenFragment" on path: DexPathList[[zip file "/data/app/com.phoneixridergame.heartbeatsurvival-24XUAnT5wWCYXVaWTYMInw==/base.apk"],nativeLibraryDirectories=[/data/app/com.phoneixridergame.heartbeatsurvival-24XUAnT5

**Comment by Phoenixrider23** [comment]
After 1 whole month, I was finally able to get the authentication to work:

Unity version: 2017.4.30f1
GPGS version: 0.9.64
Build system: Gradle

Here are my player setting:

In the other setting:
configuration:
scripting backen: IL2CPP
Target architecture: enable ARMv7 and ARM64 and disable x86

In the publish setting I have:
Build:
Build system: gradle
custom gradle template disabled
proguard file disabled

This is the how I managed to get my google play game service to authenticate for my device on android(do keep in mind that it worked for me, it does not guaranteed that it will work for you, I really hope and wish that it will fix your gpgs problem).

Keep a changelog so that you will be able to fix and roll back if the situation somehow gets worst.

If your gpgs authentification is crashing, then try these step to attempt to solve it:
Step:
1. If you are building localy(directly from your pc to your phone) make sure that you are using the upload certificate as your sha1 on the google api oath2.0 credential and if your are building from your pc to google play store and downloading your apk from there then you need to set up the app singin certificate as your sha1 on the google api oath2.0 credential
2. change your appID from just "\" to "\u003" in the folder GooglePlayGames/Plugins/Android/GooglePlayGamesManifest.plugin/ android manifest and also the template android manifest, not in your main android manifest
3. Disable google saved game and anti piracy in the play console
4. Add all appropriate email in your track as tester on the play console in your application as well as in the google play service
5. make sure that your package name and application id are the same both in your project and in the play console
6. google play service --> android setting --> resolve

If your application still crash at authenticate then try:
Step:
1. create a new clean project
2. watch this youtube tutorial and follow step by step:  https://www.youtube.com/watch?v=0LGs1Xtt_1I&feature=youtu.be&fbclid=IwAR0hYVmes4rF4bvDrjKRD7S5-sWHnsopqvQnhDk9nf6W8-3KUYv4RJm92y4
3. if the authentication work on the clean project, then you know that it is some code interference in your project, in that case
4. compare each file that you have imported from the gpgs from the clean project and with your current project, verify every single folder and file a single missing file could cause problem
5. add/remove any unnecessary folder/file that you might have that is not in common with your clean project the folder are in google play game service, google play game service resolver and plugins folder(becareful in your plugins folder not to delete something connected to another component)
6. google play service --> android setting --> resolve
7. hopefully by now if you have all the same gpgs folder/file as your clean project, the authentication will not crash, now there is 2 possible outcome, either the it will authenticate and everything will be all good or the authentication will be ignore

If your gpgs authentification is simply being ignored, then try these step to attempt to solve it:
Step:
1. remove your main android manifest from your asset and put it in your desktop, just make sure that it is no longer in your project
2. google play service --> android setting --> resolve
3. make a build
4. grab the new generated main android manifest and put it in your plugins folder
5. try the exact same google sign in script as the above youtube tutorial and replace it with yours just for testing
6. google play service --> android setting --> resolve
7. now test your application this time the authentication should work(hopefully)

Good luck!
