### ISSUE TITLE
Upgraded to the latest Unity and Play Games plugin versions and can't complete sign in process

### ISSUE THREAD

**Issue by hitex** [playgameservices/play-games-plugin-for-unity#2722]
I have upgraded to the latest Unity and Play Games Plugin versions and now can't complete sign in process to GPG.
I successfully receive the authentication popup, select the account, get the notification that my account is signed in but then the game becomes unresponsive for 10 seconds or so and when it starts to respond - `Social.localUser.authenticated` is `false`. 

Here is logcat:

```
09-02 01:13:28.098  5548  5548 D GamesUnitySDK: Performing Android initialization of the GPG SDK
09-02 01:13:28.129  5548  5548 I Unity   : Building GPG services, implicitly attempts silent auth
09-02 01:13:28.131  5548  5548 I GamesNativeSDK: Using existing jar.
09-02 01:13:28.131  5548  5548 I GamesNativeSDK: Writing 1941 bytes to jar file
09-02 01:13:28.135  5548  5548 I GamesNativeSDK: Using existing jar.
09-02 01:13:28.135  5548  5548 I GamesNativeSDK: Writing 1066 bytes to jar file
09-02 01:13:28.143  5548  5917 I GamesNativeSDK: Auth operation started: SIGN IN
09-02 01:13:28.144  5548  5917 I GamesNativeSDK: Connecting to Google Play...
09-02 01:13:28.163  5548  5548 V GamesNativeSDK: Received Activity Resume Event.
09-02 01:13:28.163  5548  5548 I Unity   : onResume
09-02 01:13:28.163  5548  5548 D TokenFragment: onResume called
09-02 01:13:28.164  5548  5548 I Unity   : windowFocusChanged: true
09-02 01:13:28.202  5548  5587 I Unity   :  [Play Games Plugin DLL] 09/02/19 1:13:28 +03:00 DEBUG: Invoking user callback on game thread
09-02 01:13:28.223 32040 32531 W GamesServiceBroker: Client connected with SDK 12451000, Services 18719037, and Games 116610048
09-02 01:13:28.235 32040  5527 W GamesServiceBroker: Client connected with SDK 18814000, Services 18719037, and Games 116610048
09-02 01:13:28.346 32040  5527 W GamesServiceBroker: Client connected with SDK 18814000, Services 18719037, and Games 116610048
09-02 01:13:28.406  5548  5548 V GamesNativeSDK: Play Games callback indicates connection.
09-02 01:13:28.412 32040  5527 W GamesServiceBroker: Client connected with SDK 18814000, Services 18719037, and Games 116610048
09-02 01:13:28.431  5548  5917 I GamesNativeSDK: Successfully connected to Google Play.
09-02 01:13:28.464  5548  5587 I Unity   :  [Play Games Plugin DLL] 09/02/19 1:13:28 +03:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: VALID
09-02 01:13:28.465  5548  5587 I Unity   :  [Play Games Plugin DLL] 09/02/19 1:13:28 +03:00 DEBUG: Entering internal callback for PlayerManager#InternalFetchSelfCallback
09-02 01:13:28.482  5548  5587 I Unity   :  [Play Games Plugin DLL] 09/02/19 1:13:28 +03:00 DEBUG: Populating User
09-02 01:13:28.496  5548  5587 I Unity   :  [Play Games Plugin DLL] 09/02/19 1:13:28 +03:00 DEBUG: Found User: [Player: 'ThomasD' (id 110489848606390441989)]
09-02 01:13:28.497  5548  5587 I Unity   :  [Play Games Plugin DLL] 09/02/19 1:13:28 +03:00 DEBUG: Maybe finish for User
09-02 01:13:28.498  5548  5587 I Unity   :  [Play Games Plugin DLL] 09/02/19 1:13:28 +03:00 DEBUG: Auth finished. Proceeding.
09-02 01:13:28.499  5548  5587 I Unity   :  [Play Games Plugin DLL] 09/02/19 1:13:28 +03:00 DEBUG: Invoking Callbacks: System.Action`2[System.Boolean,System.String]
09-02 01:13:28.501 32040  5929 I AchievementAgent: Sending achievement batch...
09-02 01:13:28.514  5548  5587 I Unity   :  [Play Games Plugin DLL] 09/02/19 1:13:28 +03:00 DEBUG: Invoking user callback on game thread
09-02 01:13:28.606  2827  3246 W Auth    : [GetToken] GetToken failed with status code: NeedPermission
09-02 01:13:28.632 32040  5929 W Auth    : [GoogleAuthUtil] GoogleAuthUtil
09-02 01:13:28.633 32040  5929 E DataHolderOperation: Auth error while performing operation, requesting reconnect
09-02 01:13:28.633 32040  5929 E DataHolderOperation: bqx: NeedPermission
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at bqs.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):19)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at bqp.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):4)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at bqp.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):20)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at bqq.b(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):1)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at cje.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):1)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at cir.c(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):12)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at ebc.c(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):1)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at cir.c(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):1)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at cir.b(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):6)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at ebc.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):4)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at ebq.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):10)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at dgf.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):215)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at dgf.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):246)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at dgf.b(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):14)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at elv.b(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):4)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at ekz.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):2)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at bte.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):6)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at bsz.run(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):1)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-02 01:13:28.633 32040  5929 E DataHolderOperation:   at java.lang.Thread.run(Thread.java:764)
09-02 01:13:28.645  5548  5548 I GamesNativeSDK: Auth operation started: SIGN OUT
09-02 01:13:28.645  5548  5548 E GamesNativeSDK: Out of box error detected; the user must reauthenticate through the UIflow.
09-02 01:13:28.651 32040  5929 I AchievementAgent: Sending achievement batch...
09-02 01:13:28.664  1423 15958 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.auth.api.signin.RevocationBoundService.clearClientState cmp=com.pirategames.thegame/brm } U=0: not found
09-02 01:13:28.664 32040  5527 W GamesServiceBroker: Client connected with SDK 18814000, Services 18719037, and Games 116610048
09-02 01:13:28.742  2827  3246 W Auth    : [GetToken] GetToken failed with status code: NeedPermission
09-02 01:13:28.763 32040  5929 W Auth    : [GoogleAuthUtil] GoogleAuthUtil
09-02 01:13:28.764 32040  5929 E DataHolderOperation: Auth error while performing operation, requesting reconnect
09-02 01:13:28.764 32040  5929 E DataHolderOperation: bqx: NeedPermission
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at bqs.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):19)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at bqp.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):4)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at bqp.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):20)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at bqq.b(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):1)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at cje.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):1)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at cir.c(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):12)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at ebc.c(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):1)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at cir.c(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):1)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at cir.b(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):6)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at ebc.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):4)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at ebq.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):10)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at dgf.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):215)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at dgf.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):246)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at dgf.b(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):14)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at elv.b(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):4)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at ekz.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):2)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at bte.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):6)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at bsz.run(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):1)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-02 01:13:28.764 32040  5929 E DataHolderOperation:   at java.lang.Thread.run(Thread.java:764)
09-02 01:13:29.276 32040 32040 E ActivityThread: Service com.google.android.gms.games.chimera.GamesAsyncServiceProxy has leaked ServiceConnection eln@cc45cdf that was originally bound here
09-02 01:13:29.276 32040 32040 E ActivityThread: android.app.ServiceConnectionLeaked: Service com.google.android.gms.games.chimera.GamesAsyncServiceProxy has leaked ServiceConnection eln@cc45cdf that was originally bound here
09-02 01:13:29.276 32040 32040 E ActivityThread:        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1650)
09-02 01:13:29.276 32040 32040 E ActivityThread:        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1542)
09-02 01:13:29.276 32040 32040 E ActivityThread:        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
09-02 01:13:29.276 32040 32040 E ActivityThread:        at android.app.ContextImpl.bindService(ContextImpl.java:1630)
09-02 01:13:29.276 32040 32040 E ActivityThread:        at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
09-02 01:13:29.276 32040 32040 E ActivityThread:        at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
09-02 01:13:29.276 32040 32040 E ActivityThread:        at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
09-02 01:13:29.276 32040 32040 E ActivityThread:        at ckv.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):69)
09-02 01:13:29.276 32040 32040 E ActivityThread:        at ckv.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):62)
09-02 01:13:29.276 32040 32040 E ActivityThread:        at elk.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):7)
09-02 01:13:29.276 32040 32040 E ActivityThread:        at bte.a(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):6)
09-02 01:13:29.276 32040 32040 E ActivityThread:        at bsz.run(:com.google.android.play.games.services@116610040@2019.07.11661 (259783482.259783482-000400):1)
09-02 01:13:29.276 32040 32040 E ActivityThread:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-02 01:13:29.276 32040 32040 E ActivityThread:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-02 01:13:29.276 32040 32040 E ActivityThread:        at java.lang.Thread.run(Thread.java:764)
```

Where is the issue?

**Comment by ozdemir08** [comment]
You mentioned the game being unresponsive for 10 seconds. Can you capture a bug report from the very beginning of sign in?

**Comment by hitex** [comment]
I have updated the issue with entries from the beginning of the sign in. The game does not freeze completely - it just does not react to touches. It is running in the background, I even receive successful callback from `Social.localUser.Authenticate`.
Here is a recording of the whole process: https://youtu.be/fHuGQO9948k

**Comment by olehkuznetsov** [comment]
Can you try to update plugin to version 0.10.05, please?
