### ISSUE TITLE
Crash with java.lang.NullPointerException when pressing Install button with Google Play Store disabled

### ISSUE THREAD

**Issue by LASpencer** [playgameservices/play-games-plugin-for-unity#2752]
Unity 2018.4.7f1
Plugin v0.9.64

After running my app and successful authentication, I closed the app, uninstalled Google Play Games, disabled Google Play Store, and cleared all Google Play Services data.
I started my app again, and when it tried to authenticate a dialog appeared prompting me to install Google Play Games. I pressed Install and after a short time the app crashed with a java.lang.NullPointerException

```
10-17 16:28:23.440: E/AndroidRuntime(9290): FATAL EXCEPTION: GoogleApiHandler
10-17 16:28:23.440: E/AndroidRuntime(9290): Process: au.com.[company name].[app name], PID: 9290
10-17 16:28:23.440: E/AndroidRuntime(9290): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zag(com.google.android.gms.common.ConnectionResult)' on a null object reference
10-17 16:28:23.440: E/AndroidRuntime(9290): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zab.zag(com.google.android.gms:play-services-base@@17.1.0:10)
10-17 16:28:23.440: E/AndroidRuntime(9290): 	at com.google.android.gms.common.api.internal.zace.zac(com.google.android.gms:play-services-base@@17.1.0:45)
10-17 16:28:23.440: E/AndroidRuntime(9290): 	at com.google.android.gms.common.api.internal.zace.zaa(com.google.android.gms:play-services-base@@17.1.0:49)
10-17 16:28:23.440: E/AndroidRuntime(9290): 	at com.google.android.gms.common.api.internal.zacg.run(com.google.android.gms:play-services-base@@17.1.0:2)
10-17 16:28:23.440: E/AndroidRuntime(9290): 	at android.os.Handler.handleCallback(Handler.java:789)
10-17 16:28:23.440: E/AndroidRuntime(9290): 	at android.os.Handler.dispatchMessage(Handler.java:98)
10-17 16:28:23.440: E/AndroidRuntime(9290): 	at com.google.android.gms.internal.base.zar.dispatchMessage(com.google.android.gms:play-services-base@@17.1.0:8)
10-17 16:28:23.440: E/AndroidRuntime(9290): 	at android.os.Looper.loop(Looper.java:164)
10-17 16:28:23.440: E/AndroidRuntime(9290): 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

The next time I run it, and in other situations where it tries to install Google Play Games and Google Play Store is disabled, it fails with this exception, but the app doesn't crash. I'm pretty sure this is the intended behavior.
```
10-17 16:46:49.093: E/GamesUpgradeActivity(14380): Unable to launch play store intent
10-17 16:46:49.093: E/GamesUpgradeActivity(14380): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details id=com.google.android.play.games&pcampaignid=GPG_playGamesUpsell flg=0x80000 pkg=com.android.vending }
```

**Comment by Ravenh0lm** [comment]
Same. On some devices without Google Play Games installed.
When call:
```
if (Social.localUser.authenticated) 
{
	Social.ShowLeaderboardUI();
}
```
I expect an installation request, but I get a stable crash.
```
[EGL] Failed to create window surface: EGL_BAD_ALLOC: EGL failed to allocate resources for the requested operation.    

Device model      : samsung SM-J530FM
10-08 20:44:34.945 14937 14937 E AndroidRuntime: Device fingerprint: samsung/j5y17ltexxm/j5y17lte:7.0/NRD90M/J530FMXXU3ARA1:user/release-keys
10-08 20:44:34.945 14937 14937 E AndroidRuntime:
10-08 20:44:34.945 14937 14937 E AndroidRuntime: Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.google.android.gm
isplayId=0 mBaseDisplayId=0 mFlags=0 } (has extras) }
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1844)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1649)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5037)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at android.app.Activity.startActivityFromFragment(Activity.java:5023)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:7523)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at android.app.Fragment.startActivityForResult(Fragment.java:1150)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at android.app.Fragment.startActivityForResult(Fragment.java:1139)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at com.google.games.bridge.SimpleUiRequest$2.onSuccess(SimpleUiRequest.java:36)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at com.google.games.bridge.SimpleUiRequest$2.onSuccess(SimpleUiRequest.java:33)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at com.google.android.gms.tasks.zzn.run(Unknown Source)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6776)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
10-08 20:44:34.945 14937 14937 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```
v 10.04. Unity 2019.2.8f1. New empty project.

**Comment by Fort44** [comment]
There are some progress on this issue.

**Comment by Ravenh0lm** [comment]
Fixed on all my device

**Comment by ozdemir08** [comment]
Is it fixed for everyone?
