### ISSUE TITLE
[Solved] Google Play Games AND Google Mobile Ads 

### ISSUE THREAD

**Issue by NunoDinisSantos** [playgameservices/play-games-plugin-for-unity#2761]
Hello !

I'm using Unity  to upload my game in google play and I'm getting tons of errors in the pre-launch report (can't upload).
I'm using version 0.9.64 of google mobile games and the new version of the google mobile ads (v4.0.0). If I use a newer version of google mobile games, I get an error create the games (versionHandlerUpdate or something like that).

However, if I only use one of them (google play games v0.9.64 or GoogleMobileAdsV4), the errors disappear and it's all good. But I need both of them in my project. 
Anyone knows how to fix this ? Thanks ! 

**Google play logcat (long one):===========================================**

FATAL EXCEPTION: main
Process: com.NunoQF.ZombieHordeMassacre, PID: 27339
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArraySet;
	at com.google.android.gms.common.api.internal.GoogleApiManager.<init>(Unknown Source:29)
	at com.google.android.gms.common.api.internal.GoogleApiManager.zab(Unknown Source:8)
	at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source:27)
	at com.google.android.gms.common.api.GoogleApi.<init>(Unknown Source:51)
	at com.google.android.gms.auth.api.signin.GoogleSignInClient.<init>(Unknown Source:3)
	at com.google.android.gms.auth.api.signin.GoogleSignIn.getClient(Unknown Source:3)
	at com.google.games.bridge.TokenFragment.buildClient(TokenFragment.java:326)
	at com.google.games.bridge.TokenFragment.processRequest(TokenFragment.java:271)
	at com.google.games.bridge.TokenFragment.onResume(TokenFragment.java:400)
	at android.app.Fragment.performResume(Fragment.java:2657)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1319)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1549)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1611)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2154)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2055)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArraySet" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/androidx.test.tools.crawler-yvK4mjTlnWbVl3xwPelamA==/base.apk", zip file "/data/app/com.NunoQF.ZombieHordeMassacre-kyFb1S_RFCKY0nZ5QWBlhg==/base.apk", zip file "/data/app/com.NunoQF.ZombieHordeMassacre-kyFb1S_RFCKY0nZ5QWBlhg==/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-yvK4mjTlnWbVl3xwPelamA==/lib/arm64, /data/app/com.NunoQF.ZombieHordeMassacre-kyFb1S_RFCKY0nZ5QWBlhg==/lib/arm64, /data/app/androidx.test.tools.crawler-yvK4mjTlnWbVl3xwPelamA==/base.apk!/lib/arm64-v8a, /data/app/com.NunoQF.ZombieHordeMassacre-kyFb1S_RFCKY0nZ5QWBlhg==/base.apk!/lib/arm64-v8a, /data/app/com.NunoQF.ZombieHordeMassacre-kyFb1S_RFCKY0nZ5QWBlhg==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 24 more
	Suppressed: java.io.IOException: No original dex files found for dex location (arm64) /data/app/com.NunoQF.ZombieHordeMassacre-kyFb1S_RFCKY0nZ5QWBlhg==/split_config.arm64_v8a.apk
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:353)
		at dalvik.system.DexFile.<init>(DexFile.java:100)
		at dalvik.system.DexFile.<init>(DexFile.java:74)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
		at dalvik.system.DexPathList.<init>(DexPathList.java:157)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
		at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:676)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:709)
		at android.app.LoadedApk.getResources(LoadedApk.java:942)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:2303)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5937)
		at android.app.ActivityThread.-wrap1(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
		at android.os.Handler.dispatchMessage(Handler.java:105)
		... 5 more

**Comment by NunoDinisSantos** [comment]
Edit: The game actually crashes at start with only the google play games plugin.

**Comment by NunoDinisSantos** [comment]
Ok guys so the problem was Google mobile Ads 
If anyone is having the same problem, try using v0.964 of google play games WITH google mobile ads **VERSION 3.17**

You still have to open the androidmanifest of the google mobile ads and paste your ID in the that file (where it says [APPLICATION_ID], put yours with "" and no [] ). That should solve this problem.
