### ISSUE TITLE
Issue when Login Play Service (Social.localUser.Authenticate)

### ISSUE THREAD

**Issue by m-mine** [playgameservices/play-games-plugin-for-unity#2808]
`2019-12-10 12:12:15.301 7300-7300/? I/AppCompatDelegate: Failed to instantiate custom view inflater android.support.v7.app.AppCompatViewInflater. Falling back to default.
    java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at sj.a(:com.google.android.gms@19629037@19.6.29 (120400-278422107):5)
        at sj.onCreateView(:com.google.android.gms@19629037@19.6.29 (120400-278422107):1)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2084)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2627)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2694)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2094)
        at android.app.ActivityTransitionState.setEnterActivityOptions(ActivityTransitionState.java:171)
        at android.app.Activity.performCreate(Activity.java:7810)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at sj.a(:com.google.android.gms@19629037@19.6.29 (120400-278422107):5) 
        at sj.onCreateView(:com.google.android.gms@19629037@19.6.29 (120400-278422107):1) 
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481) 
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2084) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2627) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2694) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2094) 
        at android.app.ActivityTransitionState.setEnterActivityOptions(ActivityTransitionState.java:171) 
        at android.app.Activity.performCreate(Activity.java:7810) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `

**Comment by m-mine** [comment]
when i try using 
com.android.support:support-compat:28.0.0 has error as below

ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [:androidx.core.core-1.0.0:] AndroidManifest.xml:22:18-86
	is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:4:3-17:17 to override.

**Comment by m-mine** [comment]
The unity auto generated gradle file 
`dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation(name: 'androidx.arch.core.core-runtime-2.0.0', ext:'aar')
    implementation(name: 'androidx.asynclayoutinflater.asynclayoutinflater-1.0.0', ext:'aar')
    implementation(name: 'androidx.coordinatorlayout.coordinatorlayout-1.0.0', ext:'aar')
    implementation(name: 'androidx.core.core-1.0.0', ext:'aar')
    implementation(name: 'androidx.cursoradapter.cursoradapter-1.0.0', ext:'aar')
    implementation(name: 'androidx.customview.customview-1.0.0', ext:'aar')
    implementation(name: 'androidx.documentfile.documentfile-1.0.0', ext:'aar')
    implementation(name: 'androidx.drawerlayout.drawerlayout-1.0.0', ext:'aar')
    implementation(name: 'androidx.fragment.fragment-1.0.0', ext:'aar')
    implementation(name: 'androidx.interpolator.interpolator-1.0.0', ext:'aar')
    implementation(name: 'androidx.legacy.legacy-support-core-ui-1.0.0', ext:'aar')
    implementation(name: 'androidx.legacy.legacy-support-core-utils-1.0.0', ext:'aar')
    implementation(name: 'androidx.lifecycle.lifecycle-livedata-2.0.0', ext:'aar')
    implementation(name: 'androidx.lifecycle.lifecycle-livedata-core-2.0.0', ext:'aar')
    implementation(name: 'androidx.lifecycle.lifecycle-runtime-2.0.0', ext:'aar')
    implementation(name: 'androidx.lifecycle.lifecycle-viewmodel-2.0.0', ext:'aar')
    implementation(name: 'androidx.loader.loader-1.0.0', ext:'aar')
    implementation(name: 'androidx.localbroadcastmanager.localbroadcastmanager-1.0.0', ext:'aar')
    implementation(name: 'androidx.print.print-1.0.0', ext:'aar')
    implementation(name: 'androidx.slidingpanelayout.slidingpanelayout-1.0.0', ext:'aar')
    implementation(name: 'androidx.swiperefreshlayout.swiperefreshlayout-1.0.0', ext:'aar')
    implementation(name: 'androidx.versionedparcelable.versionedparcelable-1.0.0', ext:'aar')
    implementation(name: 'androidx.viewpager.viewpager-1.0.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-auth-17.0.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-auth-api-phone-17.0.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-auth-base-17.0.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-base-17.0.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-basement-17.0.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-drive-17.0.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-games-18.0.1', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-nearby-17.0.0', ext:'aar')
    implementation(name: 'com.google.android.gms.play-services-tasks-17.0.0', ext:'aar')
    implementation(name: 'com.google.games.gpgs-plugin-support-0.10.06', ext:'aar')
    implementation project(':GooglePlayGamesManifest.plugin')
}`

**Comment by m-mine** [comment]
fixed by fill OAuth consent screen logo and support mail ,now it works
this setting should be written in the manual

**Comment by TonAbs** [comment]
Thank you! This worked!
