### ISSUE TITLE
Cannot connect to services if downloaded from Play Store (Account cannot be null)

### ISSUE THREAD

**Issue by PickingPies** [playgameservices/play-games-plugin-for-unity#2825]
I have this issue: I installed the latest version of the plugin. When I use android studio to send the APK to my phone it works fine: it connects and I can use the leaderboads.
But, when I submit it to the play Store and download it, the game freezes momentarily and then, fails. This is the error I got in logcat:

```
2019-12-25 16:56:54.767 3455-4627/? E/AbstractServiceBroker: Getting service failed
    java.lang.NullPointerException: Account cannot be null.
        at byh.a(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):2)
        at dzi.a(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):23)
        at bvk.a(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):32)
        at bwb.a(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):55)
        at bqg.a(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):7)
        at bqk.run(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at cdz.b(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):15)
        at cdz.run(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):10)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at tfn.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)
2019-12-25 16:56:54.767 3455-4627/? W/GmsClient: IGmsServiceBroker.getService failed
    java.lang.NullPointerException: Account cannot be null.
        at byh.a(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):2)
        at dzi.a(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):23)
        at bvk.a(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):32)
        at bwb.a(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):55)
        at bqg.a(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):7)
        at bqk.run(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at cdz.b(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):15)
        at cdz.run(:com.google.android.play.games.services@144490040@2019.11.14449 (285495469.285495469-000400):10)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at tfn.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)
2019-12-25 16:56:54.768 3455-3455/? W/GamesLogHelper: Failed to log event: bmo{statusCode=INTERNAL_ERROR, resolution=null, message=null}
```

**Comment by john-turner** [comment]
I am seeing this exact error as well but unlike @PickingPies  I am getting it in my local apk.

**Comment by tsorrells** [comment]
I'm getting this error sometimes when a game tries to login to my Google Play account.  As a user all I was seeing was a spinning turquoise ring, but when I connected up ADB I saw a very similar log to the one posted above repeated over and over again.

**Comment by olehkuznetsov** [comment]
Your local apk and one in Play Store have different SHA1 signatures. You need to link another Android application with the same package but different SHA1 signature. See this [codelab](https://codelabs.developers.google.com/codelabs/playservices_unity/index.html?index=..%2F..index#0) for more details how to do that.

**Comment by emdimacali** [comment]
I get this error too with a local apk. I noticed it only happens with my Xiaomi Mi 9 with (Android v10). It does not happen on Nox emulator(Android 4.4.2) and on my Huawei GR5 2017 (Android v7). I checked the logs and noticed that it happens after this debug line. 
`DEBUG: Creating Android IPlayGamesClient Client`

I attached a snippet of the log where the same "Account cannot be null" error was logged.
[xiaomilog.txt](https://github.com/playgameservices/play-games-plugin-for-unity/files/4030365/xiaomilog.txt)

**Comment by olehkuznetsov** [comment]
"Account cannot be null" shouldn't affect sign-in. Check if you have linked Android app with release SHA1 key in play console, please.

**Comment by emdimacali** [comment]
> "Account cannot be null" shouldn't affect sign-in. Check if you have linked Android app with release SHA1 key in play console, please.

I already checked. I am currently using the SHA1 in Upload certificate because the game is still in internal testing. My local apk matches that of the one in play console.

**Comment by mythicgit** [comment]
We have the same issue with Unity 2018.4.12f1 and the newest plugin. It doesn't work with "Account cannot be null" no matter if the app is on Google Play or locally. We linked both with upload and our hash and tested on Honor 7X and nVidia Shield K1, both in 64 bit and ARMv7 modes. Any help or workaround idea would be great!

**Comment by mythicgit** [comment]
After 2 days of playing with Google API Console, setting up and linking different Firebase / GPG apps and watching how it affects JSONs, testing on different devices and trying out old versions of Unity Plugin it's finally solved…
We needed to set the OAuth consent screen! (https://console.cloud.google.com/apis/credentials/consent)
As soon as we set the type to external, entered email and saved it all started working. Now it's time for the cleanup...

**Comment by emdimacali** [comment]
Okay, apparently mine was just a dumb issue. I just forgot to tick the checkbox for the group of internal testers.
