### ISSUE TITLE
Warning when using sign in/ Saved Game? Please Help

### ISSUE THREAD

**Issue by cyberstrongmedia** [playgameservices/play-games-plugin-for-unity#2931]
Hello everyone,
i'm having issue with game service
I can signed in and see my name on the top,
i can also Show achievement UI (which means i'm successfully signed in, am i not?)

but on ADB logcat everytime i start the game i get this warning (the one and only warning from game service):

> 08-21 17:27:41.037  3982  4072 W Unity   : !!! [Play Games Plugin 0.10.09] 08/21/20 17:27:41 +07:00 WARNING: Creating new PlayGamesPlatform
08-21 17:27:41.037  3982  4072 W Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
08-21 17:27:41.037  3982  4072 W Unity   : UnityEngine.Logger:Log(LogType, Object)
08-21 17:27:41.037  3982  4072 W Unity   : GooglePlayGames.OurUtils.PlayGamesHelperObject:Update()
08-21 17:27:41.037  3982  4072 W Unity   :
08-21 17:27:41.037  3982  4072 W Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/Android/runtime/DebugBindings.gen.cpp Line: 51)

I have followed the solution below 
[https://github.com/playgameservices/play-games-plugin-for-unity/issues/1754](https://github.com/playgameservices/play-games-plugin-for-unity/issues/1754)
but i saw the certificate is alright already.

Did i make some mistake?
I'm using Playmaker with Easy Mobile and Unity 2017.4.40f1

Thank you for your help !

**Comment by ozdemir08** [comment]
This looks actually looks fine. Apart from these logs, are you having any problems?

**Comment by cyberstrongmedia** [comment]
hello @ozdemir08 thank you for your reply,

i didn't see any warning regarding google game service other than this one.
but when i tried fetching the saved games data and displayed it on the UI : 
date display text became 0-0-0
device returned null
but in the console it logged commitAndClose.succeed
when i reopen the cloud data UI, it now returns the date as 1970-1-1

below is the logcat:

`08-29 09:09:16.755  1831  2052 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10057 but it is really 10030
08-29 09:09:16.755  1831  2052 W AppOps  : java.lang.RuntimeException: here
08-29 09:09:16.755  1831  2052 W AppOps  :      at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1257)
08-29 09:09:16.755  1831  2052 W AppOps  :      at com.android.server.AppOpsService.checkPackage(AppOpsService.java:976)
08-29 09:09:16.755  1831  2052 W AppOps  :      at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
08-29 09:09:16.755  1831  2052 W AppOps  :      at android.os.Binder.execTransact(Binder.java:565)
08-29 09:09:16.755  1831  2052 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10057 but it is really 10030
08-29 09:09:16.755  1831  2052 W AppOps  : java.lang.RuntimeException: here
08-29 09:09:16.755  1831  2052 W AppOps  :      at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1257)
08-29 09:09:16.755  1831  2052 W AppOps  :      at com.android.server.AppOpsService.checkPackage(AppOpsService.java:976)
08-29 09:09:16.755  1831  2052 W AppOps  :      at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
08-29 09:09:16.755  1831  2052 W AppOps  :      at android.os.Binder.execTransact(Binder.java:565)
08-29 09:09:16.808  2033  3233 W GLSUser : [DeviceKeyStore] Cannot load key: Device key file not found.
08-29 09:09:16.839  4406  4461 D EGL_emulation: eglCreateContext: 0x7766bbe215c0: maj 3 min 1 rcv 4
08-29 09:09:16.844  4406  4461 D EGL_emulation: eglMakeCurrent: 0x7766bbe215c0: ver 3 1 (tinfo 0x7766a200d2c0)
08-29 09:09:16.931  2033  3233 W GLSUser : [AppCertManager] Failed to get security token.
08-29 09:09:16.931  2033  3233 W GLSUser : java.io.IOException: INVALID_SENDER
08-29 09:09:16.931  2033  3233 W GLSUser :      at addj.b(:com.google.android.gms@202614023@20.26.14 (040800-320008519):22)
08-29 09:09:16.931  2033  3233 W GLSUser :      at addj.a(:com.google.android.gms@202614023@20.26.14 (040800-320008519):18)
08-29 09:09:16.931  2033  3233 W GLSUser :      at addj.a(:com.google.android.gms@202614023@20.26.14 (040800-320008519):11)
08-29 09:09:16.931  2033  3233 W GLSUser :      at huv.a(:com.google.android.gms@202614023@20.26.14 (040800-320008519):17)
08-29 09:09:16.931  2033  3233 W GLSUser :      at hut.a(:com.google.android.gms@202614023@20.26.14 (040800-320008519):5)
08-29 09:09:16.931  2033  3233 W GLSUser :      at hut.a(:com.google.android.gms@202614023@20.26.14 (040800-320008519):43)
08-29 09:09:16.931  2033  3233 W GLSUser :      at cou.onTransact(:com.google.android.gms@202614023@20.26.14 (040800-320008519):5)
08-29 09:09:16.931  2033  3233 W GLSUser :      at android.os.Binder.transact(Binder.java:499)
08-29 09:09:16.931  2033  3233 W GLSUser :      at css.onTransact(:com.google.android.gms@202614023@20.26.14 (040800-320008519):2)
08-29 09:09:16.931  2033  3233 W GLSUser :      at android.os.Binder.transact(Binder.java:499)
08-29 09:09:16.931  2033  3233 W GLSUser :      at zzr.onTransact(:com.google.android.gms@202614023@20.26.14 (040800-320008519):17)
08-29 09:09:16.931  2033  3233 W GLSUser :      at android.os.Binder.execTransact(Binder.java:565)
08-29 09:09:17.000  2033  3233 W GLSUser : [AppCertManager] IOException while requesting key:
08-29 09:09:17.000  2033  3233 W GLSUser : java.io.IOException: Invalid device key response.
08-29 09:09:17.000  2033  3233 W GLSUser :      at huv.a(:com.google.android.gms@202614023@20.26.14 (040800-320008519):48)
08-29 09:09:17.000  2033  3233 W GLSUser :      at hut.a(:com.google.android.gms@202614023@20.26.14 (040800-320008519):5)
08-29 09:09:17.000  2033  3233 W GLSUser :      at hut.a(:com.google.android.gms@202614023@20.26.14 (040800-320008519):43)
08-29 09:09:17.000  2033  3233 W GLSUser :      at cou.onTransact(:com.google.android.gms@202614023@20.26.14 (040800-320008519):5)
08-29 09:09:17.000  2033  3233 W GLSUser :      at android.os.Binder.transact(Binder.java:499)
08-29 09:09:17.000  2033  3233 W GLSUser :      at css.onTransact(:com.google.android.gms@202614023@20.26.14 (040800-320008519):2)
08-29 09:09:17.000  2033  3233 W GLSUser :      at android.os.Binder.transact(Binder.java:499)
08-29 09:09:17.000  2033  3233 W GLSUser :      at zzr.onTransact(:com.google.android.gms@202614023@20.26.14 (040800-320008519):17)
08-29 09:09:17.000  2033  3233 W GLSUser :      at android.os.Binder.execTransact(Binder.java:565)
08-29 09:09:17.000  2033  3233 W GLSUser : [DeviceKeyStore] Cannot load key: Device key file not found.
08-29 09:09:17.414  2365  2879 I ContentDownloadManager: Up-to-date file is already available locally: EntrySpec[6]
08-29 09:09:17.447  1831  3091 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10057 but it is really 10030
08-29 09:09:17.447  1831  3091 W AppOps  : java.lang.RuntimeException: here
08-29 09:09:17.447  1831  3091 W AppOps  :      at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1257)
08-29 09:09:17.447  1831  3091 W AppOps  :      at com.android.server.AppOpsService.checkPackage(AppOpsService.java:976)
08-29 09:09:17.447  1831  3091 W AppOps  :      at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
08-29 09:09:17.447  1831  3091 W AppOps  :      at android.os.Binder.execTransact(Binder.java:565)
08-29 09:09:17.447  2365  3259 W PlayGamesServices[GamesServiceBroker]: Client connected with SDK 202906000, Services 202614023, and Games 199430084
08-29 09:09:17.447  1831  1860 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10057 but it is really 10030
08-29 09:09:17.447  1831  1860 W AppOps  : java.lang.RuntimeException: here
08-29 09:09:17.447  1831  1860 W AppOps  :      at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1257)
08-29 09:09:17.447  1831  1860 W AppOps  :      at com.android.server.AppOpsService.checkPackage(AppOpsService.java:976)
08-29 09:09:17.447  1831  1860 W AppOps  :      at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
08-29 09:09:17.447  1831  1860 W AppOps  :      at android.os.Binder.execTransact(Binder.java:565)

08-29 09:10:08.064  2033  3233 W GLSUser : [DeviceKeyStore] Cannot load key: Device key file not found.
08-29 09:10:08.064  2033  3233 W GLSUser : [DeviceKeyStore] Cannot load key: Device key file not found.
08-29 09:10:08.420  2365  2879 I ContentDownloadManager: Up-to-date file is already available locally: EntrySpec[6]
08-29 09:10:08.449  1831  2232 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10057 but it is really 10030
08-29 09:10:08.449  1831  2232 W AppOps  : java.lang.RuntimeException: here
08-29 09:10:08.449  1831  2232 W AppOps  :      at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1257)
08-29 09:10:08.449  1831  2232 W AppOps  :      at com.android.server.AppOpsService.checkPackage(AppOpsService.java:976)
08-29 09:10:08.449  1831  2232 W AppOps  :      at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
08-29 09:10:08.449  1831  2232 W AppOps  :      at android.os.Binder.execTransact(Binder.java:565)
08-29 09:10:08.449  2365  3259 W PlayGamesServices[GamesServiceBroker]: Client connected with SDK 202906000, Services 202614023, and Games 199430084
08-29 09:10:08.449  1831  3091 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10057 but it is really 10030
08-29 09:10:08.449  1831  3091 W AppOps  : java.lang.RuntimeException: here
08-29 09:10:08.449  1831  3091 W AppOps  :      at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1257)
08-29 09:10:08.449  1831  3091 W AppOps  :      at com.android.server.AppOpsService.checkPackage(AppOpsService.java:976)
08-29 09:10:08.449  1831  3091 W AppOps  :      at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
08-29 09:10:08.449  1831  3091 W AppOps  :      at android.os.Binder.execTransact(Binder.java:565)
08-29 09:10:08.499  2033  3370 W GLSUser : [DeviceKeyStore] Cannot load key: Device key file not found.
08-29 09:10:08.499  2033  3370 W GLSUser : [DeviceKeyStore] Cannot load key: Device key file not found.
08-29 09:10:08.897  2365  2879 I ContentDownloadManager: Up-to-date file is already available locally: EntrySpec[6]
08-29 09:10:08.928  1831  2232 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10057 but it is really 10030
08-29 09:10:08.928  1831  2232 W AppOps  : java.lang.RuntimeException: here
08-29 09:10:08.928  1831  2232 W AppOps  :      at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1257)
08-29 09:10:08.928  1831  2232 W AppOps  :      at com.android.server.AppOpsService.checkPackage(AppOpsService.java:976)
08-29 09:10:08.928  1831  2232 W AppOps  :      at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
08-29 09:10:08.928  1831  2232 W AppOps  :      at android.os.Binder.execTransact(Binder.java:565)
08-29 09:10:08.928  1831  2232 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10057 but it is really 10030
08-29 09:10:08.928  1831  2232 W AppOps  : java.lang.RuntimeException: here
08-29 09:10:08.928  1831  2232 W AppOps  :      at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1257)
08-29 09:10:08.928  1831  2232 W AppOps  :      at com.android.server.AppOpsService.checkPackage(AppOpsService.java:976)
08-29 09:10:08.928  1831  2232 W AppOps  :      at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
08-29 09:10:08.928  1831  2232 W AppOps  :      at android.os.Binder.execTransact(Binder.java:565)
08-29 09:10:09.363  2365  2879 I PendingContent: Deleted duplicate successfully: fef31306-cb19-4e23-86e2-a43f809a3e9b
08-29 09:10:09.375  2365  3886 I ContentMaintenance: Internal cache bytes used: 0; limit: 100000000; download size: 0
08-29 09:10:09.378  1831  2052 W ActivityManager: Unable to start service Intent { cmp=com.google.android.gms/.drive.api.ApiService } U=0: not found
08-29 09:10:09.379  1831  3091 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10057 but it is really 10030
08-29 09:10:09.379  1831  3091 W AppOps  : java.lang.RuntimeException: here
08-29 09:10:09.379  1831  3091 W AppOps  :      at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1257)
08-29 09:10:09.379  1831  3091 W AppOps  :      at com.android.server.AppOpsService.checkPackage(AppOpsService.java:976)
08-29 09:10:09.379  1831  3091 W AppOps  :      at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
08-29 09:10:09.379  1831  3091 W AppOps  :      at android.os.Binder.execTransact(Binder.java:565)
08-29 09:10:09.379  1831  2052 W AppOps  : Bad call: specified package com.google.android.play.games under uid 10057 but it is really 10030
08-29 09:10:09.379  1831  2052 W AppOps  : java.lang.RuntimeException: here
08-29 09:10:09.379  1831  2052 W AppOps  :      at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1257)
08-29 09:10:09.379  1831  2052 W AppOps  :      at com.android.server.AppOpsService.checkPackage(AppOpsService.java:976)
08-29 09:10:09.379  1831  2052 W AppOps  :      at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
08-29 09:10:09.379  1831  2052 W AppOps  :      at android.os.Binder.execTransact(Binder.java:565)
08-29 09:10:09.388  4675  4675 I Unity   : commitAndClose.succeed
08-29 09:10:09.391  2033  3233 W GLSUser : [DeviceKeyStore] Cannot load key: Device key file not found.
08-29 09:10:09.391  2033  3233 W GLSUser : [DeviceKeyStore] Cannot load key: Device key file not found.
08-29 09:10:09.391  2365  3886 I RealtimeCacheCleanup: Beginning Realtime garbage collection.
08-29 09:10:09.392  2365  3886 I RealtimeCacheCleanup: Finished Realtime garbage collection.
08-29 09:10:11.470  2033  3233 W GLSUser : [DeviceKeyStore] Cannot load key: Device key file not found.
08-29 09:10:11.471  2033  3233 W GLSUser : [DeviceKeyStore] Cannot load key: Device key file not found.
08-29 09:10:11.847  1831  2232 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.drive.ApiService.STOP cmp=com.google.android.gms/.drive.api.ApiService } U=0: not found
08-29 09:10:40.376  2365  3419 I ContentMaintenance: Internal cache bytes used: 52766; limit: 100000000; download size: 0`

i don't understand any of above log :(
please help, thank you so much :D

**Comment by ozdemir08** [comment]
Looks like there is a bug with the returning date. Apart from that, your integration looks fine. We will address this issue with the next release.

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
