### ISSUE TITLE
10.11 Crash on Startup 

### ISSUE THREAD

**Issue by danoli3** [playgameservices/play-games-plugin-for-unity#2952]
```
2020-09-26 23:39:28.931 24750-24750/? W/GoogleSilentSignIn: RemoteException when calling back onSilentSignedInToGoogle().
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1145)
        at cpd.b(:com.google.android.gms@203315028@20.33.15 (100400-330018294):2)
        at hxq.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):1)
        at hyc.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):0)
        at btcq.run(:com.google.android.gms@203315028@20.33.15 (100400-330018294):6)
        at btca.execute(:com.google.android.gms@203315028@20.33.15 (100400-330018294):0)
        at btas.b(:com.google.android.gms@203315028@20.33.15 (100400-330018294):4)
        at btas.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):28)
        at btas.b(:com.google.android.gms@203315028@20.33.15 (100400-330018294):11)
        at btea.run(:com.google.android.gms@203315028@20.33.15 (100400-330018294):9)
        at btca.execute(:com.google.android.gms@203315028@20.33.15 (100400-330018294):0)
        at btas.b(:com.google.android.gms@203315028@20.33.15 (100400-330018294):4)
        at btas.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):28)
        at btas.b(:com.google.android.gms@203315028@20.33.15 (100400-330018294):19)
        at btav.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):2)
        at btaw.run(:com.google.android.gms@203315028@20.33.15 (100400-330018294):12)
        at btca.execute(:com.google.android.gms@203315028@20.33.15 (100400-330018294):0)
        at btas.b(:com.google.android.gms@203315028@20.33.15 (100400-330018294):4)
        at btas.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):28)
        at btas.b(:com.google.android.gms@203315028@20.33.15 (100400-330018294):19)
        at adqg.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):0)
        at rsq.run(Unknown Source:0)
        at suj.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):3)
        at rsn.a(Unknown Source:0)
        at rsq.run(Unknown Source:0)
        at suj.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):3)
        at rsn.a(Unknown Source:0)
        at rss.handleMessage(:com.google.android.gms@203315028@20.33.15 (100400-330018294):5)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at aeuq.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):2)
        at aeuq.dispatchMessage(:com.google.android.gms@203315028@20.33.15 (100400-330018294):12)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)`
```

`2020-09-26 23:39:38.153 4698-4945/? E/axjx: Exception occurred while getting SettingsStore instance.
    java.util.concurrent.ExecutionException: com.google.android.gms.auth.UserRecoverableAuthException: BadAuthentication
        at btas.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):19)
        at btas.get(:com.google.android.gms@203315028@20.33.15 (100400-330018294):13)
        at axjx.b(:com.google.android.gms@203315028@20.33.15 (100400-330018294):3)
        at axjx.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):20)
        at axfq.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):4)
        at axfq.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):68)
        at aakb.run(:com.google.android.gms@203315028@20.33.15 (100400-330018294):11)
        at bodv.run(:com.google.android.gms@203315028@20.33.15 (100400-330018294):2)
        at svc.b(:com.google.android.gms@203315028@20.33.15 (100400-330018294):12)
        at svc.run(:com.google.android.gms@203315028@20.33.15 (100400-330018294):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at tbb.run(:com.google.android.gms@203315028@20.33.15 (100400-330018294):0)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.gms.auth.UserRecoverableAuthException: BadAuthentication
        at gbk.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):3)
        at gbe.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):0)
        at gbk.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):8)
        at gbk.c(:com.google.android.gms@203315028@20.33.15 (100400-330018294):15)
        at gbk.b(:com.google.android.gms@203315028@20.33.15 (100400-330018294):1)
        at gbk.b(:com.google.android.gms@203315028@20.33.15 (100400-330018294):2)
        at gbk.e(:com.google.android.gms@203315028@20.33.15 (100400-330018294):0)
        at axkk.call(Unknown Source:0)
        at btee.b(:com.google.android.gms@203315028@20.33.15 (100400-330018294):0)
        at btdf.run(:com.google.android.gms@203315028@20.33.15 (100400-330018294):3)
        at btef.run(:com.google.android.gms@203315028@20.33.15 (100400-330018294):0)
        at btdm.execute(:com.google.android.gms@203315028@20.33.15 (100400-330018294):5)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at btat.b(:com.google.android.gms@203315028@20.33.15 (100400-330018294):0)
        at axkl.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):7)
        at axfq.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):3)
        at axfq.a(:com.google.android.gms@203315028@20.33.15 (100400-330018294):68) 
        at aakb.run(:com.google.android.gms@203315028@20.33.15 (100400-330018294):11) 
        at bodv.run(:com.google.android.gms@203315028@20.33.15 (100400-330018294):2) 
        at svc.b(:com.google.android.gms@203315028@20.33.15 (100400-330018294):12) 
        at svc.run(:com.google.android.gms@203315028@20.33.15 (100400-330018294):7) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at tbb.run(:com.google.android.gms@203315028@20.33.15 (100400-330018294):0) 
        at java.lang.Thread.run(Thread.java:764) `

Any ideas?

Correct Google Play ID is set. 
User has access to the Game.
Game AntiPiracy is turned on

Unity 2020.1.6 Generated

**Comment by danoli3** [comment]
Fix:
Make sure the 
`<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\u" />   `
is within the Application Tags and not accidentally within the <activity> tags
