### ISSUE TITLE
Disconnecting and reconnecting account from Drive results in inaccessible (404) saved game

### ISSUE THREAD

**Issue by pabloivars** [playgameservices/play-games-plugin-for-unity#3000]
Re-adding the Drive permissions for an app throws an error when trying to access a saved game file:

<pre>02-05 10:24:33.810 27869 29460 E Volley  : [6153] NetworkUtility.d: Unexpected response code 404 for https://www.googleapis.com/drive/v2internal/files/*******?prettyPrint=false&fields=downloadUrl,owners(permissionId,emailAddress,isAuthenticatedUser,displayName,picture(url)),mimeType,subscribed,copyable,indexableText(text),id,writersCanShare,authorizedAppIds,thumbnail(image,mimeType),webViewLink,version,labels(starred,restricted,viewed,trashed),appDataContents,explicitlyTrashed,fileSize,sharedWithMeDate,modifiedDate,spaces,etag,folderFeatures,gplusMedia,folderColorRgb,headRevisionId,parents(isRoot,id),recencyReason,shared,description,title,localId(value,version,space),thumbnailLink,creatorAppId,quotaBytesUsed,lastModifyingUser(permissionId,emailAddress,isAuthenticatedUser,displayName,picture(url)),md5Checksum,fileExtension,alternateLink,modifiedByMeDate,lastViewedByMeDate,webContentLink,userPermission(emailAddress,role,domain,additionalRoles,name,withLink,id,photoLink,type,value),editable,ownerNames,recency,embedLink,createdDate,sharingUser(permissionId,emailAddress,isAuthenticatedUser,displayName,picture(url)),originalFilename,properties(visibility,appId,value,key)&acknowledgeAbuse=false&allProperties=true&fileScopeAppIds=105071846765&updateViewedDate=false
02-05 10:24:33.830 27869 27157 W NetworkResponseErrorDec: StatusCode:404 Reason:[notFound] Location:[file]
02-05 10:24:33.900 27869 31060 I ContentMaintenance: Internal cache bytes used: 2552; limit: 100000000; download size: 0
02-05 10:24:33.907 27869 27157 E AsyncOperation: operation=OpenContentsOperation, opStatusCode=1502 [CONTEXT service_id=11 ]
02-05 10:24:33.907 27869 27157 E AsyncOperation: OperationException[Status{statusCode=Drive item not found, or you are not authorized to access it., resolution=null}]
02-05 10:24:33.907 27869 27157 E AsyncOperation:        at vdf.E(:com.google.android.gms@205016039@20.50.16 (120408-351607135):0)
02-05 10:24:33.907 27869 27157 E AsyncOperation:        at vdf.n(:com.google.android.gms@205016039@20.50.16 (120408-351607135):12)
02-05 10:24:33.907 27869 27157 E AsyncOperation:        at vfo.k(:com.google.android.gms@205016039@20.50.16 (120408-351607135):7)
02-05 10:24:33.907 27869 27157 E AsyncOperation:        at vei.b(:com.google.android.gms@205016039@20.50.16 (120408-351607135):3)
02-05 10:24:33.907 27869 27157 E AsyncOperation:        at vea.fR(:com.google.android.gms@205016039@20.50.16 (120408-351607135):21)
02-05 10:24:33.907 27869 27157 E AsyncOperation:        at abfs.run(:com.google.android.gms@205016039@20.50.16 (120408-351607135):9)
02-05 10:24:33.907 27869 27157 E AsyncOperation:        at bqmr.run(:com.google.android.gms@205016039@20.50.16 (120408-351607135):2)
02-05 10:24:33.907 27869 27157 E AsyncOperation:        at tor.c(:com.google.android.gms@205016039@20.50.16 (120408-351607135):6)
02-05 10:24:33.907 27869 27157 E AsyncOperation:        at tor.run(:com.google.android.gms@205016039@20.50.16 (120408-351607135):7)
02-05 10:24:33.907 27869 27157 E AsyncOperation:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-05 10:24:33.907 27869 27157 E AsyncOperation:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-05 10:24:33.907 27869 27157 E AsyncOperation:        at tup.run(:com.google.android.gms@205016039@20.50.16 (120408-351607135):0)
02-05 10:24:33.907 27869 27157 E AsyncOperation:        at java.lang.Thread.run(Thread.java:919)
02-05 10:24:33.908 27869 31192 E PlayGamesServices[SnapshotAgent]: Failed to open contents. Result: Status{statusCode=Drive item not found, or you are not authorized to access it., resolution=null}
02-05 10:24:33.923 27869 31060 I RealtimeCacheCleanup: Beginning Realtime garbage collection.
02-05 10:24:33.927 27869 31060 I RealtimeCacheCleanup: Finished Realtime garbage collection.
02-05 10:24:34.034  1774  2071 D CompatibilityInfo: mCompatibilityFlags - 0
02-05 10:24:34.034  1774  2071 D CompatibilityInfo: applicationDensity - 480
02-05 10:24:34.035  1774  2071 D CompatibilityInfo: applicationScale - 1.0
02-05 10:24:34.044   972 19408 D AudioPolicyService: UidPolicy::onUidStateChanged() UID=10230 procState=12
02-05 10:24:34.044   972 19408 D AudioPolicyService: updateUidStates_l() allowCapture=1 isAssistantOnTop=0 isTopOrLatestActive=1 isLatestSensitive=0 isSensitiveActive=0 isInCall=0 current->canCaptureOutput=0
02-05 10:24:34.044   972 19408 D AudioPolicyService: updateUidStates_l() allowCapture=true because of on TOP AND uses VOICE_RECOGNITION OR uses HOTWORD
02-05 10:24:34.044   972 19408 D AudioPolicyService: updateUidStates_l() current->uid=10169 current->pid=16111 allowCapture=1 UidState=3 apmStat=1
02-05 10:24:34.044   972 19408 D AudioPolicyService: notifyProcState
02-05 10:24:34.159  1774  4819 V AlarmManager: set(PendingIntent{ba296c6: PendingIntentRecord{8c1501 com.google.android.gms broadcastIntent}}) : type=2 when=477448955whenElapsed477448955maxWhen =478536021 win=1087066 interval=0 flags=0x0 pkg = com.google.android.gms
02-05 10:24:34.162  4597 29566 W NetworkScheduler: Error inserting flex_time=512000 job_id=-1 period=1026000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=205016000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1612517074152 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0, error message: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE) [CONTEXT service_id=218 ]
02-05 10:24:34.163  1774  4819 V AlarmManager: set(PendingIntent{d8b09b4: PendingIntentRecord{8c1501 com.google.android.gms broadcastIntent}}) : type=2 when=477025527whenElapsed477025527maxWhen =477795018 win=769491 interval=0 flags=0x0 pkg = com.google.android.gms
02-05 10:24:34.371 27869 29459 E Volley  : [6152] NetworkUtility.d: Unexpected response code 404 for https://www.googleapis.com/drive/v2internal/files/1z_ijUcHylJqt***?prettyPrint=false&fields=downloadUrl,owners(permissionId,emailAddress,isAuthenticatedUser,displayName,picture(url)),mimeType,subscribed,copyable,indexableText(text),id,writersCanShare,authorizedAppIds,thumbnail(image,mimeType),webViewLink,version,labels(starred,restricted,viewed,trashed),appDataContents,explicitlyTrashed,fileSize,sharedWithMeDate,modifiedDate,spaces,etag,folderFeatures,gplusMedia,folderColorRgb,headRevisionId,parents(isRoot,id),recencyReason,shared,description,title,localId(value,version,space),thumbnailLink,creatorAppId,quotaBytesUsed,lastModifyingUser(permissionId,emailAddress,isAuthenticatedUser,displayName,picture(url)),md5Checksum,fileExtension,alternateLink,modifiedByMeDate,lastViewedByMeDate,webContentLink,userPermission(emailAddress,role,domain,additionalRoles,name,withLink,id,photoLink,type,value),editable,ownerNames,recency,embedLink,createdDate,sharingUser(permissionId,emailAddress,isAuthenticatedUser,displayName,picture(url)),originalFilename,properties(visibility,appId,value,key)&acknowledgeAbuse=false&allProperties=true&fileScopeAppIds=105071846765&updateViewedDate=false
02-05 10:24:34.375 27869 27157 W NetworkResponseErrorDec: StatusCode:404 Reason:[notFound] Location:[file]
02-05 10:24:34.414 27869 27157 E AsyncOperation: operation=GetMetadataOperation, opStatusCode=1502 [CONTEXT service_id=11 ]
02-05 10:24:34.414 27869 27157 E AsyncOperation: OperationException[Status{statusCode=Drive item not found, or you are not authorized to access it., resolution=null}]
02-05 10:24:34.414 27869 27157 E AsyncOperation:        at vdf.E(:com.google.android.gms@205016039@20.50.16 (120408-351607135):0)
02-05 10:24:34.414 27869 27157 E AsyncOperation:        at vdf.M(:com.google.android.gms@205016039@20.50.16 (120408-351607135):5)
02-05 10:24:34.414 27869 27157 E AsyncOperation:        at vdf.f(:com.google.android.gms@205016039@20.50.16 (120408-351607135):0)
02-05 10:24:34.414 27869 27157 E AsyncOperation:        at vdf.k(:com.google.android.gms@205016039@20.50.16 (120408-351607135):7)
02-05 10:24:34.414 27869 27157 E AsyncOperation:        at vfe.b(:com.google.android.gms@205016039@20.50.16 (120408-351607135):2)
02-05 10:24:34.414 27869 27157 E AsyncOperation:        at vea.fR(:com.google.android.gms@205016039@20.50.16 (120408-351607135):21)
02-05 10:24:34.414 27869 27157 E AsyncOperation:        at abfs.run(:com.google.android.gms@205016039@20.50.16 (120408-351607135):9)
02-05 10:24:34.414 27869 27157 E AsyncOperation:        at bqmr.run(:com.google.android.gms@205016039@20.50.16 (120408-351607135):2)
02-05 10:24:34.414 27869 27157 E AsyncOperation:        at tor.c(:com.google.android.gms@205016039@20.50.16 (120408-351607135):6)
02-05 10:24:34.414 27869 27157 E AsyncOperation:        at tor.run(:com.google.android.gms@205016039@20.50.16 (120408-351607135):7)
02-05 10:24:34.414 27869 27157 E AsyncOperation:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-05 10:24:34.414 27869 27157 E AsyncOperation:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-05 10:24:34.414 27869 27157 E AsyncOperation:        at tup.run(:com.google.android.gms@205016039@20.50.16 (120408-351607135):0)
02-05 10:24:34.414 27869 27157 E AsyncOperation:        at java.lang.Thread.run(Thread.java:919)
02-05 10:24:34.416 27869 31192 E PlayGamesServices[SnapshotAgent]: Failed to retrieve metadata: Status{statusCode=Drive item not found, or you are not authorized to access it., resolution=null}
02-05 10:24:34.416 27869 31192 E PlayGamesServices[SnapshotAgent]: java.lang.Throwable
02-05 10:24:34.416 27869 31192 E PlayGamesServices[SnapshotAgent]:      at m.czb.p(:com.google.android.play.games.services@242130040@2021.01.24213 (353017112.353017112-000400):27)
02-05 10:24:34.416 27869 31192 E PlayGamesServices[SnapshotAgent]:      at m.czb.b(:com.google.android.play.games.services@242130040@2021.01.24213 (353017112.353017112-000400):17)
02-05 10:24:34.416 27869 31192 E PlayGamesServices[SnapshotAgent]:      at m.dwy.c(:com.google.android.play.games.services@242130040@2021.01.24213 (353017112.353017112-000400):9)
02-05 10:24:34.416 27869 31192 E PlayGamesServices[SnapshotAgent]:      at m.dtt.a(:com.google.android.play.games.services@242130040@2021.01.24213 (353017112.353017112-000400):1)
02-05 10:24:34.416 27869 31192 E PlayGamesServices[SnapshotAgent]:      at m.bmn.a(:com.google.android.play.games.services@242130040@2021.01.24213 (353017112.353017112-000400):0)
02-05 10:24:34.416 27869 31192 E PlayGamesServices[SnapshotAgent]:      at m.bmk.run(:com.google.android.play.games.services@242130040@2021.01.24213 (353017112.353017112-000400):1)
02-05 10:24:34.416 27869 31192 E PlayGamesServices[SnapshotAgent]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-05 10:24:34.416 27869 31192 E PlayGamesServices[SnapshotAgent]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-05 10:24:34.416 27869 31192 E PlayGamesServices[SnapshotAgent]:      at java.lang.Thread.run(Thread.java:919)
02-05 10:24:34.417 27869 31192 E PlayGamesServices[SnapshotAgent]: Failed to retrieve metadata: Status{statusCode=Drive item not found, or you are not authorized to access it., resolution=null}
02-05 10:24:34.417 27869 31192 E PlayGamesServices[SnapshotAgent]: java.lang.Throwable
02-05 10:24:34.417 27869 31192 E PlayGamesServices[SnapshotAgent]:      at m.czb.p(:com.google.android.play.games.services@242130040@2021.01.24213 (353017112.353017112-000400):27)
02-05 10:24:34.417 27869 31192 E PlayGamesServices[SnapshotAgent]:      at m.czb.b(:com.google.android.play.games.services@242130040@2021.01.24213 (353017112.353017112-000400):17)
02-05 10:24:34.417 27869 31192 E PlayGamesServices[SnapshotAgent]:      at m.dwy.c(:com.google.android.play.games.services@242130040@2021.01.24213 (353017112.353017112-000400):9)
02-05 10:24:34.417 27869 31192 E PlayGamesServices[SnapshotAgent]:      at m.dtt.a(:com.google.android.play.games.services@242130040@2021.01.24213 (353017112.353017112-000400):1)
02-05 10:24:34.417 27869 31192 E PlayGamesServices[SnapshotAgent]:      at m.bmn.a(:com.google.android.play.games.services@242130040@2021.01.24213 (353017112.353017112-000400):0)
02-05 10:24:34.417 27869 31192 E PlayGamesServices[SnapshotAgent]:      at m.bmk.run(:com.google.android.play.games.services@242130040@2021.01.24213 (353017112.353017112-000400):1)
02-05 10:24:34.417 27869 31192 E PlayGamesServices[SnapshotAgent]:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-05 10:24:34.417 27869 31192 E PlayGamesServices[SnapshotAgent]:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-05 10:24:34.417 27869 31192 E PlayGamesServices[SnapshotAgent]:      at java.lang.Thread.run(Thread.java:919)
02-05 10:24:34.422 27869 31192 W PlayGamesServices[SnapshotAgent]: Could not open snapshot savedgame100</pre>

Also on save game:
<pre>02-05 10:37:50.770 27869 24568 W NetworkResponseErrorDec: StatusCode:404 Reason:[notFound] Location:[file]
02-05 10:37:50.805 27869 24568 E AsyncOperation: operation=CreateFolderOperation, opStatusCode=1502 [CONTEXT service_id=11 ]
02-05 10:37:50.805 27869 24568 E AsyncOperation: OperationException[Status{statusCode=Invalid parent folder., resolution=null}]
02-05 10:37:50.805 27869 24568 E AsyncOperation:        at vdf.m(:com.google.android.gms@205016039@20.50.16 (120408-351607135):4)
02-05 10:37:50.805 27869 24568 E AsyncOperation:        at ves.b(:com.google.android.gms@205016039@20.50.16 (120408-351607135):6)
02-05 10:37:50.805 27869 24568 E AsyncOperation:        at vea.fR(:com.google.android.gms@205016039@20.50.16 (120408-351607135):21)
02-05 10:37:50.805 27869 24568 E AsyncOperation:        at abfs.run(:com.google.android.gms@205016039@20.50.16 (120408-351607135):9)
02-05 10:37:50.805 27869 24568 E AsyncOperation:        at bqmr.run(:com.google.android.gms@205016039@20.50.16 (120408-351607135):2)
02-05 10:37:50.805 27869 24568 E AsyncOperation:        at tor.c(:com.google.android.gms@205016039@20.50.16 (120408-351607135):6)
02-05 10:37:50.805 27869 24568 E AsyncOperation:        at tor.run(:com.google.android.gms@205016039@20.50.16 (120408-351607135):7)
02-05 10:37:50.805 27869 24568 E AsyncOperation:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-05 10:37:50.805 27869 24568 E AsyncOperation:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-05 10:37:50.805 27869 24568 E AsyncOperation:        at tup.run(:com.google.android.gms@205016039@20.50.16 (120408-351607135):0)
02-05 10:37:50.805 27869 24568 E AsyncOperation:        at java.lang.Thread.run(Thread.java:919)
02-05 10:37:50.806 27869 32295 E PlayGamesServices[SnapshotAgent]: Folder could not be created: Status{statusCode=Invalid parent folder., resolution=null} 1502
02-05 10:37:50.806 27869 32295 E PlayGamesServices[SnapshotAgent]: Could not find the games folder for game 105071846765
02-05 10:37:50.807 27869 32295 W PlayGamesServices[SnapshotAgent]: Could not open snapshot folder for game 105071846765</pre>

Steps to reproduce:
- Sign in to Google Play Games and save a snapshot.
- Remove permissions from web: Google Drive > Settings ⚙ > Settings > Manage Apps > Options > Disconnect from Drive.
- Sign in in the game, accept permissions and attempt to fetch/save a snapshot.

I tried:
- Clearing game's data
- Clearing cache for Google Play Games, Google Play Services, Google Play Store

The issue only gets solved by reinstalling the app, so maybe the plugin is storing some reference to old folder id

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
