### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by LCEDevBuildMachine** [playgameservices/play-games-plugin-for-unity#3006]
Got this error in signed android build. After it sign in hangs up and nothing happens
- Android 11
- GPGS 10.12
- Unity 2019.4.20
- Android SDK installed with Unity

On the other devices login works!

02-26 14:27:57.798: E/Parcel(1335): Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
02-26 14:27:57.798: E/Parcel(1335): java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
02-26 14:27:57.798: E/Parcel(1335):   at java.lang.Class.classForName(Native Method)
02-26 14:27:57.798: E/Parcel(1335):   at java.lang.Class.forName(Class.java:454)
02-26 14:27:57.798: E/Parcel(1335):   at android.os.Parcel.readParcelableCreator(Parcel.java:3350)
02-26 14:27:57.798: E/Parcel(1335):   at android.os.Parcel.readParcelable(Parcel.java:3284)
02-26 14:27:57.798: E/Parcel(1335):   at android.os.Parcel.readValue(Parcel.java:3186)
02-26 14:27:57.798: E/Parcel(1335):   at android.os.Parcel.readArrayMapInternal(Parcel.java:3579)
02-26 14:27:57.798: E/Parcel(1335):   at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
02-26 14:27:57.798: E/Parcel(1335):   at android.os.BaseBundle.unparcel(BaseBundle.java:236)
02-26 14:27:57.798: E/Parcel(1335):   at android.os.BaseBundle.getString(BaseBundle.java:1196)
02-26 14:27:57.798: E/Parcel(1335):   at android.content.Intent.getStringExtra(Intent.java:8882)
02-26 14:27:57.798: E/Parcel(1335):   at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1110)
02-26 14:27:57.798: E/Parcel(1335):   at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:876)
02-26 14:27:57.798: E/Parcel(1335):   at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1705)
02-26 14:27:57.798: E/Parcel(1335):   at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1556)
02-26 14:27:57.798: E/Parcel(1335):   at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1508)
02-26 14:27:57.798: E/Parcel(1335):   at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1649)
02-26 14:27:57.798: E/Parcel(1335):   at android.os.Binder.execTransactInternal(Binder.java:1190)
02-26 14:27:57.798: E/Parcel(1335):   at android.os.Binder.execTransact(Binder.java:1159)
02-26 14:27:57.798: E/Parcel(1335): Caused by: java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
02-26 14:27:57.798: E/Parcel(1335):   ... 18 more
02-26 14:27:57.798: W/Bundle(1335): Failed to parse Bundle, but defusing quietly
02-26 14:27:57.798: W/Bundle(1335): android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
02-26 14:27:57.798: W/Bundle(1335):   at android.os.Parcel.readParcelableCreator(Parcel.java:3376)
02-26 14:27:57.798: W/Bundle(1335):   at android.os.Parcel.readParcelable(Parcel.java:3284)
02-26 14:27:57.798: W/Bundle(1335):   at android.os.Parcel.readValue(Parcel.java:3186)
02-26 14:27:57.798: W/Bundle(1335):   at android.os.Parcel.readArrayMapInternal(Parcel.java:3579)
02-26 14:27:57.798: W/Bundle(1335):   at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
02-26 14:27:57.798: W/Bundle(1335):   at android.os.BaseBundle.unparcel(BaseBundle.java:236)
02-26 14:27:57.798: W/Bundle(1335):   at android.os.BaseBundle.getString(BaseBundle.java:1196)
02-26 14:27:57.798: W/Bundle(1335):   at android.content.Intent.getStringExtra(Intent.java:8882)
02-26 14:27:57.798: W/Bundle(1335):   at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1110)
02-26 14:27:57.798: W/Bundle(1335):   at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:876)
02-26 14:27:57.798: W/Bundle(1335):   at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1705)
02-26 14:27:57.798: W/Bundle(1335):   at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1556)
02-26 14:27:57.798: W/Bundle(1335):   at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1508)
02-26 14:27:57.798: W/Bundle(1335):   at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1649)
02-26 14:27:57.798: W/Bundle(1335):   at android.os.Binder.execTransactInternal(Binder.java:1190)
02-26 14:27:57.798: W/Bundle(1335):   at android.os.Binder.execTransact(Binder.java:1159)

**Comment by LCEDevBuildMachine** [comment]
Resolver settings below
![изображение](https://user-images.githubusercontent.com/79259394/109473126-fb477200-7a83-11eb-9f67-34b2c578493a.png)

**Comment by LCEDevBuildMachine** [comment]
Tried different sdk versions and plugin version - nothing helps. I also noticed that "sign in" hangs up when auto login disabled in settings and maybe when player have more then one google accounts

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
