### ISSUE TITLE
Lokhttp3/OkHttpClient exception crashes app

### ISSUE THREAD

**Issue by DawidB** [playgameservices/play-games-plugin-for-unity#3014]
I have added GooglePlayGames plugin v10.12 to my Unity (2019.4.20f1) game and I managed to successfully build it for Android (API 29) and deploy it. The game starts and player is able to use Google login with no issues. However when scene is switched, the game crashes with an error:
_FATAL EXCEPTION: Thread-22
Process: com.appid, PID: 32371
java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/OkHttpClient$Builder;
at com.microsoft.xplatcppsdk_internal.HttpRequest.<clinit>(HttpRequest.java:24)
Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.OkHttpClient$Builder" on path: DexPathList[[zip file "/data/app/com.appid-HtfeIsrd6KdOTXdmiaMsrg==/base.apk"],nativeLibraryDirectories=[/data/app/com.appid-HtfeIsrd6KdOTXdmiaMsrg==/lib/arm, /data/app/com.appid-HtfeIsrd6KdOTXdmiaMsrg==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at com.microsoft.xplatcppsdk_internal.HttpRequest.<clinit>(HttpRequest.java:24)_

As I suspect it may have something to do with JAR resolver, but I have no clue how to resolve it.

**Comment by DawidB** [comment]
Found out the root cause - Playfab SDK was causing it.

It seems that enabling Custom Main Gradle Template with default template autogenerated by Unity fixes the problem, as it already includes missing lib:
`   implementation 'com.squareup.okhttp3:okhttp:3.10.0'`

To enable custom gradle template, open Project Settings, select Player tab and then navigate to Publish Settings section.
![image](https://user-images.githubusercontent.com/6333513/111525871-5785e380-875e-11eb-83fb-bdbd7f6416cc.png)
