### ISSUE TITLE
google play service Cause Crash when app start.

### ISSUE THREAD

**Issue by REFIRSER2** [playgameservices/play-games-plugin-for-unity#3040]
05-27 13:51:19.864: D/TokenFragment(12644): silentSignIn.onFailure
05-27 13:51:19.864: D/AndroidRuntime(12644): Shutting down VM
05-27 13:51:19.865: E/AndroidRuntime(12644): FATAL EXCEPTION: main
05-27 13:51:19.865: E/AndroidRuntime(12644): Process: com.dygame.zombiefire2, PID: 12644
05-27 13:51:19.865: E/AndroidRuntime(12644): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/FragmentActivity;
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at com.google.android.gms.auth.api.signin.internal.zzh.zzc(Unknown Source:18)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at com.google.android.gms.auth.api.signin.GoogleSignInClient.silentSignIn(Unknown Source:27)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at com.google.games.bridge.TokenFragment.signIn(TokenFragment.java:216)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at com.google.games.bridge.TokenFragment.processRequest(TokenFragment.java:269)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at com.google.games.bridge.TokenFragment.onResume(TokenFragment.java:397)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at android.app.Fragment.performResume(Fragment.java:2580)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2220)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at android.os.Handler.handleCallback(Handler.java:883)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at android.os.Looper.loop(Looper.java:214)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at android.app.ActivityThread.main(ActivityThread.java:7573)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at java.lang.reflect.Method.invoke(Native Method)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-27 13:51:19.865: E/AndroidRuntime(12644): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
05-27 13:51:19.865: E/AndroidRuntime(12644): Caused by: java.lang.ClassNotFoundException: android.support.v4.app.FragmentActivity
05-27 13:51:19.865: E/AndroidRuntime(12644): 	... 20 more
05-27 13:51:19.881: I/Process(12644): Sending signal. PID: 12644 SIG: 9

log all.

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
