### ISSUE TITLE
Crash com.google.android.gms java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by NickBack** [playgameservices/play-games-plugin-for-unity#3061]
We recently started getting this in builds we upload, anything we can do about it?

FATAL EXCEPTION: highpool[3]
Process: com.google.android.gms, PID: 14780
java.lang.IllegalArgumentException: Arguments must match previous call for Uri: android://com.google.android.gms/files/mdd_pds_config/shared/DiagSharedFiles.pb
	at bpza.f(:com.google.android.gms@210214046@21.02.14 (150400-352619232):0)
	at bgxo.a(:com.google.android.gms@210214046@21.02.14 (150400-352619232):20)
	at bdhw.b(:com.google.android.gms@210214046@21.02.14 (150400-352619232):0)
	at cfwm.b(:com.google.android.gms@210214046@21.02.14 (150400-352619232):1)
	at bdhi.b(:com.google.android.gms@210214046@21.02.14 (150400-352619232):0)
	at cfwm.b(:com.google.android.gms@210214046@21.02.14 (150400-352619232):1)
	at bdck.a(:com.google.android.gms@210214046@21.02.14 (150400-352619232):1)
	at bdho.b(:com.google.android.gms@210214046@21.02.14 (150400-352619232):0)
	at cfwm.b(:com.google.android.gms@210214046@21.02.14 (150400-352619232):1)
	at bdhx.a(:com.google.android.gms@210214046@21.02.14 (150400-352619232):1)
	at bctv.b(:com.google.android.gms@210214046@21.02.14 (150400-352619232):14)
	at bmui.e(:com.google.android.gms@210214046@21.02.14 (150400-352619232):5)
	at bmui.c(:com.google.android.gms@210214046@21.02.14 (150400-352619232):1)
	at amdt.fM(:com.google.android.gms@210214046@21.02.14 (150400-352619232):2)
	at zdv.run(:com.google.android.gms@210214046@21.02.14 (150400-352619232):9)
	at bojz.run(:com.google.android.gms@210214046@21.02.14 (150400-352619232):2)
	at rmw.c(:com.google.android.gms@210214046@21.02.14 (150400-352619232):6)
	at rmw.run(:com.google.android.gms@210214046@21.02.14 (150400-352619232):7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at rst.run(:com.google.android.gms@210214046@21.02.14 (150400-352619232):0)
	at java.lang.Thread.run(Thread.java:923)
	Suppressed: bokl: 
		at tk_trace.279-DownloadAsyncOperation(Unknown Source:0)
		at tk_trace.ocr-OcrModelUpdateStateIntentOperation_onHandleIntentWithRedelivery(Unknown Source:0)

**Comment by smile616** [comment]
Would it be possible to share logcats/bug reports with us? Preferably link to a Google Drive folder but, please, don't accept access request unless it from @google.com email addresses.

See https://developer.android.com/studio/debug/bug-report for the guid on capture and read bug reports.

**Comment by smile616** [comment]
(internal bug id: b/184125322)

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
