### ISSUE TITLE
Error connecting to GPS

### ISSUE THREAD

**Issue by LexVolkov** [playgameservices/play-games-plugin-for-unity#3087]
Hi.
Help me to understand.
When I build in a "Development mode" everything works. But In this mode, i cannot sign a build (what need to download in Google Play Console). But, if unchecked "Development mode" , then an error will appear in the Logcat when i try to call authenticate (Social.localUser.Authenticate).

`2021.11.07 21:15:07.692 21846 21870 Error Unity AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.games.Games
2021.11.07 21:15:07.692 21846 21870 Error Unity java.lang.ClassNotFoundException: com.google.android.gms.games.Games
2021.11.07 21:15:07.692 21846 21870 Error Unity 	at java.lang.Class.classForName(Native Method)
2021.11.07 21:15:07.692 21846 21870 Error Unity 	at java.lang.Class.forName(Class.java:454)
2021.11.07 21:15:07.692 21846 21870 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2021.11.07 21:15:07.692 21846 21870 Error Unity 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
2021.11.07 21:15:07.692 21846 21870 Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
2021.11.07 21:15:07.692 21846 21870 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:103)
2021.11.07 21:15:07.692 21846 21870 Error Unity 	at android.os.Looper.loop(Looper.java:224)
2021.11.07 21:15:07.692 21846 21870 Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
2021.11.07 21:15:07.692 21846 21870 Error Unity Caused by: java.lang.ClassNotFoundException: com.google.android.gms.games.Games
2021.11.07 21:15:07.692 21846 21870 Error Unity 	... 8 more
2021.11.07 21:15:07.692 21846 21870 Error Unity   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
2021.11.07 21:15:07.692 21846 21870 Error Unity   at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <00000000000000000000000000000000>:0 
2021.11.07 21:15:07.692 21846 21870 Error Unity   at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00000] in <000000000000
`

Im using:
Windows 10
Unity 2020.2.22f1 (LTS)
GooglePlayGamesPlugin-0.10.12
In scene, only this example: https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/samples/Minimal
In Unity: 
SDK,NDK,JDK are connected and working properly.
SignKey Installed
"Minify" -> "Release" cheked
"IL2CCP" selected
"ARMv7" and "ARM64" checked
"Android setup" filled
"Force Resolved" did
In Google:
SHA1 Upload matches with Google Cloud Platform
Google Play Sevirce Credentials is configured and Publish.

I don't know what could be wrong. I can't find any answer for a week. but nothing helps. 
Dont works with Upload key in local test and dont works with App key in Google test. 
Please tell me where to look for the problem.

**Comment by LexVolkov** [comment]
found a solution. maybe someone will need: https://www.higithub.com/playgameservices/issue/play-games-plugin-for-unity/3072

just check the box "Custom Proguard File" and paste this into the proguard file:

`-keep class com.google.android.gms.games.leaderboard.** { *; }
-keep class com.google.android.gms.games.snapshot.** { *; }
-keep class com.google.android.gms.games.achievement.** { *; }
-keep class com.google.android.gms.games.event.** { *; }
-keep class com.google.android.gms.games.stats.** { *; }
-keep class com.google.android.gms.games.video.** { *; }
-keep class com.google.android.gms.games.* { *; }
-keep class com.google.android.gms.common.api.ResultCallback { *; }
-keep class com.google.android.gms.signin.** { *; }
-keep class com.google.android.gms.dynamic.** { *; }
-keep class com.google.android.gms.dynamite.** { *; }
-keep class com.google.android.gms.tasks.** { *; }
-keep class com.google.android.gms.security.** { *; }
-keep class com.google.android.gms.base.** { *; }
-keep class com.google.android.gms.actions.** { *; }
-keep class com.google.games.bridge.** { *; }
-keep class com.google.android.gms.common.ConnectionResult { *; }
-keep class com.google.android.gms.common.GooglePlayServicesUtil { *; }
-keep class com.google.android.gms.common.api.** { *; }
-keep class com.google.android.gms.common.data.DataBufferUtils { *; }
-keep class com.google.android.gms.games.quest.** { *; }
-keep class com.google.android.gms.nearby.** { *; }
-keep class com.google.android.gms.games.Games.** { *; }
-keep class com.google.android.gms.games.multiplayer.** { *; }
-keep class com.unity.androidnotifications.* { *; }`
