### ISSUE TITLE
Welcome Popup keeps showing every 5-10mins 

### ISSUE THREAD

**Issue by kuoliangkwong** [playgameservices/play-games-plugin-for-unity#3108]
I have been getting the welcome popup every 5-10mins time. First it would show the first welcome popup when `PlayGamesPlatform.Instance.Authenticate` is called. Then after 5-10mins of gameplay,  whenever `PlayGamesPlatform.Instance.SavedGame.OpenWithAutomaticConflictResolution` is called to handle save game, the welcome popup will show again. This never happens to 0.10.06 version. This issue occurs after upgrading to 0.10.13.

Here're the logs from logcat
```
2022-01-13 15:41:13.700 26023-26023/? D/BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.signin.service.START pkg=com.google.android.gms }
2022-01-13 15:41:13.700 26023-26023/? D/BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.signin.service.START pkg=com.google.android.gms }
2022-01-13 15:41:13.851 26023-7751/? I/SignInPerformer-54: Handling request [GetGamesServiceRequest{gamePackageName=com.xxxx.xxxx.xxx, gameUid=xxx, gamePlayServicesClientLibraryVersion=12451000, sdkVariation=1052947, requestedScopes=[https://www.googleapis.com/auth/drive.appdata, https://www.googleapis.com/auth/games_lite], callingIdentity=CallingIdentity{uid=xxxx, pid=6949, packageName=com.xxxx.xxxx.xxx, playServicesClientLibraryVersion=12451000}, requestedAccount=Optional.absent(), forceResolveAccountKey=null, requestedServiceMode=0}], isFirstPartyCaller [false], Overdrive [enabled] [CONTEXT service_id=1 ]
2022-01-13 15:41:13.872 26023-26259/? I/LegacyGetServiceValidat: onGetService() from Client SDK version [214815000], Module version [214815033], PGA version [304712030], Account [Account {name=<<default account>>, type=com.google}], Calling package [com.google.android.gms], Game package [com.google.android.gms] [CONTEXT service_id=1 ]
2022-01-13 15:41:13.873 26023-26259/? W/GetGamesServiceReqFacto: Parsing request with ignored arguments. signInOptionsBundle [Bundle[{com.google.android.gms.signin.internal.serverClientId=null, com.google.android.gms.signin.internal.usePromptModeForAuthCode=true, com.google.android.gms.signin.internal.logSessionId=null, com.google.android.gms.signin.internal.hostedDomain=null, com.google.android.gms.signin.internal.offlineAccessRequested=false, com.google.android.gms.signin.internal.waitForAccessTokenRefresh=false, com.google.android.gms.signin.internal.clientRequestedAccount=Account {name=<<default account>>, type=com.google}, com.google.android.gms.signin.internal.idTokenRequested=false, com.google.android.gms.signin.internal.forceCodeForRefreshToken=false}]], isRetryingSignIn [false], skipWelcomePopup [false], requireGooglePlus [false]
2022-01-13 15:41:13.917 26023-26023/? D/BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.signin.service.INTERNAL_START id=identifierhack:xxxxx-bb5e-453e-b623-2786bae151f2 pkg=com.google.android.gms (has extras) }
2022-01-13 15:41:13.917 26023-26023/? D/BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.signin.service.INTERNAL_START id=identifierhack:xxxxxx-bb5e-453e-b623-2786bae151f2 pkg=com.google.android.gms (has extras) }
2022-01-13 15:41:13.936 26023-26023/? D/BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.signin.service.INTERNAL_START id=identifierhack:xxxxx-bb5e-453e-b623-2786bae151f2 pkg=com.google.android.gms (has extras) }
2022-01-13 15:41:13.939 26023-7751/? I/SignInPerformer-54: Successfully authorized dpo{clientPackageName=com.xxxx.xxxx.xxx, clientUid=xxxxx, account=<ELLIDED:-xxxxx>, requestedScopes=[https://www.googleapis.com/auth/drive.appdata, https://www.googleapis.com/auth/games_lite], shouldIncludeAllGrantedScopes=false, gamesAutoSignInPolicyAction=APPLY_AND_APPROVE, serverClientId=null, forceRefreshToken=false} [CONTEXT service_id=1 ]
2022-01-13 15:41:13.976 26023-26023/? D/BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.signin.service.START cmp=com.google.android.gms/.chimera.GmsApiService }
2022-01-13 15:41:13.977 26023-26023/? D/BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.signin.service.START cmp=com.google.android.gms/.chimera.GmsApiService }
2022-01-13 15:41:14.079 26023-7751/? I/GmsCoreAccountHinter: No Games Java SDK version for com.xxxx.xxxx.xxx. Assuming first generation SDK. Updating active gmscore account. [CONTEXT service_id=1 ]
2022-01-13 15:41:14.080 26023-7751/? I/GmsCoreAccountHinter: Hinted account Account {name=kuoliang.kwong@gmail.com, type=com.google} for com.xxxx.xxxx.xxx [CONTEXT service_id=1 ]
2022-01-13 15:41:14.102 26023-7751/? I/SignInManagerV2: Recorded sign-in successful: request[ebk{gamePackageName=com.xxxx.xxxx.xxx, gameUid=10758, account=<ELLIDED:-xxxxx>, playerId=<ELLIDED:-xxxxx>, grantedScoped=[https://www.googleapis.com/auth/drive.appdata, https://www.googleapis.com/auth/games_lite]}] [CONTEXT service_id=1 ]
2022-01-13 15:41:14.158 26023-7751/? I/GetGamesServiceV2Op: Successfully brokered GamesService for request egz{gamePackageName=com.xxxx.xxxx.xxx, gameUid=xxxx, gamePlayServicesClientLibraryVersion=12451000, sdkVariation=1052947, requestedScopes=[https://www.googleapis.com/auth/drive.appdata, https://www.googleapis.com/auth/games_lite], callingIdentity=CallingIdentity{uid=xxxx, pid=6949, packageName=com.xxxx.xxxx.xxx, playServicesClientLibraryVersion=12451000}, requestedAccount=Optional.absent(), forceResolveAccountKey=null, requestedServiceMode=0} [CONTEXT service_id=1 ]
2022-01-13 15:41:14.161 26023-7751/? I/SignInPerformer-55: Handling request [GetGamesServiceRequest{gamePackageName=com.google.android.gms, gameUid=xxxx, gamePlayServicesClientLibraryVersion=214815000, sdkVariation=1052947, requestedScopes=[https://www.googleapis.com/auth/games_lite], callingIdentity=CallingIdentity{uid=xxxx, pid=26023, packageName=com.google.android.gms, playServicesClientLibraryVersion=214815000}, requestedAccount=Optional.absent(), forceResolveAccountKey=null, requestedServiceMode=2}], isFirstPartyCaller [true], Overdrive [enabled] [CONTEXT service_id=1 ]
2022-01-13 15:41:14.168 26023-7751/? I/GetGamesServiceV2Op: Successfully brokered GamesService for request egz{gamePackageName=com.google.android.gms, gameUid=xxxx, gamePlayServicesClientLibraryVersion=214815000, sdkVariation=1052947, requestedScopes=[https://www.googleapis.com/auth/games_lite], callingIdentity=CallingIdentity{uid=xxxx, pid=26023, packageName=com.google.android.gms, playServicesClientLibraryVersion=214815000}, requestedAccount=Optional.absent(), forceResolveAccountKey=null, requestedServiceMode=2} [CONTEXT service_id=1 ]
2022-01-13 15:41:14.216 531-5188/? I/SurfaceFlinger: [SF client] NEW(0xea98f5c0) for (26023:com.google.android.gms)
2022-01-13 15:41:14.221 531-5188/? I/SurfaceFlinger: id=5397 createSurf (0x0),-1 flag=80004, bd88122 com.google.android.gms#0
2022-01-13 15:41:14.327 1107-1148/? V/WindowManager: Relayout Window{bd88122 u0 com.google.android.gms}: viewVisibility=0 req=720x168
2022-01-13 15:41:14.338 1107-1148/? D/WindowManager: isScreenshotDisabledLocked - win: Window{bd88122 u0 com.google.android.gms}
2022-01-13 15:41:14.377 1107-5786/? D/WindowManager: finishDrawingWindow: Window{bd88122 u0 com.google.android.gms} mDrawState=DRAW_PENDING
2022-01-13 15:41:14.416 1107-1148/? V/WindowManager: Relayout Window{bd88122 u0 com.google.android.gms}: viewVisibility=0 req=720x168
2022-01-13 15:41:14.454 1107-1148/? D/WindowManager: finishDrawingWindow: Window{bd88122 u0 com.google.android.gms} mDrawState=HAS_DRAWN
2022-01-13 15:41:14.490 26023-32492/? E/Volley: [18279] BasicNetwork.performRequest: Unexpected response code 401 for https://www.googleapis.com/games/v1/applications/played
2022-01-13 15:41:14.520 26023-7754/? W/PlayGamesServices[GameAgent]: Volley error when reporting played
    com.android.volley.AuthFailureError
        at com.android.volley.toolbox.BasicNetwork.performRequest(:com.google.android.gms.optional_games@214815057@21.48.15 (100000-0):36)
        at m.ctf.performRequest(:com.google.android.gms.optional_games@214815057@21.48.15 (100000-0):17)
        at com.android.volley.NetworkDispatcher.a(:com.google.android.gms.optional_games@214815057@21.48.15 (100000-0):5)
        at m.hgm.b(:com.google.android.gms.optional_games@214815057@21.48.15 (100000-0):0)
        at m.hgs.run(:com.google.android.gms.optional_games@214815057@21.48.15 (100000-0):0)
        at m.cwi.c(:com.google.android.gms.optional_games@214815057@21.48.15 (100000-0):6)
        at m.cwi.run(:com.google.android.gms.optional_games@214815057@21.48.15 (100000-0):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at vub.run(:com.google.android.gms@214815033@21.48.15 (150300-414534850):0)
        at java.lang.Thread.run(Thread.java:923)
2022-01-13 15:41:15.472 26023-3274/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@214815033@21.48.15 (150300-414534850):2)
2022-01-13 15:41:15.473 26023-3274/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@214815033@21.48.15 (150300-414534850):0)
2022-01-13 15:41:15.507 26023-3274/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@214815033@21.48.15 (150300-414534850):2)
2022-01-13 15:41:15.507 26023-3274/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@214815033@21.48.15 (150300-414534850):0)
2022-01-13 15:41:16.324 6949-6949/? I/Unity: commitAndClose.succeed
    UnityEngine.Logger:Log(LogType, Object)
    GooglePlayGames.Android.<>c__DisplayClass9_0:<CommitUpdate>b__0(AndroidJavaObject)
    GooglePlayGames.Android.TaskOnSuccessProxy`1:onSuccess(T)
    System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
    System.Reflection.MethodBase:Invoke(Object, Object[])
    UnityEngine.AndroidJavaProxy:Invoke(String, Object[])
    UnityEngine._AndroidJNIHelper:InvokeJavaProxyMethod(AndroidJavaProxy, IntPtr, IntPtr)
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
2022-01-13 15:41:17.367 26023-3274/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@214815033@21.48.15 (150300-414534850):2)
2022-01-13 15:41:17.367 26023-3274/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@214815033@21.48.15 (150300-414534850):0)
2022-01-13 15:41:17.423 26023-3274/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@214815033@21.48.15 (150300-414534850):2)
2022-01-13 15:41:17.423 26023-3274/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@214815033@21.48.15 (150300-414534850):0)
2022-01-13 15:41:18.515 531-531/? I/Layer: id=5397 Destroyed bd88122 com.google.android.gms#0
2022-01-13 15:41:18.851 26023-26023/? D/BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.signin.service.START pkg=com.google.android.gms }
2022-01-13 15:41:19.054 26023-26023/? D/BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.signin.service.START cmp=com.google.android.gms/.chimera.GmsApiService }
2022-01-13 15:41:19.066 1107-1342/? V/SamsungAlarmManager: Sending to uid : 10022 action=com.google.android.gms.auth.authzen.cryptauth.DEVICE_STATE_CHECK_DELAY_COMPLETE alarm=Alarm{f28ed5c type 3 when 855804004 com.google.android.gms}
2022-01-13 15:41:19.074 1107-1342/? D/ActivityManager: Received SERVICE intent 0x222c0a0 Key{startService pkg=com.google.android.gms/com.google.android.gms.auth_authzen__phone intent=act=com.google.android.gms.auth.authzen.cryptauth.DEVICE_STATE_CHECK_DELAY_COMPLETE cat=[targeted_intent_op_prefix:.auth.authzen.cryptauth.DeviceStateSyncManager$CheckStateEventIntentOperation] cmp=com.google.android.gms/.chimera.GmsIntentOperationService flags=0x0 u=0} requestCode=0 from uid 1000
```

Unity: 2018.4.25f1
Play Games Plugin Unity: 0.10.13
Android OS version: 11

**Comment by kuoliangkwong** [comment]
> There are some changes in v10.13 that may cause a configuration issue in the Android manifest file

Did you mean the `GooglePlayGames\Plugins\Android\GooglePlayGamesManifest.androidlib` folder in older Unity version? If yes, I renamed it to `GooglePlayGamesManifest.plugin` so the Android manifest is included correctly, but the popup still occurs every few mins.

Also tried v10.14, still same issue.

Here's the bug report captured from my Android device [https://drive.google.com/file/d/1NK7F1qGLAqYwUCXNwQGJkuPxT0fAliJh/view?usp=sharing](url)

**Comment by kuoliangkwong** [comment]
To make the scope smaller, I have tested several versions and noticed v10.09 and below are working fine. All versions starting v10.10 and above have the issue.

**Comment by SalaheddineChafik** [comment]
Play Games Plugin Unity: 0.10.12 same issue.

**Comment by vaibhavgpt-google** [comment]
Closing this issue as part of a cleanup of older tickets. Google Play Games v1 is now deprecated. Please upgrade to version v2.1.0 or newer: https://github.com/playgameservices/play-games-plugin-for-unity/releases/tag/v2.1.0. If this issue persists on the new v2 architecture, please open a new ticket.
