### ISSUE TITLE
Login always failed, the login dialog pops up, after selected email account, the circle waiting is shown, but latter failed

### ISSUE THREAD

**Issue by liiijz** [playgameservices/play-games-plugin-for-unity#451]
Followed the official tutors, app setup is OK

But when using this sdk in unity, always login failed, the login windows has popped up, so I think the integration is OK

logcat always printed this message:
04-01 11:05:25.056: V/GamesNativeSDK(10463): Play Games callback indicates connection failure.
04-01 11:05:25.056: I/GamesNativeSDK(10463): UI interaction required to connect to Google Play.

**Comment by liiijz** [comment]
04-01 11:29:56.886: I/GamesNativeSDK(12112): Auth operation started: SIGN IN
04-01 11:29:56.886: I/GamesNativeSDK(12112): Connecting to Google Play...
04-01 11:29:56.891: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:56.896: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:56.901: W/EDMNativeHelper(2547): EDMNativeHelperService is published
04-01 11:29:56.911: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:56.916: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:56.931: D/dalvikvm(13848): Note: class Lcom/google/android/gms/games/internal/eb; has 200 unimplemented (abstract) methods
04-01 11:29:56.946: D/AppStateService(13848): client connected with version: 7095000
04-01 11:29:56.961: D/InputReader(3079): Input event: value=0 when=31084453338000
04-01 11:29:56.961: I/InputReader(3079): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=31084453341000
04-01 11:29:56.961: I/InputDispatcher(3079): Delivering touch to: action: 0x1
04-01 11:29:56.976: I/System.out(12112): Thread-2910 calls detatch()
04-01 11:29:57.036: W/GmsApplication(13848): Using Auth Proxy for data requests.
04-01 11:29:57.076: I/GoogleURLConnFactory(13848): Using platform SSLCertificateSocketFactory
04-01 11:29:57.086: I/GLSUser(13848): [ ChannelManager ] Attempting to channel bind connection HttpClient.
04-01 11:29:57.106: I/GLSUser(13848): [ ChannelManager ] Skip channel binding on pre-KLP devices.
04-01 11:29:57.121: W/GmsApplication(13848): Using Auth Proxy for data requests.
04-01 11:29:57.166: W/GmsApplication(13848): Using Auth Proxy for data requests.
04-01 11:29:57.166: W/GmsApplication(13848): Using Auth Proxy for data requests.
04-01 11:29:57.186: D/dalvikvm(13848): GC_CONCURRENT freed 1964K, 19% free 17961K/21928K, paused 4ms+6ms, total 44ms
04-01 11:29:57.236: W/GmsApplication(13848): Using Auth Proxy for data requests.
04-01 11:29:57.266: W/GmsApplication(13848): Using Auth Proxy for data requests.
04-01 11:29:57.271: W/GmsApplication(13848): Using Auth Proxy for data requests.
04-01 11:29:57.291: W/GmsApplication(13848): Using Auth Proxy for data requests.
04-01 11:29:57.536: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:57.541: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:57.546: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:57.546: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:57.561: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:57.561: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:57.576: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:57.576: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:57.581: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:57.586: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:57.591: W/ApplicationPackageManager(3836): getCSCPackageItemText()
04-01 11:29:57.591: V/GamesNativeSDK(12112): Play Games callback indicates connection failure.
04-01 11:29:57.591: I/GamesNativeSDK(12112): UI interaction required to connect to Google Play.
04-01 11:29:57.591: I/GamesNativeSDK(12112): Resolving connection.

**Comment by liiijz** [comment]
04-01 12:41:47.271: E/GamesNativeSDK(26205): Exception in dalvik/system/DexClassLoader.loadClass: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.NativeSdkEntryPoints" on path: DexPathList[[zip file "/data/data/app_.gpg.classloader/4da25210572e7e07ea67142ded62c42e.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]].
04-01 12:41:48.911: E/AuthZen(13848): Failed to do enrollment for account: XXXXXXXXXXXXXXXXXXXXXXXXX
04-01 12:41:48.911: E/AuthZen(13848): com.google.android.gms.auth.authzen.b.b: Failed to get GCM registeration id
04-01 12:41:48.911: E/AuthZen(13848): 	at com.google.android.gms.auth.authzen.b.a.a(SourceFile:152)
04-01 12:41:48.911: E/AuthZen(13848): 	at com.google.android.gms.auth.authzen.b.d.a(SourceFile:200)
04-01 12:41:48.911: E/AuthZen(13848): 	at com.google.android.gms.auth.authzen.b.d.a(SourceFile:153)
04-01 12:41:48.911: E/AuthZen(13848): 	at com.google.android.gms.auth.authzen.b.d.a(SourceFile:103)
04-01 12:41:48.911: E/AuthZen(13848): 	at com.google.android.gms.auth.be.cryptauth.sync.b.a(SourceFile:256)
04-01 12:41:48.911: E/AuthZen(13848): 	at com.google.android.gms.auth.be.cryptauth.sync.b.a(SourceFile:207)
04-01 12:41:48.911: E/AuthZen(13848): 	at com.google.android.gms.auth.be.cryptauth.sync.b.a(SourceFile:200)
04-01 12:41:48.911: E/AuthZen(13848): 	at com.google.android.gms.auth.authzen.a.a(SourceFile:104)
04-01 12:41:48.911: E/AuthZen(13848): 	at com.google.android.gms.auth.authzen.GcmReceiverService.onHandleIntent(SourceFile:28)
04-01 12:41:48.911: E/AuthZen(13848): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
04-01 12:41:48.911: E/AuthZen(13848): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-01 12:41:48.911: E/AuthZen(13848): 	at android.os.Looper.loop(Looper.java:157)
04-01 12:41:48.911: E/AuthZen(13848): 	at android.os.HandlerThread.run(HandlerThread.java:61)
04-01 12:41:51.206: E/ViewRootImpl(25286): Attempting to destroy the window while drawing!
04-01 12:41:51.206: E/ViewRootImpl(25286):   window=android.view.ViewRootImpl@42c21ff8, title=
04-01 12:41:51.306: E/ViewRootImpl(25286): sendUserActionEvent() mView == null
04-01 12:41:53.136: E/GameAgent(13848): Unable to retrieve application XXXXXXXXXX from network
04-01 12:41:53.141: E/GameAgent(13848): Application ID XXXXXXXXXX is not associated with package XXXXXXXXXXXXX. Check the application ID in your manifest.
