### ISSUE TITLE
java.lang.IllegalStateException when returning from Play Games profile to game

### ISSUE THREAD

**Issue by timobleeker** [playgameservices/play-games-plugin-for-unity#482]
I'm using the Google Play Service package 0.9.15 and the Google Play Services Rev 23, and building to a Nexus 5 with android 5.1

Whenever I view the leaderboards > click on my user icon > view my Play Games profile > press back button until I'm back into my game, the Google Play Services crashes with `IllegalStateException`. 

I'm not really sure if I'm doing something wrong, or this is a bug. I'm followed the Readme.

```
04-27 16:28:49.774: E/AndroidRuntime(15071): FATAL EXCEPTION: main
04-27 16:28:49.774: E/AndroidRuntime(15071): Process: com.google.android.gms.ui, PID: 15071
04-27 16:28:49.774: E/AndroidRuntime(15071): java.lang.RuntimeException: Unable to stop activity {com.google.android.gms/com.google.android.gms.games.ui.client.leaderboards.ClientLeaderboardListActivity}: java.lang.IllegalStateException: GoogleApiClient instance not created yet
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3670)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at android.app.ActivityThread.access$1400(ActivityThread.java:151)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at android.os.Looper.loop(Looper.java:135)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at java.lang.reflect.Method.invoke(Native Method)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
04-27 16:28:49.774: E/AndroidRuntime(15071): Caused by: java.lang.IllegalStateException: GoogleApiClient instance not created yet
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at com.google.android.gms.games.ui.p.x(SourceFile:714)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at com.google.android.gms.games.ui.p.onStop(SourceFile:466)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1277)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at android.app.Activity.performStop(Activity.java:6142)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3665)
04-27 16:28:49.774: E/AndroidRuntime(15071): 	... 10 more
```

**Comment by claywilkinson** [comment]
This has been fixed a while back.  Please open an issue if still having problems.
