### ISSUE TITLE
PlayGamesPlatform vs Social

### ISSUE THREAD

**Issue by firegate666** [playgameservices/play-games-plugin-for-unity#821]
Hi, I had quite a hassle to get the google play services running.
I set up 5 achievements, 1 leaderboard, configured everything, submitted the game and tested it.

Nothing popping up. I tried a bit around and figured out that

    PlayGamesPlatform.instance.Authenticate();

is triggering the google play services popup with permission request but

    Social.localUser.Authenticate();

is not. What is the difference and what should I use?

**Comment by claywilkinson** [comment]
Once the PlayGamesPlatform.Instance.Activate() is called, the instance is set to the implementation of the Social interface, so either should work after Activate().  The PlayGamesPlatform API is specific to Google Play Game Services, so there are additional parameters and control in the calls.  The Social API is a more generic interface, which is sometimes too simplistic for a game that needs finer grain control.

**Comment by firegate666** [comment]
Ah, that explains a lot :-)

Follow up question: Although the play games popup is shown and accepted, no achievement IR score is posted. Any chance how I can debug this? Is there any more parameter other than success that I can inspect?

**Comment by claywilkinson** [comment]
Using logcat is the best way to debug things like that.  In virtually all cases there will be a warning or error message which will help figure out the issue.

**Comment by firegate666** [comment]
Thx, will have a look at logcat. I've deployed another alpha using a mix of PlayGamesPlatform and Social, but there are no achievements. Anything obvious I am missing?

    // recommended for debugging:
    PlayGamesPlatform.DebugLogEnabled = true;
    // Activate the Google Play Games platform
    PlayGamesPlatform.Activate();
        
    Social.Active.localUser.Authenticate((bool success) => {
        if (success)
        {
            playStoreAuth = true;
            Debug.Log("authenticate google play store successfull");
        }
        else
        {
            playStoreAuth = false;
            Debug.Log("authenticate google play store failed");
        }
    });

    // unlock achievement (achievement ID "Cfjewijawiu_QA")
    if (Social.localUser.authenticated)
    {
        Social.ReportProgress(achievementId, 100.0f, (bool success) =>
        {
            if (success)
            {
                Debug.Log("report progress success: " + achievementId);
            } else
            {
                Debug.LogError("report progress failed: " + achievementId);
            }
        });
    } else
    {
        Debug.LogError("report progress failed, not authenticated: " + achievementId);
    }

**Comment by firegate666** [comment]
This thing is driving me crazy. Meanwhile I figured out, that the success response is false when authenticating. Ok. I have browsed again through the documentation and figured out this keystore thing.

So I printed the SHA1 and created the API/Android entry and linked it to my app. Do I have to do something with the key it generates me?

I have uploaded the app again. New stuff, it asked again for logging in into playstore - has not done this since my first try -, I checked all the permissions but again: success === false.

I must be missing something really important here :-(

**Comment by claywilkinson** [comment]
You should not need to upload to the playstore to test the game - at least in the sense that it does not affect how the APIs work.

It sounds like maybe it is the player is not listed as a tester for the game?  Sometimes the log might have a message indicating what is going on, so it is a good idea to look there for a clue too.

Here is the list of things to check:

The thinks to check:
1. the bundle name in Unity matches the bundle/package id in the Android App linked to your game on the Play games console.
2. the SHA1 fingerprint of the keystore you are signing your game with matches the fingerprint entered in the same linked app as  the package id.
3. the player you are logging in as is added as a tester for the game in the play games console.

**Comment by firegate666** [comment]
That is interesting about the not publishing and testing, never considered that this is possible. So it should be enough to push the game to my device and launch it? I will check this. Will bosst my development cycle a lot.

I can put a check to everything you mentioned. package name matches, SHA1 matches, player is tester. I think I will reset the whole player store app and service connection and setup everything new. This drives me crazy :)

**Comment by firegate666** [comment]
Ok, now I have a stacktrace :)

If I get this correct, he is missing some kind of app <-> client ID thing?

    SignInIntentService: There is no linked app associated with this client ID.

```
11-25 11:20:25.764  1020  1301 E Surface : getSlotFromBufferLocked: unknown buffer: 0x9e57acc0
11-25 11:20:25.920   203   797 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
11-25 11:20:25.920   203   797 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
11-25 11:20:26.344   777 17169 D NetlinkSocketObserver: NeighborEvent{elapsedMs=7494383, 172.17.64.1, [02E052EC3601], RTM_NEWNEIGH, NUD_REACHABLE}
11-25 11:20:26.686   777  2716 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
11-25 11:20:26.693   777 17217 D WifiService: acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@1c43bc}
11-25 11:20:26.694   777   994 D wifi    : Initialized common fields 10000, 16, 100, 10
11-25 11:20:26.694   777   994 D wifi    : bucket[0] = 2:3:10000:2
11-25 11:20:26.707  1558 26586 I EventLogService: Aggregate from 1448445021939 (log), 1448445021939 (data)
11-25 11:20:26.806 26553 26553 E ViewRootImpl: Attempting to destroy the window while drawing!
11-25 11:20:26.806 26553 26553 E ViewRootImpl:   window=android.view.ViewRootImpl@fc632f, title=
11-25 11:20:26.810 26553 26566 E Surface : getSlotFromBufferLocked: unknown buffer: 0xa95d1b80
11-25 11:20:26.811   777  2695 W DropBoxManagerService: Dropping: event_data (39 > 0 bytes)
11-25 11:20:26.821   777  2695 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
11-25 11:20:26.838   777  2838 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
11-25 11:20:26.841  1446  1446 V GLSActivity: AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
11-25 11:20:26.842  2609  2609 I Keyboard.Facilitator: onFinishInput()
11-25 11:20:26.846  1558  1558 D ChimeraCfgMgr: Loading module com.google.android.gms.games from APK com.google.android.play.games
11-25 11:20:26.846  1558  1558 D ChimeraModuleLdr: Module APK com.google.android.play.games already loaded
11-25 11:20:26.898  1446  1446 V GLSActivity: AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
11-25 11:20:26.900   777  1045 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
11-25 11:20:26.904  1446  1446 V GLSActivity: AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
11-25 11:20:26.906  1446  1446 V GLSActivity: AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
11-25 11:20:26.918  1558  1558 D ChimeraCfgMgr: Loading module com.google.android.gms.games from APK com.google.android.play.games
11-25 11:20:26.919  1558  1558 D ChimeraModuleLdr: Module APK com.google.android.play.games already loaded
11-25 11:20:27.328   777  2694 D WifiService: releaseWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@1c43bc}
11-25 11:20:27.487  1446 26629 W CursorWindow: Window is full: requested allocation 241 bytes, free space 236 bytes, window size 2097152 bytes
11-25 11:20:27.492  1558 26606 V BaseAuthAsyncOperation: access token request successful
11-25 11:20:27.554  1558  1558 D ChimeraCfgMgr: Loading module com.google.android.gms.games from APK com.google.android.play.games
11-25 11:20:27.554  1558  1558 D ChimeraModuleLdr: Module APK com.google.android.play.games already loaded
11-25 11:20:27.820  1558 26605 W BaseAppContext: Using Auth Proxy for data requests.
11-25 11:20:28.212  1558 26605 D ChimeraCfgMgr: Loading module com.google.android.gms.games from APK com.google.android.play.games
11-25 11:20:28.212  1558 26605 D ChimeraModuleLdr: Module APK com.google.android.play.games already loaded
11-25 11:20:28.364  1558  1558 D ChimeraCfgMgr: Loading module com.google.android.gms.games from APK com.google.android.play.games
11-25 11:20:28.364  1558  1558 D ChimeraModuleLdr: Module APK com.google.android.play.games already loaded
11-25 11:20:28.449  1558  5355 E Volley  : [138] BasicNetwork.performRequest: Unexpected response code 401 for https://www.googleapis.com/games/v1/players/me?language=de_DE
11-25 11:20:28.508  1558 26605 E SignInIntentService: There is no linked app associated with this client ID.
11-25 11:20:28.508  1558 26605 E SignInIntentService: com.google.android.gms.games.server.error.GamesException
11-25 11:20:28.508  1558 26605 E SignInIntentService: 	at com.google.android.gms.games.server.GamesServer.getResponseBlocking(GamesServer.java:164)
11-25 11:20:28.508  1558 26605 E SignInIntentService: 	at com.google.android.gms.games.broker.PlayerAgent.getPlayerFromNetwork(PlayerAgent.java:1671)
11-25 11:20:28.508  1558 26605 E SignInIntentService: 	at com.google.android.gms.games.broker.PlayerAgent.fetchPlayer(PlayerAgent.java:604)
11-25 11:20:28.508  1558 26605 E SignInIntentService: 	at com.google.android.gms.games.broker.DataBroker.loadSelf(DataBroker.java:941)
11-25 11:20:28.508  1558 26605 E SignInIntentService: 	at com.google.android.gms.games.service.PlayGamesSignInIntentService$LoadSelfOperation.executeInternal(PlayGamesSignInIntentService.java:405)
11-25 11:20:28.508  1558 26605 E SignInIntentService: 	at com.google.android.gms.games.service.PlayGamesSignInIntentService$BaseOperation.execute(PlayGamesSignInIntentService.java:53)
11-25 11:20:28.508  1558 26605 E SignInIntentService: 	at com.google.android.gms.games.service.PlayGamesSignInIntentService$OperationAdapter.execute(PlayGamesSignInIntentService.java:490)
11-25 11:20:28.508  1558 26605 E SignInIntentService: 	at com.google.android.gms.chimera.BaseAsyncOperationService$OperationTask.run(BaseAsyncOperationService.java:179)
11-25 11:20:28.508  1558 26605 E SignInIntentService: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-25 11:20:28.508  1558 26605 E SignInIntentService: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-25 11:20:28.508  1558 26605 E SignInIntentService: 	at com.google.android.gms.common.util.concurrent.PriorityRunnable.run(PriorityRunnable.java:17)
11-25 11:20:28.508  1558 26605 E SignInIntentService: 	at java.lang.Thread.run(Thread.java:818)
11-25 11:20:28.511 26553 26553 E LoadSelfFragment: Unable to sign in - application does not have a registered client ID
11-25 11:20:28.511 26553 26553 W SignInActivity: onSignInFailed()...
11-25 11:20:28.511 26553 26553 W SignInActivity: ==> Returning non-OK result: 10004
11-25 11:20:28.543 26430 26430 V GamesNativeSDK: Received Activity Resume Event.
11-25 11:20:28.554  2609  2609 I Keyboard.Facilitator: onFinishInput()
11-25 11:20:28.579   777  1045 I ActivityManager: Killing 22914:com.vevo/u0a110 (adj 15): empty #17
11-25 11:20:28.580  1558  4576 W GamesServiceBroker: Client connected with SDK 8115000, Services 8301438, and Games 34120038
11-25 11:20:28.582 26553 26566 E Surface : getSlotFromBufferLocked: unknown buffer: 0xa95d0dc0
11-25 11:20:28.586   203   797 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
11-25 11:20:28.588 26430 26462 W libc    : pthread_create sched_setscheduler call failed: Operation not permitted
11-25 11:20:28.600   203   796 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
11-25 11:20:28.600   203   796 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(15)
11-25 11:20:28.600   203   796 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)
11-25 11:20:28.602   203   796 D audio_hw_primary: enable_audio_route: apply and update mixer path: low-latency-playback
11-25 11:20:28.813  1558  1558 D ChimeraCfgMgr: Loading module com.google.android.gms.cast from APK com.google.android.gms
11-25 11:20:28.820  1558 26655 D MdnsClient: Multicast lock held. Releasing
11-25 11:20:28.822 26430 26430 V GamesNativeSDK: Play Games callback indicates connection failure.
11-25 11:20:28.822 26430 26519 I GamesNativeSDK: UI interaction required to connect to Google Play.
11-25 11:20:28.934  1446 26629 I PhenotypeFlagCommitter: Experiment Configs successfully retrieved for com.google.android.gms.playlog.uploader
11-25 11:20:28.936  1446 26629 I GoogleURLConnFactory: Using platform SSLCertificateSocketFactory
11-25 11:20:29.063  1446 26629 W CursorWindow: Window is full: requested allocation 241 bytes, free space 236 bytes, window size 2097152 bytes
11-25 11:20:29.827  1558  4576 W GamesServiceBroker: Client connected with SDK 8115000, Services 8301438, and Games 34120038
11-25 11:20:29.830  1558  1558 D ChimeraCfgMgr: Loading module com.google.android.gms.games from APK com.google.android.play.games
11-25 11:20:29.830  1558  1558 D ChimeraModuleLdr: Module APK com.google.android.play.games already loaded
11-25 11:20:29.841 26430 26430 V GamesNativeSDK: Play Games callback indicates connection failure.
11-25 11:20:29.841 26430 26519 I GamesNativeSDK: UI interaction required to connect to Google Play.
11-25 11:20:30.080   213   269 I ThermalEngine: TM Id 'SKIN_THERMAL_management_1' Sensor 'xo_therm_pu2' - alarm raised 1 at 41.0 degC
11-25 11:20:30.085   213   269 I ThermalEngine: ACTION: CPU - Setting CPU[0] to 1958400
11-25 11:20:30.085   213   269 I ThermalEngine: ACTION: CPU - Setting CPU[1] to 1958400
11-25 11:20:30.085   213   269 I ThermalEngine: ACTION: CPU - Setting CPU[2] to 1958400
11-25 11:20:30.085   213   269 I ThermalEngine: ACTION: CPU - Setting CPU[3] to 1958400
11-25 11:20:30.085   213   269 I ThermalEngine: ACTION: LCD - Setting max LCD brightness to 229
11-25 11:20:30.845  1558 24182 W GamesServiceBroker: Client connected with SDK 8115000, Services 8301438, and Games 34120038
11-25 11:20:30.851  1558  1558 D ChimeraCfgMgr: Loading module com.google.android.gms.games from APK com.google.android.play.games
11-25 11:20:30.851  1558  1558 D ChimeraModuleLdr: Module APK com.google.android.play.games already loaded
11-25 11:20:30.860 26430 26430 V GamesNativeSDK: Play Games callback indicates connection failure.
11-25 11:20:30.860 26430 26519 I GamesNativeSDK: UI interaction required to connect to Google Play.
11-25 11:20:31.866  1558  1570 W GamesServiceBroker: Client connected with SDK 8115000, Services 8301438, and Games 34120038
11-25 11:20:31.870  1558  1558 D ChimeraCfgMgr: Loading module com.google.android.gms.games from APK com.google.android.play.games
11-25 11:20:31.870  1558  1558 D ChimeraModuleLdr: Module APK com.google.android.play.games already loaded
11-25 11:20:31.889 26430 26430 V GamesNativeSDK: Play Games callback indicates connection failure.
11-25 11:20:31.889 26430 26519 I GamesNativeSDK: UI interaction required to connect to Google Play.
11-25 11:20:31.889 26430 26544 I Unity   :  [Play Games Plugin DLL] 11/25/15 11:20:31 +01:00 DEBUG: Starting Auth Transition. Op: SIGN_IN status: ERROR_NOT_AUTHORIZED
11-25 11:20:31.889 26430 26544 I Unity   :
11-25 11:20:31.889 26430 26544 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
11-25 11:20:31.889 26430 26544 I Unity   :
11-25 11:20:31.891 26430 26544 I Unity   : AuthState == Unauthenticated calling auth callbacks with failure
11-25 11:20:31.891 26430 26544 I Unity   :
11-25 11:20:31.891 26430 26544 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
11-25 11:20:31.891 26430 26544 I Unity   :
11-25 11:20:31.899 26430 26462 I Unity   :  [Play Games Plugin DLL] 11/25/15 11:20:31 +01:00 DEBUG: Invoking user callback on game thread
11-25 11:20:31.899 26430 26462 I Unity   :
11-25 11:20:31.899 26430 26462 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
11-25 11:20:31.899 26430 26462 I Unity   :
11-25 11:20:31.899 26430 26462 E Unity   : authenticate google play store failed
11-25 11:20:31.899 26430 26462 E Unity   :
11-25 11:20:31.899 26430 26462 E Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
11-25 11:20:31.899 26430 26462 E Unity   :
```

**Comment by claywilkinson** [comment]
You can definitely just build and run locally, you only need to publish the app to the play store when you want to distribute it.  Testers can load the .apk with `adb install` and test (provided they are listed as testers in the game configuration).

Yes, something is not configured correctly on the [Play Game Console](https://play.google.com/apps/publish), or does not match how your app is configured.

Unfortunately, this error could mean that the packageId + SHA1 fingerprint from the application does not match any linked application, or that the app ID for the game is not associated with the application.

**Comment by firegate666** [comment]
Ok, I have unpublished my app, unpublished the services and deleted the console api project.

Then I first created the console project and added my SHA1 hash, then I created the app, then linked the new services.

Now it works out of the box^^

Thanks for all your help! Any thanks for this awesome library

**Comment by claywilkinson** [comment]
Thanks for the update.  I am glad you got it working!
