### ISSUE TITLE
Invitation does not start game

### ISSUE THREAD

**Issue by gamozome** [playgameservices/play-games-plugin-for-unity#827]
I am getting invitation in inbox, but when i accept then its starts app but does not call OnRoomConnected().

Is there any listener method that should be called after invitation  accept ??

public void OnInvitationReceived(Invitation invitation, bool shouldAutoAccept) 
	{		
		if (shouldAutoAccept)
                 {			
			PlayGamesPlatform.Instance.RealTime.AcceptInvitation(invitation.InvitationId, this);			
		}
                else 
                 {			
			mIncomingInvitation = invitation;
		}
	}

Everything working good with OnQuickMatch().

**Comment by gamozome** [comment]
E/CellLocation(  923): create GsmCellLocation

E/CellLocation(  923): create GsmCellLocation

I/Unity   ( 4055): Starting sign-in...

I/Unity   ( 4055):  

I/Unity   ( 4055): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   ( 4055): 

E/dalvikvm( 4132): Could not find class 'android.transition.Transition', referenced from method android.support.v4.app.BackStackRecord.captureExitingViews

E/dalvikvm( 4132): Could not find class 'android.transition.Transition', referenced from method android.support.v4.app.BackStackRecord.configureTransitions

E/dalvikvm( 4132): Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.uidHasPackageName

E/        (  137): AudioCloseDumpPCMFile file== NULL

E/        (  137): AudioCloseDumpPCMFile file== NULL

E/ViewRootImpl( 4132): Attempting to destroy the window while drawing!

E/ViewRootImpl( 4132):   window=ViewRoot{420cbbc8 ,ident = 1}, title=

E/dalvikvm( 4132): Could not find class 'android.test.IsolatedContext', referenced from method com.google.android.gms.games.util.PanoUtils.isPano

I/Unity   ( 4055): In Auth callback, success = True

I/Unity   ( 4055):  

I/Unity   ( 4055): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 65)

I/Unity   ( 4055): 

E/dalvikvm( 4132): Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.google.android.gms.games.ui.client.ClientFragmentActivity.instantiateGoogleApiClient

E/dalvikvm( 4132): Could not find class 'com.google.android.gms.games.ui.GamesFragmentActivity$1', referenced from method com.google.android.gms.games.ui.GamesFragmentActivity.onCreate

E/dalvikvm( 4132): Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.google.android.gms.games.ui.GamesFragmentActivity.updateTaskDescription

E/dalvikvm( 4132): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.google.android.gms.games.ui.util.UiUtils.constructButtonBackground

E/        (  137): AudioCloseDumpPCMFile file== NULL

E/        (  137): AudioCloseDumpPCMFile file== NULL

E/        (  137): AudioCloseDumpPCMFile file== NULL

E/        (  137): AudioCloseDumpPCMFile file== NULL

E/libjingle(26152): Error(mediasession.cc:529): cricket::SessionDescription* cricket::MediaSessionDescriptionFactory::CreateOffer(const cricket::MediaSessionOptions&, const cricket::SessionDescription*): Creating Data offer.

E/libjingle(26152): Error(basicpacketsocketfactory.cc:67): UDP bind failed with error 22

E/libjingle(26152): Error(basicpacketsocketfactory.cc:67): UDP bind failed with error 22

E/libjingle(26152): Error(basicpacketsocketfactory.cc:67): UDP bind failed with error 22

E/libjingle(26152): Error(basicpacketsocketfactory.cc:67): UDP bind failed with error 22

I/Unity   ( 4055): NullReferenceException: Object reference not set to an instance of an object

I/Unity   ( 4055):   at PlusNetworkManager.OnRoomConnected (Boolean success) [0x00000] in <filename unknown>:0 

I/Unity   ( 4055):   at GooglePlayGames.Native.NativeRealtimeMultiplayerClient+OnGameThreadForwardingListener+<RoomConnected>c__AnonStorey42.<>m__51 () [0x00000] in <filename unknown>:0 

I/Unity   ( 4055):   at GooglePlayGames.OurUtils.PlayGamesHelperObject.<Update>m__B (System.Action a) [0x00000] in <filename unknown>:0 

I/Unity   ( 4055):   at System.Collections.Generic.List`1[System.Action].ForEach (System.Action`1 action) [0x00000] in <filename unknown>:0 

I/Unity   ( 4055):   at GooglePlayGames.OurUtils.PlayGamesHelperObject.Update () [0x00000] in <filename unknown>:0 

I/Unity   ( 4055):  

I/Unity   ( 4055): (Filename:  Line: -1)

I/Unity   ( 4055): 

E/InputDispatcher(  549): channel '429815c0 com.Gamozome.CarSimulator3D/com.unity3d.player.UnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

E/AudioService(  549): handleConfigurationChanged() createInstance IAudioServiceExt fail

E/AudioService(  549): java.lang.RuntimeException

E/AudioService(  549): 	at com.mediatek.common.MediatekClassFactory.createInstance(MediatekClassFactory.java:584)

E/AudioService(  549): 	at android.media.AudioService.handleConfigurationChanged(AudioService.java:5916)

E/AudioService(  549): 	at android.media.AudioService.access$8500(AudioService.java:108)

E/AudioService(  549): 	at android.media.AudioService$AudioServiceBroadcastReceiver.onReceive(AudioService.java:4085)

E/AudioService(  549): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:788)

E/AudioService(  549): 	at android.os.Handler.handleCallback(Handler.java:800)

E/AudioService(  549): 	at android.os.Handler.dispatchMessage(Handler.java:100)

E/AudioService(  549): 	at android.os.Looper.loop(Looper.java:194)

E/AudioService(  549): 	at com.android.server.ServerThread.run(SystemServer.java:1327)

E/        (  137): AudioCloseDumpPCMFile file== NULL

E/        (  137): AudioCloseDumpPCMFile file== NULL

**Comment by gamozome** [comment]
Anyone???? can help??
If you wont more code then text me.. help me

**Comment by claywilkinson** [comment]
This looks like some jar files are missing from your build?  It does not look specifically related to play game services: 
`Could not find class 'android.transition.Transition', referenced from method android.support.v4.app.BackStackRecord.captureExitingViews`

Check the Plugins/Android directory for anything unusual.  Also, try running Window > Google Play Games > Setup > Android Setup... again to copy the correct libraries into the plugins directory.

**Comment by claywilkinson** [comment]
Closing this since it has been a long time with no activity.  Please open another issue with updated information if this is still a problem.
