### ISSUE TITLE
CreateWithInvitationScreen() crashes application (QuizRacer example)

### ISSUE THREAD

**Issue by hapticdata** [playgameservices/play-games-plugin-for-unity#90]
Hello,

I am trying to develop a game using play-games-plugin-for-unity's RTMP. I have successfully authenticated, unlocked achievements etc… but every time that I use the `PlayGamesPlatform.Instance.RealTime.CreateWitInvitationScreen( MinOpponents, MaxOpponents, GameVariant, listener)` the game crashes with message "GameName has stopped working" before returning to unity. After failing multiple times I tried the [QuizRacer](https://github.com/playgameservices/play-games-plugin-for-unity/tree/b107a56b29847820c47a306db8fc010de3a735f5/samples/QuizRacer) example and noticed it has the same problem.

```
E/AndroidRuntime(16307): FATAL EXCEPTION: main
E/AndroidRuntime(16307): java.lang.Error: FATAL EXCEPTION [main]
E/AndroidRuntime(16307): Unity version     : 4.3.4f1
E/AndroidRuntime(16307): Device model      :  xxxxxxxx
E/AndroidRuntime(16307): Device fingerprint: xxxxxxx
E/AndroidRuntime(16307):
E/AndroidRuntime(16307): Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9876, result=-1, data=Intent { (has extras) }} to activity {xxxxxx/com.google.example.games.pluginsupport.SelectOpponentsHelperActivity}: java.lang.NullPointerException
E/AndroidRuntime(16307): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3322)
E/AndroidRuntime(16307): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3365)
E/AndroidRuntime(16307): 	at android.app.ActivityThread.access$1100(ActivityThread.java:144)
E/AndroidRuntime(16307): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285)
E/AndroidRuntime(16307): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(16307): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(16307): 	at android.app.ActivityThread.main(ActivityThread.java:5078)
E/AndroidRuntime(16307): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(16307): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(16307): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:802)
E/AndroidRuntime(16307): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:569)
E/AndroidRuntime(16307): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(16307): Caused by: java.lang.NullPointerException
E/AndroidRuntime(16307): 	at com.google.example.games.pluginsupport.SelectOpponentsHelperActivity.deliverSuccess(SelectOpponentsHelperActivity.java:47)
E/AndroidRuntime(16307): 	at com.google.example.games.pluginsupport.UiHelperActivity.onActivityResult(UiHelperActivity.java:57)
E/AndroidRuntime(16307): 	at android.app.Activity.dispatchActivityResult(Activity.java:5293)
E/AndroidRuntime(16307): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3318)
E/AndroidRuntime(16307): 	... 11 more
W/ActivityManager(  824):   Force finishing activity xxxxxxxxxxx/com.google.example.games.pluginsupport.SelectOpponentsHelperActivity
```

I have tested this on a device running Android 4.4.2 as well as 4.2.2.
I am developing on a Mac, with Unity 4.3.4f1 and using C# w/ MonoDevelop.

Any help is really appreciated! 
Thank you for your assistance.

**Comment by claywilkinson** [comment]
Closing as obsolete - the plugin has been re-architected so the call stack referenced is no longer relevant.
