### ISSUE TITLE
Crash Report Related to Google Play Plugin

### ISSUE THREAD

**Issue by kromenak** [playgameservices/play-games-plugin-for-unity#93]
Hi there, we recently got a crash report from a user with log output.  I thought it might provide some valuable information for bug fixing:

```
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9001, result=10002, data=null} to activity {com.companyredacted.gameredacted/com.google.example.games.pluginsupport.SignInHelperActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.deliverResults(ActivityThread.java:2553)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:2595)
	at android.app.ActivityThread.access$2000(ActivityThread.java:121)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:973)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3701)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.google.example.games.basegameutils.GameHelper.onActivityResult(GameHelper.java:633)
	at com.google.example.games.pluginsupport.SignInHelperActivity.onActivityResult(SignInHelperActivity.java:34)
	at android.app.Activity.dispatchActivityResult(Activity.java:3908)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:2549)
	... 11 more
```
Device Info:
OS: Android 2.3.4 - API 10
Device: Sony Ericsson - WT19a
Screen: 480 x 320 (160 dpi)

**Comment by claywilkinson** [comment]
Closing as obsolete, the plugin was reimplemented and this call stack is out of date.
